### ISSUE TITLE
Edit Disclaimer Bullets on Intro Page

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#102]
### Description

Need to change the disclaimer bullets in this order:
EN
- **This is not an application.** You'll get a list of your possible benefits.
- Your answers are **not** shared, saved, or submitted.
- **Answer more questions** to get better results.

ES
- **Esto no es una aplicación.** Esta página le ayudará a encontrar posibles beneficios.
- Sus respuestas **no** serán compartidas o guardadas.
- **Responda más preguntas** para obtener mejores resultados.

### User Story

As a user I need to know this tool is not an application.

**Comment by scottqueen-bixal** [comment]
We are in code freeze until post v2.beta0.1.0 release. Please organize with @fongcindy for these types of updates to align with product roadmapping.

Noting a few other things here that need to be included/confirmed as part of this request.

1. copy in the description doesn't match what we currently have in application
2. do we need to make the same changes in `es`, if so please provide that copy

**Comment by diegocob** [comment]
The idea was to change this back in Oct. If it can be done great or we wait for post-mvp. 

Added the ES in the description. The updated text of the form is on the [DOLO content Gdoc](https://docs.google.com/document/d/1wt3hIA6vd6XuiS5XCkY5YhMLxysawxu-lnTvAytt2VA/edit)

**Comment by diegocob** [comment]
This was done a while ago. Probably with another tix:)
