### ISSUE TITLE
Add CrazyEgg scripts to Disability pages in CMS

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1020]
### Description

Add one script for each snapshot (even when there are multiple snapshots with the same URL).
Snapshots are set to go live at 1pm on March 7.

1. https://www.usa.gov/es/buscador-beneficios/discapacidad (desktop)
```
<!-- Track a specific Crazy Egg snapshot by name -->
<script type="text/javascript">
    var CE_SNAPSHOT_NAME = "Benefit finder: disability | Virtual Page 1";
</script>
```

2. https://www.usa.gov/es/buscador-beneficios/discapacidad (desktop)
```
<!-- Track a specific Crazy Egg snapshot by name -->
<script type="text/javascript">
    var CE_SNAPSHOT_NAME = "Buscador beneficios: discapacidad | Virtual Page 1";
</script>
```

3. https://www.usa.gov/es/buscador-beneficios/discapacidad (desktop)
```
<!-- Track a specific Crazy Egg snapshot by name -->
<script type="text/javascript">
    var CE_SNAPSHOT_NAME = "Buscador beneficios: discapacidad | Virtual Page 2";
</script>
```

4. https://www.usa.gov/es/buscador-beneficios/discapacidad
```
<!-- Track a specific Crazy Egg snapshot by name -->
<script type="text/javascript">
    var CE_SNAPSHOT_NAME = "Buscador beneficios: discapacidad | Results Page";
</script>
```

### Acceptance Criteria

- [ ] scrips are available in the `<head />` element on ussagov production for each of the described LifeEvents

**Comment by nickpistone** [comment]
Additional notes: the snapshot for virtual page 2 may not include the military questions since I took the screenshot without answering any of the questions on that page. The snapshot for the benefits page may not look right since the screen looks different every time. But we might still be able to get some useful information from the element list. I'm only creating a few snapshots for now to test out how it works.

**Comment by scottqueen-bixal** [comment]
@gchi25 you can use DOLO as an example to see how we implemented this work previously

**Comment by nickpistone** [comment]
Gene just added one script to the English Disability page Header HTML (I miswrote the URL in the description and accidentally pasted in the Spanish URL for all 4 scripts). Then he added the 3 next scripts all together to the Header HTML field of the Spanish Disability page. We only kept the comment of the first one to not be repetitive.  I will check back this afternoon to make sure the data is being collected.

**Comment by nickpistone** [comment]
<img width="852" alt="Screenshot 2024-03-07 at 11 21 35 AM" src="https://github.com/GSA/px-benefit-finder/assets/121254111/6e9ff435-155a-4296-a6bc-8b4502e93dcf">

**Comment by gchi25** [comment]
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/ed110f5d-06d1-4a85-8910-a19a41a28f41)

**Comment by nickpistone** [comment]
<img width="851" alt="Screenshot 2024-03-07 at 11 23 03 AM" src="https://github.com/GSA/px-benefit-finder/assets/121254111/56c0f618-4cdd-480b-aab5-3455606a3c86">
