### ISSUE TITLE
SEO Audit Issues Mega Ticket

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1027]
### Description

Verify that all SEO audit issues have been addressed as needed.
[BF SEO Audit Issue Summary.docx](https://github.com/GSA/px-benefit-finder/files/14529583/BF.SEO.Audit.Issue.Summary.docx)

**Comment by scottqueen-bixal** [comment]
I left comments on #1028 , #1032, and #1033 for follow up or consideration.

**Comment by diegocob** [comment]
To confirm if @erniedeeb would like us to work on the Twitter card and possibly for other social media like FB and LI.

Converted the attached Word doc to [Gdocs here.] so we can add comments (https://docs.google.com/document/d/1nfxcghGIzn0AWZ27GhsiNVpksmmm7CV2/edit?usp=sharing&ouid=107288689112956295907&rtpof=true&sd=true)
