### ISSUE TITLE
Address missing H1 on BF LE pages

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1028]
### Description

This issue is present on the following pages:
/retirement
/disability
/death
/muerte
/jubilacion
/discapacidad

It is not present on the BF landing page in English or Spanish. There appears to be an H1 at the top of each page. But for some reason, it was identified in the site crawl for LE pages and not for the landing page. So we might not need to do anything, but we should at least verify that the H1 is set up properly.

### User Story

#1027

**Comment by scottqueen-bixal** [comment]
Most likely ahref tool is flagging this before the content loads, confirming we have h1 in our DOM.

<img width="1437" alt="Screenshot 2024-03-07 at 4 40 17 PM" src="https://github.com/GSA/px-benefit-finder/assets/37077057/6a9e7577-4577-4235-8f08-42d00632a212">

### Some options to resolve:

**Option 1.** 

Modify page template to let TOME generate static content from Drupal on initial view of life event page and only Instantiate JS application when user clicks 'Start'

**LOE** - Medium to Large

**Option 2.**

Leave as is. 

- There's no evidence that headings in and of themselves are a Google ranking factor.
- There have been plenty of research on the lack of impact for missing `<H1 />` on SEO rankings like https://moz.com/blog/h1-seo-experiment while others state "small but positive impact" https://www.semrush.com/blog/anatomy-of-top-performing-articles/
- We are not technically missing `<H1 />` so accessibility is not impacted
- other metadata is static and available for site crawlers

I'd like to experiment with Option 1. for several reasons related to performance, like the  reduction of visible load time to the end user and the improved performance metrics we might receive on first contentful paints.

**Comment by nickpistone** [comment]
@scottqueen-bixal I only made this ticket to make everyone aware of this in case it might be indicative of some other issue. But I don't think we need to fix every issue and I agree with your points that it's not impacting search rankings. I'll leave it up to you if you think there would be additional benefits to load time or something else by going with Option 1. I'm ok with either one.

**Comment by scottqueen-bixal** [comment]
Option 3, 

implement `<H1/>` in static build, then remove on rehydration and replace with application DOM

**Comment by nickpistone** [comment]
I will have to crawl this when it's live to prod to verify
