### ISSUE TITLE
Address sitemap missing indexable page issue

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1034]
### Description

/benefit-finder and /buscador-beneficios are in the sitemap, but the life experiences pages are not. Add the following pages to the sitemap and submit to Google via Search Console (David Kaufmann can submit).

/benefit-finder/death
/benefit-finder/disability
/benefit-finder/retirement
/es/buscador-beneficios/muerte
/es/buscador-beneficios/jubilacion
/es/buscador-beneficios/discapacidad

### User Story

#1027

**Comment by scottqueen-bixal** [comment]
USAGov has a custom sitemap module, @gchi25 please connect with Isabel to better understand why or how to get our life event pages added

https://github.com/usagov/usagov-2021/blob/51f718db42b9516296b06ec3119514a46760a3e3/web/modules/custom/usagov_sitemap/usagov_sitemap.info.yml

**Comment by gchi25** [comment]
https://github.com/usagov/usagov-2021/pull/1575
Added BF pages to sitemap.

**Comment by scottqueen-bixal** [comment]
closing as completed
