### ISSUE TITLE
Results page CTA buttons adjustment

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1041]
### Description

Currently we see that the CTA buttons (to visit agency site) in the results page are quite wide. The CTA buttons throughout the tool is consistent and smaller. 

![image](https://github.com/GSA/px-benefit-finder/assets/128498116/d1b22709-541b-4cf9-841e-515b0227a9a3)

### User Story

As a DOLO user, I expect all CTA buttons to be the same size from start to finish (landing page to results page)

### Acceptance Criteria

The width of the CTA button is smaller, this is an example of the longest text we are expecting to see. All CTA buttons need to match
![image](https://github.com/GSA/px-benefit-finder/assets/128498116/9f0f0863-ffd7-4421-bdd8-6b14f5efb521)

Expected for the following release **after** v0.2.0.beta.1

**Comment by EnriqueOrt** [comment]
#48 for reference

**Comment by scottqueen-bixal** [comment]
Closing as duplicate
