### ISSUE TITLE
Change "Click to select" in SP combo box

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1043]
### Description

Need to change Spanish select combo box text: Presione para seleccionar --> Presione aquí

### User Story

Need to simplify how user click and read on the page

### Acceptance Criteria

As a content editor need to know what branch to make these changes in.

**Comment by scottqueen-bixal** [comment]
Removing myself since no support needed

**Comment by fongcindy** [comment]
@diegocob Angelina, Ernesto and Scott have decided to change what we currently have: 

The select field text shows "Select" and "select an option" 
![Image](https://github.com/user-attachments/assets/0503a5d3-99ff-4896-b465-0f4ddfa394fa)

To changing the "select an option" to just "Select" 
![Image](https://github.com/user-attachments/assets/78757e0a-7fba-4dcb-a7f6-729018379726)

Could you provide the translation of just "select" and get approval from USAGov content? 
Thank you

**Comment by diegocob** [comment]
The ES translation of Select-->Seleccione

**Comment by fongcindy** [comment]
Some clarification:
"Select" goes inside the box
"Select an option" is on top of the box, on the outside. 

We currently have "Select" on top of the box, we would like it to say "Select an option".
If this content change works, can you provide the Spanish translation to "Select an option"?

**Comment by diegocob** [comment]
When using "Select an option" in Spanish we can use "Seleccione una opción".

**Comment by diegocob** [comment]
Hi Cindy, Sorry I missed this. 
**ES Translation:** 
Select an option-->Seleccione una opción
