### ISSUE TITLE
Make content QA changes on Github branch

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1052]
### Description

As a content editor, I need to make content changes based on UX research to look like the [Figma file](https://www.figma.com/proto/jt1oS8sGYDJn0MjYaprQkM/BEARS-DESIGN?type=design&node-id=3409-4351&viewport=1234%2C1257%2C0.25&t=Mjghweb0M0fQxwtP-0&scaling=min-zoom&starting-point-node-id=3409%3A4351&show-proto-sidebar=1): 
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/c3a9b223-e291-42e9-a050-1f1e5ae10ce8)

### User Story

As a content editor I need a branch on the Github repo to make these changes.

**Comment by diegocob** [comment]
@scottqueen-bixal, created a ticket to track these changes.

**Comment by scottqueen-bixal** [comment]
removing myself since no support needed

**Comment by diegocob** [comment]
Was complete a while ago.

**Comment by diegocob** [comment]
@ErnestoFernandezAlvarez, we made some changes and added them to the [Summary component doc](https://docs.google.com/document/d/1tzHCq6SySEK6XlHD7Yxzm56WpPbls-fVAZ8FKXcqBmA/edit)

# English content suggestions:
Bullet 1
Current: For full eligibility and requirements visit each agency providing the benefit.
Suggested: Visit each agency’s website to find full eligibility requirements.

Bullet 2 
Current:  Modifying your responses and completing more questions may open your eligibility to other benefits
Suggested: Your results may change if you answer more questions or modify your answers.

Bullet 3
Current: To restart the form click here
Suggested: Clear my answers and restart the form.

# Spanish
Importante
Bullet 1
Current: Para confirmar su eligibilidad necesita visitar el enlace de cada agencia.
Suggested: Visite el sitio web de cada agencia para confirmar su elegibilidad y requisitos.

Bullet 2 
Current:  Si modifica sus respuestas o responde más preguntas podría ser elegible para más beneficios.
Suggested: Sus resultados podrían cambiar si responde más preguntas o modifica sus respuestas.

Bullet 3
Current: Para confirmar el formulario de nuevo seleccione aquí
Suggested: Borrar mis respuestas y empezar el formulario de nuevo
