### ISSUE TITLE
Create Downloadable Spreadsheet from content on CMS

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1053]
### Description

Create a way and format to download BF content to a Sheets doc.

### User Story

Content editors need to view all the content on the CMS in a file to count, compare, and analyze the content. Doing it manually creates margin for errors and does not allow bird's eye view of all the content.

### Acceptance Criteria

The downloaded doc has all the information in separate fields for: 
- - [ ] Agency
- - [ ] Criteria
- - [ ] Life event forms
- - [ ] Benefits

**Comment by scottqueen-bixal** [comment]
@gchi25 can coordinate

**Comment by diegocob** [comment]
Will ask Gene whenever these are needed. 
Ernie asked for a doc to show agencies their benefits on BF. Created this [benefit template](https://docs.google.com/spreadsheets/d/1w8AiViPHRRFkaHbaaP5jUfuoA-0IQmFFXv9jLOtf2CQ/edit?usp=sharing) for agencies and shared with Ernie. 

Closing this ticket out, not sure if we need anything from Ernie atm - @fongcindy
