### ISSUE TITLE
Coordinate content update in USAGov prod

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1071]
### Description

Content update management.
Coordinate content update in USAGov prod.
Coordinate DEV content related testing.
Make sure no issue for generating JSON data files.

### Acceptance Criteria

Content update in prod.
Make sure no issue for generating new JSON data files.

**Comment by gchi25** [comment]
cms.usa.gov
Benefit Finder content last updated on 02/16/2024

bf-cms-dev.bxdev.net 
Has USAGov prod database of March 12, 2024
Benefit Finder content last updated on 02/16/2024

[Death of a loved one - life event form content](https://docs.google.com/document/d/1wt3hIA6vd6XuiS5XCkY5YhMLxysawxu-lnTvAytt2VA/edit)
Death of a loved one
Benefit Finder - life event form content

Changes highlighted in the document:

- Answer these questions
- About the applicant
- About the deceased
- American Indian
- Coal mines  

  
Hold content update till release
Perform life event form content update in cms.usa.gov as draft mode
  
After release,
Generate draft JSON data files
Perform QA on Benefit Finder App in draft mode
Publish updated life event form
Generate JSON data files

**Comment by diegocob** [comment]
This is WIP
| Status | Before | After | Comment |
|----------|---------|----------|----------|
|  | | |

**Comment by EnriqueOrt** [comment]
Gene owns the bulk of work. Diego to QA and verify

**Comment by scottqueen-bixal** [comment]
closing as completed
