### ISSUE TITLE
Automate draft JSON data file generation

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1111]
### Description

Automate draft JSON data file generation.

### User Story

As content editor, I need to add/update benefit finder content first in draft mode. 
I like the system automatically generate draft JSON data file when I save the draft content. So I can perform QA on my newly added/updated content in benefit finder tool running in draft mode.

### Acceptance Criteria

When content editors save benefit content, the system will automatically generate draft JSON data files.

**Comment by diegocob** [comment]
How should I QA this? Is this only in Dev mode? 
@gchi25

**Comment by diegocob** [comment]
This is completed on ticket #1208
