### ISSUE TITLE
Automate draft JSON data file generation in Benefit Finder configuration

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1112]
### Description

In Benefit Finder configuration page, add "Automate draft JSON data file generation".

### User Story

As Benefit Finder administrator, I like to manage "Automate draft JSON data file generation" function.
I like to have a checkbox in Benefit Finder configuration page for me to make this function on and off.

### Acceptance Criteria

In Benefit Finder configuration page, the system provides a checkbox "Automate draft JSON data file generation" for Benefit Finder administrator to make this function on and off.

**Comment by diegocob** [comment]
Not working on this tix. No need for QA content atm.
