### ISSUE TITLE
Automate JSON file generation testing

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1117]
### Description

With "automate JSON data file generation" on, the system will automatically generate draft and published JSON data file when content changed.
Perform some content change testing.

### User Story

As automate JSON data file generation on, the system will automatically generate draft and published JSON data files when content changed.
We will perform a series of content change testing to test if there are some potential content changes that can break the application workflow, like JSON data file generation and React running.

### Acceptance Criteria

Design and perform a series of content change testing with automate JSON data file generation on.
The Benefit Finder application works well as expected without breaking from content changes.

**Comment by gchi25** [comment]
https://github.com/GSA/px-benefit-finder/issues/1141
Generate only draft JSON data files when content saved as draft.

**Comment by EnriqueOrt** [comment]
@diegocob to test once this work is completed. No work needed at this time

**Comment by gchi25** [comment]
In Benefit Finder DEV site, bf-cms-dev.bxdev.net
The "Automate generate JSON data files" is enabled.
When content changes and saved as draft, the system immediately generates DRAFT JSON data files. And You can test Benefit Finder app in draft mode.
When content saved as published, the system immediately generates real JSON data files. And You can test Benefit Finder app in real mode.
For example, if you change life event form of "Benefit Finder: death of a loved one" and save as draft, you can test life event page using draft mode.
http://bf-cms-dev.bxdev.net/benefit-finder/death?mode=draft
If you further save as published, you can test life event page in real mode.
http://bf-cms-dev.bxdev.net/benefit-finder/death

**Comment by diegocob** [comment]
QA completed. 

@gchi25 I tested making changes on the Dev environment for published and draft changes and they were all reflected on the Dev life event forms.
