### ISSUE TITLE
Benefit finder style not loading properly in Safari v17.0

### ISSUE THREAD

**Issue by Ndoyle118** [GSA/px-benefit-finder#1122]
### What's expected

When loading the Benefit Finder tool in Safari, the style of the tool is expected to match the design that has been live since the launch, as shown in the attached screenshots of how the tool looks in my Google Chrome browser.

![Image](https://github.com/GSA/px-benefit-finder/assets/99103193/313f039c-e9bb-4f97-ba75-225235e3da57)
![Image](https://github.com/GSA/px-benefit-finder/assets/99103193/a665637d-be0f-4daf-9d9e-bf05070b1c80)

### What happened

When opening all three versions of the Benefit Finder tool (DOLO, retirement, and disability) with Safari, the page style and design do not load correctly, displaying instead a more minimal outline of the page content shown in the images attached. 

![Image](https://github.com/GSA/px-benefit-finder/assets/99103193/f6dd1e0b-fdd7-4ca1-8b94-154bfe48478f)
![Image](https://github.com/GSA/px-benefit-finder/assets/99103193/c1ceb5ac-b322-43c0-a2d2-dc5098e07e55)
![Image](https://github.com/GSA/px-benefit-finder/assets/99103193/23c226d3-22ca-4b6b-87d4-d75f214c14a4)
![Image](https://github.com/GSA/px-benefit-finder/assets/99103193/01b16e47-ac6a-4ebf-8689-8525862c0d4c)

### How to replicate

The problem seems to be localized to Safari. To replicate the problem, use Safari v17.0 and open the BF tool. It seems to reproduce the issue regardless of whether you navigate to the tool by entering the URL directly into the address bar, navigating to the tool through USA.gov, or clicking on the BF link through a Google search.

**Comment by scottqueen-bixal** [comment]
Discovery

In v.0.2.0.1.beta.1 we updated our release to include nested css stylesheets.  Unfortunately this is not fully supported in safari versions 16.5 - 17.1 without specific syntax.  



![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/2c515e1d-11e0-46e9-a541-b8e3dc517486)

We will need to update our production build script to include a fix for this.
