### ISSUE TITLE
Uncaught Type Error – GoogleAnalyticsObject is not a function.

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/px-benefit-finder#1124]
### What's expected

When a user accesses various benefits on www.usa.gov/benefit-finder, the application should not display Uncaught Type Error – GoogleAnalyticsObject is not a function

### What happened

With dev tools open when a user access the benefit below, the error "Uncaught Type Error – GoogleAnalyticsObject is not a function" is displayed. This is causing the Cypress automated tests to fail.
https://www.usa.gov/benefit-finder/death
https://www.usa.gov/es/buscador-beneficios/muerte
https://www.usa.gov/benefit-finder/retirement
https://www.usa.gov/es/buscador-beneficios/jubilacion
https://www.usa.gov/benefit-finder/disability
https://www.usa.gov/es/buscador-beneficios/discapacidad

![image](https://github.com/GSA/px-benefit-finder/assets/121119072/d43592de-ef3f-4228-aed2-d9c58f2a774f)

### How to replicate

Navigate to https://www.usa.gov/benefit-finder
Open developers tool and click on the console tab
Navigate through the links in each benefit and not the error

Uncaught TypeError: window[window.GoogleAnalyticsObject] is not a function
    at createTracker (Universal-Federated-Analytics.js:546:5)
    at _onEveryPage (Universal-Federated-Analytics.js:108:3)
    at Universal-Federated-Analytics.js:111:1
![google-analytics-uncaught-type-error](https://github.com/GSA/px-benefit-finder/assets/121119072/70056fd8-7b3f-4eee-b8a7-068b4d453fda)

**Comment by nickpistone** [comment]
I'm following up with David Kaufmann on this

**Comment by nickpistone** [comment]
Hi @nehemiah-abuga, I'm meeting with David Kaufmann to discuss this and some other follow-up items. I see that you listed out the life experience pages in English and Spanish. Is this error happening on any other USAGov pages outside Benefit Finder? And is it happening on the BF landing page?

**Comment by nehemiah-abuga** [comment]
> Hi @nehemiah-abuga, I'm meeting with David Kaufmann to discuss this and some other follow-up items. I see that you listed out the life experience pages in English and Spanish. Is this error happening on any other USAGov pages outside Benefit Finder? And is it happening on the BF landing page?

@nickpistone  - On the other pages I see a different type error. Mostly I see errors like the one below
<img width="1324" alt="image" src="https://github.com/GSA/px-benefit-finder/assets/121119072/4d41a34d-207c-4f31-bd6e-b87ad7f12e5c">

**Comment by nickpistone** [comment]
Followed up last Friday with Eric Moreno. He responded and is following up with the team.

**Comment by nickpistone** [comment]
Eric Moreno from DAP confirmed that this code will be removed on June 26 as Universal Analytics is sunset. So this is resolved.
