### ISSUE TITLE
Reduce benefit title character count

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1135]
### Description

Need to reduce the length of the benefit titles so they fit with the new button design [1118](https://github.com/GSA/px-benefit-finder/issues/1118).

New titles are in the [Content Data Bank](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit#gid=0): Column F in EN and O in ES.

### User Story

As a user I need to have a uniquely descriptive button. Screen reader users should know the difference between each button.

### Acceptance Criteria

- [x] Approval from Ernie
- [x] Makes changes in CMS

**Comment by diegocob** [comment]
@ernie do you think we can go ahead with these changes?

**Comment by ernie** [comment]
@diegocob I'll approve anything but that's because I am the wrong @ernie :D

**Comment by diegocob** [comment]
> @diegocob I'll approve anything but that's because I am the wrong @ernie :D

Sorry about that @ernie. Thanks for letting me know.

**Comment by diegocob** [comment]
The Real @erniedeeb, approved changes and made them in CMS. Will close this ticket and create another one for the QA.

**Comment by diegocob** [comment]
Made these changes in Dev envi will now make in the prod site.

**Comment by diegocob** [comment]
##Shorten titles
Reduce character length on these titles for a better fit in the benefit accordion CTA

##EN/ES
Tracked changes in this doc [Shortening benefit titles](https://docs.google.com/document/d/12AhEkppUYrAANC8zQucdDbAtuzmN2Y-P-x_0SNAHayw/edit?usp=sharing)

**Comment by diegocob** [comment]
@gchi25 I finished shortening the titles and tracked them in the document above. Could you please review and let me know when the json file is generated to view in sand or prod envi?

**Comment by diegocob** [comment]
Done. Created ticket #1172 to QA changes in Dev and in Prod.
