### ISSUE TITLE
Generate draft JSON data files when content saved as draft

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1141]
### Description

When content changed and saved as draft, only generate draft JSON data files.

### User Story

As content editor, when I add and/or change content and save as draft, I want to generate draft JSON data files and run Benefit Finder app in draft mode to perform QA on my content change.

### Acceptance Criteria

When content saved as draft, generate draft JSON data files.

**Comment by diegocob** [comment]
Is this for the main site? Is there anything I should do to generate the json file?
