### ISSUE TITLE
benefit-finder-cms-main app stuck

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1148]
### What's expected

main cms app in cloud should be available as a service

### What happened

app is STOPPED

seems stuck in "Offline while Updating"

https://dashboard.fr.cloud.gov/applications/2oBn9LBurIXUNpfmtZCQTCHnxUM/5fdf89fe-fddb-4b68-b8f8-435007d610e4/summary

- tried starting, restarting, restagging, all through cli and in UI

```bash
➜ cf restage benefit-finder-cms-main
This action will cause app downtime.

Restaging app benefit-finder-cms-main in org gsa-tts-usagov / space benefit-finder-main as geoffrey.queen@gsa.gov...

Staging app and tracing logs...
space's memory limit exceeded: staging requires 1024M memory
FAILED
```

### How to replicate

log in to cloud, view application service status

currently results in
"Offline while updating"

**Comment by casey-rapnicki-bixal** [comment]
App couldn't start due to low memory.
