### ISSUE TITLE
Benefit Accordions Re-design

### ISSUE THREAD

**Issue by ErnestoFernandezAlvarez** [GSA/px-benefit-finder#1179]
### Description

As part of the redesign following USA.gov guidelines and recommendation, I am iterating on some new accordion designs.
I am consulting with Nick and Angelina in order to address feedback from AT testing sessions.

**Comment by ErnestoFernandezAlvarez** [comment]
Hi guys
As an update I am copying my Slack post:

Yesterday I presented the new accordion design options to [USA.gov](http://usa.gov/) (Link bellow). It was very well received!
I will be waiting for their formal feedback and direction on these. I mentioned that our team is in favor of "Summary With Checkmark for Met Criteria & Bulleted List for Unmet Criteria" vs  "Summary With Checkmark and Cross-mark" for the "Not eligible" accordion model.
Please feel free to leave any feedback or comments in the Figma file.
https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=3213%3A22070&mode=design&t=XF64bNWk1Ow1AOpk-1
Also, please note I added a third version to the "Need more info" accordion: a link to go "Back to form" directly from the section "Needs more information"

**Comment by EnriqueOrt** [comment]
Presented to USAgov and will wait for feedback. Ernesto thinks it may take some time.

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @EnriqueOrt 
I am keeping this ticket active. I have received feedback from Maria as of 4/30 and will continue working on it:

**Hola Ernesto!

Thanks for sending the designs over and working on all the variations for us to compare the various treatments. Below is my feedback after also talking to other designers on the team: 

Summary box - good with the overall design
Change the "Important" heading to Source Sans Pro typeface as the USWDS component suggests and bold it.
In the guidance for this component, the usage of ordered lists is not recommended, so if we keep the bullets-only layout, we are good.
Accordions - they are looking great!
The preference here is to go with the unframed but centered-aligned CTA. All of the accordions in USAGov are unframed, so we would want to keep that consistency. 
We thought the darker gray used as the background in the opened accordion and/or the hover works well as it drives your eye to the content inside. So, we are going to take that treatment and request that all accordions in USAGov be updated to match it. Thanks for making it clear to us with this example. 
I am excited about these updates and please let me know if you have any further questions. 

Thank you for working on these!**

**Comment by ErnestoFernandezAlvarez** [comment]
The design of these accordions have been approved by client. Closing tkt.

![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/bf6aebb9-2af9-4a7c-ac7f-d4e808492c51)
