### ISSUE TITLE
Notices list should not include informational alerts

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1182]
### What's expected

notices list should not include the alert component, this causes some unnecessary markup and is not expected with AT users.

### What happened

current notices list includes alert component

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/ee0b7cf0-6b24-4145-8724-98372c8ec811)

### How to replicate

- visit `/benefit-finder/death`
- inspect notices list

**Comment by ErnestoFernandezAlvarez** [comment]
Hi @EnriqueOrt @scottqueen-bixal 

I removed the alert icons, please see update on this board:
https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=2492%3A8020&mode=design&t=cQnUqowOT2o2Q9zM-1
<img width="544" alt="Screenshot 2024-04-16 at 4 28 49 PM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/4a1c5e48-74dc-4a4e-aa03-8a8c240b8be0">

**Please note** This page will most likely change with the redesign for USA.gov. Could we consider this a temporary update?
