### ISSUE TITLE
You vs Applicant Research

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1192]
### Description

Run unmoderated testings to define whether to use "you" or "the applicant" language on BF.

### User Story

As a user I need have a version of BF the works the best for me, where the purpose is clear and I get the most out of the tool.

As a UX team I need to design the webpage that is most engaging with users.

### Acceptance Criteria

- [ ] Create testing questions
- [ ] Create screenshots of tested content
- [ ] Run unmoderated sessions
- [ ] Evaluate results and make recommendations

**Comment by fongcindy** [comment]
Expected to start week of 4/22

**Comment by diegocob** [comment]
Breaking down this ticket.
Closing this ticket for this sprint as prep material for the research. 
Creating a new one for the research and if you'd like, to create a new one for the analysis and report @Ndoyle118

**Comment by fongcindy** [comment]
@diegocob Any reason why this has been moved from "done" to "no status"?

**Comment by diegocob** [comment]
Not sure why. Changing it back to done.
