### ISSUE TITLE
508 cursory review of SPA DOLO site

### ISSUE THREAD

**Issue by angelina-smith** [GSA/px-benefit-finder#1200]
Conduct a cursory high-level review of the Spanish DOLO site. Focus on:

- Review lang attributes with ANDI
- Ensure alt text is translated or are appropriately marked as decorative
- Screen reader review with @Ndoyle118 focusing on semantic / ARIA labels sound correct in Spanish

**Comment by fongcindy** [comment]
@angelina-smith Any updates on this ticket? Are you working on this currently?
