### ISSUE TITLE
Test coverage remove "skipFailOnError"

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1204]
### Description

We have `skipFailOnError` set to true because of known violations that have now been resolved

https://github.com/GSA/px-benefit-finder/blob/dev/benefit-finder/cypress/e2e/storybook/axe-a11y.cy.js#L136

### Acceptance Criteria

- [ ] remove configuration 
- [ ] ensure successful completion
- [ ] if errors are reported, tickets are created and discussed for next steps

**Comment by nehemiah-abuga** [comment]
Work completed. PR at https://github.com/GSA/px-benefit-finder/pull/1243
