### ISSUE TITLE
Button outline styles on focus are not displaying as expected

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1214]
### What's expected

`<Button />` components with the class `bf-usa-button--outline` should be styled to include 

> inner stroke is 2px #FFFFFF. The outer stroke is 2px #0186A2.

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/f36c2b6b-308c-46f3-88ec-3227ee436342)

### What happened

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/a9c29311-e08b-4916-916a-10a0fdffa3ed)

### How to replicate

- inspect DOM
- force `focus`
expected
- remove `bf-` prefixed classes

**Comment by erniedeeb** [comment]
Adding another point that was raised:

> I noticed the interior white stroke is missing from the error message fields. This contrast between the red of the alert and the dark aqua of the focus is 1.64, which I believe is insufficient (and why the white inner stroke is needed here).

![Image](https://github.com/GSA/px-benefit-finder/assets/7094493/750b98f9-2322-4f82-83d2-fda8a3cfbbfa)

**Comment by scottqueen-bixal** [comment]
> Adding another point that was raised:
> 
> > I noticed the interior white stroke is missing from the error message fields. This contrast between the red of the alert and the dark aqua of the focus is 1.64, which I believe is insufficient (and why the white inner stroke is needed here).
> 
> ![Image](https://private-user-images.githubusercontent.com/7094493/322939922-750b98f9-2322-4f82-83d2-fda8a3cfbbfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyOTIxMTUsIm5iZiI6MTcxMzI5MTgxNSwicGF0aCI6Ii83MDk0NDkzLzMyMjkzOTkyMi03NTBiOThmOS0yMzIyLTRmODItODNkMi1mZGE4YTNjZmJiZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTgyMzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmUwMzBlMTZiNzIyOTJhNDQzYjhhOWQxNzdhZmIxYjVjMGFkMzg0NmNkODc1Yjg0YWU0YTg3ODhlNzExYTU3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._s7UMevKXqHoc-LbFoYujdqCWBgH9wwcI_NGsRsr-7g)

Thanks @erniedeeb - i've created an issue for reviewing a11y concerns around contrast on form error states with focus tracking here -> https://github.com/orgs/GSA/projects/48/views/10?pane=issue&itemId=59970146
