### ISSUE TITLE
Backup JSON Data Files

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1215]
### Description

With automate JSON data file generation on, content team can generate JSON data files automatically. 
The new JSON data files will replace the existing JSON data files.
Develop a backup strategy to periodically back up the existing JSON data files in case the new JSON data files having issues.

### User Story

As Benefit Finder administrator, I want to have backup JSON data files available. If new JSON data files having issues and making Benefit Finder tool not working as expected, I can upload the backup JSON data files to make Benefit Finder tool working as expected and have time to identify and fix content issue.

### Acceptance Criteria

A JSON data file backup strategy.

**Comment by scottqueen-bixal** [comment]
Let's use Main as a source of archive, 

- each wed, (main/dev) gets db update - at which time we can regenerate all s3 files

Please create a ticket and work with Xavier to set up in our pipeline
