### ISSUE TITLE
BF form element description

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1216]
### Description

Add description for form elements of BF content form

- agency
- criteria
- benefit
- life event form

### User Story

As a content editor, I would like to have information and/or description of form elements in BF content forms.

### Acceptance Criteria
Information and/or description in form elements of BF content forms.

**Comment by diegocob** [comment]
@gchi25 what is this ticket for? Do you need anything from my end?
Wanted to close it out if not.

**Comment by scottqueen-bixal** [comment]
Not planned work
