### ISSUE TITLE
QA | Notices List

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#1218]
### Domain

design

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

[Notices list should not include informational alerts](https://github.com/GSA/px-benefit-finder/issues/1182)	https://github.com/GSA/px-benefit-finder/issues/1182

### Description

Notices list should not include the alert component, this causes some unnecessary markup and is not expected with AT users.

**Need design review based on accessibility updates.**

**Comment by scottqueen-bixal** [comment]
request for adjustment to list alignment suggested, closing
