### ISSUE TITLE
QA | Content Workflow

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#1219]
### Domain

Content

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

[Automate JSON file generation testing](https://github.com/GSA/px-benefit-finder/issues/1117)	https://github.com/GSA/px-benefit-finder/issues/1117
[Ensure that criteria content can not be deleted if still used](https://github.com/GSA/px-benefit-finder/issues/1157)	https://github.com/GSA/px-benefit-finder/issues/1157
[Automate draft JSON data file generation](https://github.com/GSA/px-benefit-finder/issues/1111)	https://github.com/GSA/px-benefit-finder/issues/1111
[Automate JSON data file generation](https://github.com/GSA/px-benefit-finder/issues/1060)	https://github.com/GSA/px-benefit-finder/issues/1060
[Ensure that agency content can not be deleted if still used](https://github.com/GSA/px-benefit-finder/issues/1156)	https://github.com/GSA/px-benefit-finder/issues/1156
[Generate draft JSON data files when content saved as draft](https://github.com/GSA/px-benefit-finder/issues/1141)	https://github.com/GSA/px-benefit-finder/issues/1141
[Add dependency in criteria](https://github.com/GSA/px-benefit-finder/issues/1159)	https://github.com/GSA/px-benefit-finder/issues/1159
[Remove life events field in life event form](https://github.com/GSA/px-benefit-finder/issues/1171)	https://github.com/GSA/px-benefit-finder/issues/1171
[Automate draft JSON data file generation in Benefit Finder configuration](https://github.com/GSA/px-benefit-finder/issues/1112)	https://github.com/GSA/px-benefit-finder/issues/1112

### Description

**Content review needed to finalize content workflow updates.**

**Comment by diegocob** [comment]
I'll go through these tickets and comment.

**Comment by diegocob** [comment]
Met with @gchi25 and went over these tickets. 
Commented on most of them. All of the QA that can be done for now is done. Will need further QA once the items are completed from the dev side.

**Comment by diegocob** [comment]
I believe Gene, addressed all these tickets, and more, on [tix 1208](https://github.com/GSA/px-benefit-finder/issues/1208)
I completed all content QA there.

@gchi25, please confirm.
