### ISSUE TITLE
QA | Analytics

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#1221]
### Domain

data

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

[Add H1 in life event page template](https://github.com/GSA/px-benefit-finder/issues/1164)	https://github.com/GSA/px-benefit-finder/issues/1164
[Include rel with s3 link on template](https://github.com/GSA/px-benefit-finder/issues/1180)	https://github.com/GSA/px-benefit-finder/issues/1180
[Address missing H1 on BF LE pages](https://github.com/GSA/px-benefit-finder/issues/1028)	https://github.com/GSA/px-benefit-finder/issues/1028
[Add meta description field in life event](https://github.com/GSA/px-benefit-finder/issues/1166)	https://github.com/GSA/px-benefit-finder/issues/1166
[Add virtual page attribute to distinguish between the "pages" of the app and results pages](https://github.com/GSA/px-benefit-finder/issues/794)	https://github.com/GSA/px-benefit-finder/issues/794

### Description

**Analytics review needed on items listed above**

**Comment by fongcindy** [comment]
@nickpistone Any updates on this? QA is due tomorrow 4/24. Thanks!

**Comment by nickpistone** [comment]
[All issues — Cms-stage.usa.pdf](https://github.com/GSA/px-benefit-finder/files/15096460/All.issues.Cms-stage.usa.pdf)
[All issues — Cms.usa.pdf](https://github.com/GSA/px-benefit-finder/files/15096461/All.issues.Cms.usa.pdf)
All of the issues uncovered in the earlier site crawl are still showing up when I crawl cms.usa.gov or cms-stage.usa.gov. When the changes go to production then we may be able to confirm them with a site crawl of the production site.

**Comment by scottqueen-bixal** [comment]
@nickpistone we should be able to QA these two items in our current dev env

https://bf-cms-dev.bxdev.net/benefit-finder/death

https://github.com/GSA/px-benefit-finder/issues/1166 https://github.com/GSA/px-benefit-finder/issues/1166
https://github.com/GSA/px-benefit-finder/issues/794 https://github.com/GSA/px-benefit-finder/issues/794

Please validate by COB today.

**Comment by scottqueen-bixal** [comment]
dev site is now available for you to rerun a test using the scanning tool to confirm https://github.com/GSA/px-benefit-finder/issues/1028 https://github.com/GSA/px-benefit-finder/issues/1028
