### ISSUE TITLE
Set up local development site with Benefit Finder

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1239]
### Description

Make local usagov website running.
https://github.com/GSA/px-benefit-finder
checkout px-benefit-finder dev
install all the dependencies for React
$ cd benefit-finder
$ npm install
px-benefit-finder
$ bash scripts/pipeline/mv-benefit-finder-app.sh
$ bash scripts/pipeline/mv-usagov_benefit_finder.sh
$ cd usagov-2021
$ bin/drupal-update
Import Benefit Finder configuration
$ bin/drush cim --partial --source=modules/custom/usagov_benefit_finder/configuration
http://localhost

### Acceptance Criteria

The instruction of making local usagov development website running in px-benefit-finder README.md

**Comment by scottqueen-bixal** [comment]
this is running with local process on setup script https://github.com/GSA/px-benefit-finder/blob/dev/scripts/local/setup-usagov-benefit-finder.sh
