### ISSUE TITLE
Add break content lock permission to Benefit Finder Content Manager

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1246]
### Description

Benefit Finder Content Manager can not break content lock.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/ebb13929-354a-4844-b9bc-b850f5ba6065)

Need add "break content lock" permission to Benefit Finder Content Manager role.

### Acceptance Criteria

Benefit Finder Content Manager can break content lock.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/05310965-133e-4e61-a609-f34e11a35f22)

**Comment by diegocob** [comment]
Tried to break the lock but was not able to do it. Getting the message w/out the option to break the lock.
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/332d5e36-5e12-494b-b8c9-ee46e0f24ba4)

**Comment by gchi25** [comment]
https://github.com/usagov/usagov-2021/pull/1556
Added break content lock permissioin.
