### ISSUE TITLE
Content under life event link in Benefit Finder landing page / Meta Description

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1251]
### Description

Where does the content under life event link in Benefit finder landing page come from ?
<img width="600" src="https://github.com/GSA/px-benefit-finder/assets/88853916/4589d221-14a2-4ba3-9d08-48bc32eec4f0">

For example, the content under Benefit finder: death of a loved one
Find government survivor benefits including COVID-19 funeral benefits, housing, and education help.

https://bf-cms-dev.bxdev.net/benefit-finder
<img width="600" src="https://github.com/GSA/px-benefit-finder/assets/88853916/3e4d025b-81ca-4d4f-99a4-16616c067a65">

In DEV site, how to add/edit the content.

### Acceptance Criteria

Can add/edit content under life event link in Benefit finder landing page

**Comment by gchi25** [comment]
In life event, we add new field "Meta Description".
The Benefit Finder landing page uses the meta description in life event for the underlying content of life event link.
Once the new field "Meta Description" of life event in USAGov site, we need to update life event to add the meta description.

**Comment by diegocob** [comment]
Thanks for adding this @gchi25. Is there a way to separate the content on the landing page from the meta description or does it have to be the same?

@nickpistone and I were discussing this.

**Comment by gchi25** [comment]
https://github.com/GSA/px-benefit-finder/issues/1271
https://github.com/GSA/px-benefit-finder/pull/1273
Added short description and page intro field in life event.

What content to add in the fields of life event?

**Comment by diegocob** [comment]
Went over these changes with @gchi25.
Short description goes to the landing page and the meta description in DOM.
Need to clarify with the content team what the page intro is for.

**Comment by diegocob** [comment]
Added the Short and meta description in [Content Bank](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit#gid=661661717)/LE tab/rows 20 and 22
