### ISSUE TITLE
Duplicated questions in retirement form

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1264]
### What's expected

https://www.usa.gov/benefit-finder/retirement
The retirement form should not have duplicated questions.

### What happened

https://www.usa.gov/benefit-finder/retirement
The retirement form has following duplicated questions.
Did you ever work and pay U.S. Social Security taxes?

<img width="500" src="https://github.com/GSA/px-benefit-finder/assets/88853916/04c7eb3b-720d-4207-abd2-7c015f816ffb">

### How to replicate

Go to https://www.usa.gov/benefit-finder/retirement
Click start 
The retirement form shows duplicated questions.

**Comment by diegocob** [comment]
Corrected and published these on main site CMS. Please let me know when it is live @gchi25

**Comment by diegocob** [comment]
This was resolved. Changes were manually QA'd.
