### ISSUE TITLE
Update BF content management guide

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1267]
### Description

The automatic JSON data file generation is on USAGov prod. When content editor saves BF content as draft, the system will automatically generate draft JSON data files. When content editor publishes BF content, the system will automatically generate both draft and real JSON data files.

We also developed a series of methods to ensure BF content integrity to prevent the application program breaking and/or not functioning correctly from content entry. For example, a criteria content can not be deleted if it is still used.

We will update BF content management guide for content team to add, update, and delete BF content in the new environment.

### User Story

As content editor, I would like to have updated content management guide to add, update, and delete BF content with the new environment.

### Acceptance Criteria

Updated BF content management guide

**Comment by diegocob** [comment]
@gchi25 is this in addition to the doc you created or a new one?

**Comment by gchi25** [comment]
The automatic JSON data file generation is on in USAGov production.

**Comment by diegocob** [comment]
Is this completed, @gchi25? I reviewed the content entry guide you shared.

**Comment by scottqueen-bixal** [comment]
we need more specific tickets, this one is too general, try and avoid carrying tickets over multiple sprints
