### ISSUE TITLE
Content a11y: Vague and unclear labels for links and buttons. Device-neutral language on drop-down fields.

### ISSUE THREAD

**Issue by angelina-smith** [GSA/px-benefit-finder#1272]
### User / Persona

As an assistive technology user, link and button text needs to be descriptive and clear so that I understand what will happen when I interact with the element. As an AT user, the phrase "Click to select" on drop-down fields can be construed as offensive for those not using a mouse.

### Reason / Justification

So that when I pull up a list of links and/or buttons, I know exactly where I will be taken or what will happen when I select the element. Terminology for click insinuates mouse-usage and best practice is to avoid the word "Click" when possible.

### Acceptance Criteria (AC)

Improvements noted from AT UT sessions:
- [ ] Make “Start” button text (on main landing page) more descriptive
- [ ] Make “Review selections” button text (in modal) more clear
- [ ] Make “Open all +” and "Close all -" button text (on Results page) more descriptive

Improvements noted from USA.gov accessibility audit:
![image](https://github.com/GSA/px-benefit-finder/assets/142342010/bbc83f07-1ba9-43bf-9266-a1e56b00f9d4)

**Comment by fongcindy** [comment]
@diegocob Hi Diego! We plan to focus on addressing some of the items raised in USAGov's a11y audit for our current sprint, this was one of the items. 

Angelina has clearly described the changes that need to be made to meet the accessibility compliance, can you work on making these changes in content? These shouldn't take too long to address :)

**Comment by diegocob** [comment]
Made some suggestions in the upcoming [CMS Content changes 05/23/24 doc](https://docs.google.com/document/d/1VFz9ydmuo7yOQcjsFaaw_SVqHa9Ckp6nZ4thKOnPMms/edit?usp=sharing)

Please review and let me know.

**Comment by angelina-smith** [comment]
For some history and context of where this ticket came from:

- Vague and unclear labels for links and buttons: came from the AT UT sessions
- Device-neutral language on drop-down fields: came from USAgov's accessibility audit in early Jan

**Comment by diegocob** [comment]
I believe this was addressed already and we could close it, @angelina-smith.

**Comment by fongcindy** [comment]
@angelina-smith Are we able to close this ticket? Have the ACs been met?

**Comment by angelina-smith** [comment]
@fongcindy @diegocob Yes we're able to close this ticket! Sorry for the delay!
