### ISSUE TITLE
Summary Box & Accordions Edits | USAGov Design Feedback

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1274]
### Description

Received this feedback from Maria(USAGov) regarding the summary box and accordion [designs ](https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=3213%3A22070&mode=design&t=xL59KsciPj1VDvEc-1)

**Summary box** - 
Change the "Important" heading to Source Sans Pro typeface as the USWDS component suggests and bold it.
In the guidance for this component, the usage of ordered lists is not recommended, so if we keep the bullets-only layout, we are good.

**Accordions** - 
The preference here is to go with the unframed but centered-aligned CTA. All of the accordions in USAGov are unframed, so we would want to keep that consistency. 
We thought the darker gray used as the background in the opened accordion and/or the hover works well as it drives your eye to the content inside. So, we are going to take that treatment and request that all accordions in USAGov be updated to match it.

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @angelina-smith 
Here are the updates to the Summary Box:

- Font changed according to Maria's suggestion
- Keep bulleted list (do not use numbers)
- Third bullet changed to a more descriptive message (Angelina please confirm)

https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=3213%3A22070&mode=design&t=q0sy8tDr599Flpth-1
<img width="1021" alt="Screenshot 2024-05-07 at 10 57 17 AM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/46b21d71-ef32-4f4b-afc7-e71d0b469023">

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy 
These are the versions of the accordion cards for the 3 possible scenarios (Likely eligible, More information needed and Not eligible) reflect the client's design recommendations:
 
https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=3213%3A22070&mode=design&t=BLLTa16JFQR2ycC6-1

<img width="1918" alt="Screenshot 2024-05-07 at 1 33 53 PM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/e839fd2d-cac7-42aa-b856-a553596dba77">

**Comment by diegocob** [comment]
Adding some suggestions here. I made some suggestions to Ernie and he requested we share them with USAGov's content team. I'll share that input here and @ErnestoFernandezAlvarez can share with Maria and the UX team letting them know it hasn't been approved by the content team yet.

**Comment by diegocob** [comment]
@ErnestoFernandezAlvarez did you here anything from the a11y audit that they suggested not using "click". They said it could be abilist bc some people don't use a mouse or click. Will suggest something that matches what they shared.

**Comment by diegocob** [comment]
Here are some content suggestions

# Summary box component
## English content suggestions:
### Bullet 1
**Current:** For full eligibility and requirements visit each agency providing the benefit.
**Suggested:** Visit each agency to find full eligibility

### Bullet 2 
**Current:**  Modifying your responses and completing more questions may open your eligibility to other benefits
**Suggested:** Your results may change if you answer more questions or modify your answers

### Bullet 3
**Current:** To restart the form click here
**Suggested:** Clear my answers and re-start here

## Spanish
### Bullet 1
**Current:** Para confirmar su eligibilidad necesita visitar el enlace de cada agencia.
**Suggested:** Visite el enlace de cada agencia para confirmar su eligibilidad.

### Bullet 2 
**Current:**  Si modifica sus respuestas o responde más preguntas podría ser elegible para más beneficios.
**Suggested:** Sus resultados podrían cambiar si responde más preguntas o modifica sus respuestas.

### Bullet 3
**Current:** Para confirmar el formulario de nuevo seleccione aquí
**Suggested:** Borre sus respuestas y empiece de nuevo aquí

**Comment by ErnestoFernandezAlvarez** [comment]
Hello @fongcindy @diegocob 
Here is the final version: 
<img width="1024" alt="Screenshot 2024-05-08 at 1 13 06 PM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/fc83e588-d638-4afb-ad6d-a8d0d85ff035">

https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=3213%3A22070&mode=design&t=VJPQejsIlKZVMfCG-1

**Comment by ErnestoFernandezAlvarez** [comment]
I will be sharing the final version of the Summary Box and Accordion Cards with Maria

**Comment by diegocob** [comment]
Ernie made some [minor tweaks](https://docs.google.com/document/d/1VFz9ydmuo7yOQcjsFaaw_SVqHa9Ckp6nZ4thKOnPMms/edit#heading=h.qgaddehxzgzu). Waiting on a11y check by @angelina-smith on hyperlinking all of bullet #3.
