### ISSUE TITLE
Definition and usage of page intro, short description, and meta description

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1275]
### Description

Basic page has following fields:
- page intro
- hide page intro
- short description
- meta description

Life event adds the following fields:
- page intro
- short description
- meta description

Find more information about the definition and usage of these fields.

### Acceptance Criteria

Get the definition and usage of following fields:
- page intro
- hide page intro
- short description
- meta description

**Comment by diegocob** [comment]
This is clear @gchi25.
We just had to clarify what the page intro was for and where it shows up.

**Comment by scottqueen-bixal** [comment]
closing as completed
