### ISSUE TITLE
Discovery | LE Total Benefits

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1289]
### Description

Look into how many benefits there are per life event in Benefit Finder and Benefits.gov 
For BF, let's narrow down the list of LE to the top 3 LE with the most benefits:

becoming-a-parent	
financial-hardship	
military-service	
school-and-education	
national-emergency-and-disaster	
education

### Acceptance Criteria

Determine what the top 3 LEs are and discuss with UX team on which LE to focus on next

**Comment by fongcindy** [comment]
Diego has found the following:

**Benefits for each LE**
Financial hardship - 16
Becoming a parent - 3
Education - 2
National emergency and disaster - 2
School and education - 1

**Comment by diegocob** [comment]
Digging a little deeper on these. There are some old benefits that 10x identified that didn't have the full info, as well as the benefits.gov ones.

**Comment by diegocob** [comment]
Created this graphs of the [benefit count per life event](https://docs.google.com/presentation/d/10MTcKsb2KlqMaSt3N9TtdWEENzmG6tq2/edit?usp=sharing&ouid=107288689112956295907&rtpof=true&sd=true). Closing this ticket, we can discuss how it needs another level of analysis.

**Comment by diegocob** [comment]
This took longer than expected bc the benefit content bank had been updated from v1 and had to realign some of its functionality and lost data from the previous version.
