### ISSUE TITLE
Spanish DOLO - Estado civil needs to be a required field

### ISSUE THREAD

**Issue by angelina-smith** [GSA/px-benefit-finder#1302]
### What's expected

Location: Spanish DOLO site, 'Acerca del solicitante' (About the applicant) page
Expect 'Estado civil' to be a required field and mirror the 'Marital status' English DOLO site. I expect:

- [ ] Visual text stating this field is required: "**(requerido)**"
- [ ] The field is coded as required. 
- [ ] When the 'Estado civil' field has been completed, I expect to select the 'Continue' button to move to the next 'Acerca de la persona fallecida' portion.
- [ ] When the 'Estado civil' field has NOT been completed, if I select the 'Continue' button, I should be presented with an Error message.

### What happened

Estado civil form field is not marked required (with text and in code). Discrepancy between English site.
When I do not complete this field, I am able to press 'Continue' and proceed to the 'Acerca de la persona fallecida'.

![image](https://github.com/GSA/px-benefit-finder/assets/142342010/dda062bf-ccf5-4381-871c-ce7e53d079f5)

### How to replicate

Complete the required fields ('Fecha de nacimiento' and 'Relación del solicitante con la persona fallecida'), but leave 'Estado civil' uncompleted. Press Continue.

**Comment by angelina-smith** [comment]
History and context of where the ticket comes from:  Created in response to my cursory 508 audit of the Spanish DOLO site on 5/8/2024

**Comment by diegocob** [comment]
Corrected this on CMS prod. Changes should relfect soon.

**Comment by scottqueen-bixal** [comment]
removing myself since no support needed

**Comment by angelina-smith** [comment]
Confirmed that this is live on prod and is working as expected! Thanks @diegocob !
I'm going to close this!
