### ISSUE TITLE
April Data Pull

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1315]
### Description

GSA is requesting to see the data for the month of April: 
It's been awhile since the data was collected, LINK[https://docs.google.com/spreadsheets/d/13Xeszi5t7aZaEBSGFjE0Ui5_507JgI7eKBOJBkhJ15M/edit#gid=0](url)

We would like views, trends, and general data. 

### User Story

As a GSA stakeholder, I need to see how many views, organic sessions for LE pages for April

@EnriqueOrt for viz

**Comment by nickpistone** [comment]
https://docs.google.com/spreadsheets/d/13Xeszi5t7aZaEBSGFjE0Ui5_507JgI7eKBOJBkhJ15M/edit#gid=1580499216
Will this take care of it? I'm working on the dashboard which will have more in-depth metrics. So I don't want to spend too much time going in-depth here in the meantime.

**Comment by EnriqueOrt** [comment]
Will put this in Front of Ernie for review and let you know. Moving the ticket to QA

**Comment by EnriqueOrt** [comment]
@erniedeeb - could you please confirm if the data pull from the comment above will be enough data at this time? Thanks in advance

**Comment by erniedeeb** [comment]
@EnriqueOrt @nickpistone This works, the only thing I'd like to see is a separation of this round of data from the previous round, so we can more clearly see how performance has trended since the last pull.

**Comment by nickpistone** [comment]
@erniedeeb sure I'll do a few single-month pulls for January, February, March, and April. January won't be a full month since the first full day after launch was Jan 18th. I'm in the process of putting the data into Tableau, so I'll just put each individual month into the dashboard.
