### ISSUE TITLE
Update short description of live events

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1316]
### Description

Update short description of live events.
It is for the content under life event links of Benefit Finder landing pages.

https://www.usa.gov/benefit-finder
<img width="600" src="https://github.com/GSA/px-benefit-finder/assets/88853916/283180b9-6a2b-4d78-8b97-758d3ce71a8d">

https://www.usa.gov/es/buscador-beneficios
<img width="600" src="https://github.com/GSA/px-benefit-finder/assets/88853916/19142373-ca0a-4e29-b4ce-47907636e590">

Death
Find government survivor benefits including COVID-19 funeral benefits, housing, and education help.
 
Retirement
Find benefits for retirees and veterans to help with expenses, medical care, and more.
 
Disability
If you have a disability or qualifying illness, find benefits to help with bills, education, jobs, and more.
 
Buscador beneficios: muerte
Conozca a cuáles beneficios del Gobierno tiene derecho tras la muerte de un familiar; desde ayuda para gastos funerarios por COVID-19, hasta beneficios de vivienda y educación para sobrevivientes, entre otros.
 
Buscador beneficios: jubilación
Encuentre beneficios del Gobierno para jubilados y veteranos de ayuda para gastos, cuidado médico y más.
 
Buscador beneficios: discapacidad
Encuentre beneficios del Gobierno si tiene una discapacidad o enfermedad elegible para sus gastos, educación, trabajo y más.

### Acceptance Criteria

Updated short descriptions of live events show up in Benefit Finder landing pages.

**Comment by gchi25** [comment]
https://www.usa.gov/benefit-finder
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/aede07b9-3fa5-4776-90c7-521d7200010c)

https://www.usa.gov/es/buscador-beneficios
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/83a43df3-38d0-49a0-a8c6-1f096864d009)

**Comment by diegocob** [comment]
Suggest using the meta description in the [Content bank](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit#gid=661661717), see tab LE Form/row 5


![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/5e3e0626-e29d-4971-8803-ad039b24e67e)


Waiting to hear from @nickpistone about changing this

**Comment by nickpistone** [comment]
These are fine with me @diegocob

**Comment by diegocob** [comment]
@gchi25 updated the meta description. I'll close this ticket and QA in another ticket.
