### ISSUE TITLE
User Testing OLE

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1317]
### Description

Conduct unmoderated user testing for One life event form. 

### User Story

As a user I'd like to use a benefit finder with access to all benefits in a user friendly way.
As a UX team we need to validate that users are interested and able to use a one life event form.
  

### Acceptance Criteria

- [x] Create script for OLE
- [x] Schedule user testing sessions
- [ ] Conduct sessions
- [ ] Watch recordings
- [ ] Create another ticket for recommendations and summary of findings

**Comment by diegocob** [comment]
Created this ticket in the backlog for the user testing for OLE. Not sure if we'll be able to schedule these in this sprint.

Added @Ndoyle118, and @fongcindy for visibility.

**Comment by diegocob** [comment]
Worked with Gene to get the content we need to the main env so we could test it with external users. Will finish that today and will be ready for testing.

**Comment by diegocob** [comment]
Made all the changes on Main. Saved as draft: https://bf-cms-main.bxdev.net/benefit-finder/all-benefits?mode=draft

Had a chat with Nick, he is unable to access the main or dev envis. We think it's bc he doesn't have user access.

The link in main is still not accessible from our phones. Not sure if you'll lift the wafs or sth else to make it accessible.

**Comment by Ndoyle118** [comment]
Update: Sessions completed 6/20/24

**Comment by diegocob** [comment]
Closing out this ticket. We can create a new ticket to watch, analyze, and interpret the sessions.
