### ISSUE TITLE
Audit benefit count

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1320]
### Description

Need to see how many benefits are in each life event.

### User Story

As a content editor need to know if the benefits in Spanish and English and in the content bank are the same ones in the CMS.

**Comment by diegocob** [comment]
@gchi25 when you get a chance could you share how many benefits are in each life event form? 

Is there an archive where you save the json files so I can go there and get this info?

**Comment by gchi25** [comment]
https://www.usa.gov/benefit-finder/death
Go to life event page. 
Complete the form.
Inspect the result page, you can see the benefit count information.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/813d6152-4608-4417-a0e8-561571f41d3d)

**Comment by diegocob** [comment]
Great tip! Thanks, Gene! I'll audit them like this.

**Comment by diegocob** [comment]
This was completed last week through another ticket.
