### ISSUE TITLE
QA patch release

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1321]
### Domain

development

### App Improvements
- Fixes #1108

### Module Improvements 
- Fixes #1296 

### Description

Created PR in USAGov repo.
[PXBF Release v0.3.1.beta.1 #1578](https://github.com/usagov/usagov-2021/pull/1578)

Perform QA in local development site.
[Patch release completes work for Milestone v0.3.1.beta.1](https://github.com/GSA/px-benefit-finder/pull/1312)

**Comment by scottqueen-bixal** [comment]
closing as completed
