### ISSUE TITLE
Alert of Automatic Testing Failures | Broken Links

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1322]
### Description

Benefit Result links in the accordion were not working (Medicare Savings Plan), Diego was able to resolve by providing updated links for English and Spanish.

Brainstorm and set up solution of alert or notification of automatic testing failures of broken links and other issues. Currently Nehemiah has to go in and check manually, he is currently on leave. To make the process less manual, alerts can be emailed to Diego. 

### User Story

As a Content Strategist or QA Engineer, I need to be alerted via email when an automated test fails, so that I can resolve it immediately.

**Comment by scottqueen-bixal** [comment]
culprit is here, https://github.com/GSA/px-benefit-finder/blob/dev/benefit-finder/cypress.prod.config.js#L7

Looks like it was excluded and then targeted in a separate config -  here https://github.com/GSA/px-benefit-finder/blob/dev/benefit-finder/cypress.prod.links.config.js,

I think NA was in process of moving to its own action

**Comment by scottqueen-bixal** [comment]
Just added and ran the action agains prod, got some broken link errors

https://github.com/GSA/px-benefit-finder/actions/runs/9117204714/job/25067531002#step:4:435

for example: 

```
https://www.tsp.gov/

The response we received from your web server was:

  > 403: Forbidden

This was considered a failure because the status code was not `2xx` or `3xx`.
```

but it is accessible, https://www.tsp.gov/ - so I suspect that is a false positive

we will need to figure out how to exclude certain behaviors like this

**Comment by scottqueen-bixal** [comment]
**Options for alerts**

1. Users can subscribe to failed workflows here https://github.com/settings/notifications, 

Note: This is an all or nothing action.  But anyone interested in subscribing can filter out notifications in their outlook/email settings.

2. the other option, which is more effort would be to set up a 

> an SMTP server and then you configure a third party action

There are some infrastructure implications here that would need to be considered.

Recommend going with option (1) unless it is deemed we need to take another route.

**Comment by fongcindy** [comment]
@diegocob Can you try subscribing to the failed workflow as Scott mentioned above?

**Comment by scottqueen-bixal** [comment]
was able to sort out some issues with the test, https://github.com/GSA/px-benefit-finder/actions/runs/9119495537/job/25074965790

We will keep an eye on things during the next cron run

**Comment by diegocob** [comment]
I think I subscribed. Could we run a test to see if I am getting notified?

**Comment by scottqueen-bixal** [comment]
everything is passing at the moment, you get notified if there is a failure
