### ISSUE TITLE
Switch to supported Terraform backend for pipeline

### ISSUE THREAD

**Issue by casey-rapnicki-bixal** [GSA/px-benefit-finder#1329]
Currently, the Terraform remote state is being stored in S3. This would be fine, but cloud.gov doesn't support DynamoDB as a service, so we can not lock the state file to prevent multiple applies from happening simultaneously.

The purpose of this ticket is to move to a supported backend that can be locked and insure that their aren't any collisions when applying TF code via the pipeline.

**Comment by XavierMetichecchia** [comment]
@casey-rapnicki-bixal if I am not mistaken this issue may be closed now. If not can you point me in the right direction as to what may still need to be done.
