### ISSUE TITLE
#1341 Snyk fixes, default branch, GitHub Integration

### ISSUE THREAD

**Issue by XavierMetichecchia** [GSA/px-benefit-finder#1341]
### Description

This issue will track work done to fix the issue of Snyk not seeing the dev (new default) branch as the default for PRs. As well as attempt to fix GitHub/Snyk integration by renaming the snyk scanning yml.

### Acceptance Criteria

Integration in GitHub is working for Snyk and PRs for security fixes are being automatically created against the dev (new default) branch.

**Comment by scottqueen-bixal** [comment]
closing as complete
