### ISSUE TITLE
Unable to add meta description to 3 Life Events

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1363]
### Description

Need to update the meta description on the life events but am unable to do so on three nodes. 
## **Discapacidad**
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/41b120e0-5a12-4a39-8d1a-cbfd6cece6de)
## **Jubilación**
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/27dc398b-6335-4e38-828b-5a736b6694b0)
## **Death of a loved one**
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/5f3d7fb8-45fe-4fd9-9519-5fec9cdbd142)

## Was able to Update:
* Disability
* Retirement
* Muerte de un ser querido

The language toggle does not recognize the events and is not letting me save. Creating another ticket to address this.

### User Story

As a content manager I need to edit life events on the CMS.

### Acceptance Criteria

Able to edit all forms.

**Comment by gchi25** [comment]
Updated meta description of life events in USAGov prod.

**Comment by diegocob** [comment]
Thanks, @gchi25. Could you pleaselet us know when it's published so we can check it live?

**Comment by scottqueen-bixal** [comment]
@diegocob should be live, please confirm and QA

**Comment by diegocob** [comment]
The new meta descriptions are not showing up on Dev draft mode in the life events. The changes reflect in draft mode in Prod but not in Dev. Not sure why:

Prod:
![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/b0381f0b-c70c-4d15-b360-6726acf328d4)

Dev:
![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/690bb79a-3164-443b-9003-da4365b77f97)

**Comment by diegocob** [comment]
QA'd live and it looks good. It's not showing up in the Dev, maybe this newest version has not been pulled downstream. Closing out the ticket.
