### ISSUE TITLE
QA | a11y v0.4.0.

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#1366]
### Domain

a11y

### Related Issue(s)

[Error states on fields are failing contrast testing](https://github.com/GSA/px-benefit-finder/issues/1222)	https://github.com/GSA/px-benefit-finder/issues/1222
[Informational List on main page: adding alt-text on icons and removing alert components](https://github.com/GSA/px-benefit-finder/issues/1269)	https://github.com/GSA/px-benefit-finder/issues/1269
[Modal Buttons](https://github.com/GSA/px-benefit-finder/issues/1270)	https://github.com/GSA/px-benefit-finder/issues/1270
[Button outline styles on focus are not displaying as expected](https://github.com/GSA/px-benefit-finder/issues/1214)	https://github.com/GSA/px-benefit-finder/issues/1214

**Due by June 5th**, pending kickoff confirmation 

### Description

Accessibility final QA for a11y related updates

**Comment by angelina-smith** [comment]
QA complete of the four accessibility issues. I will be creating a follow up bug report for https://github.com/GSA/px-benefit-finder/issues/1269 as the informational icons in the disclaimer list require alt-text.
