### ISSUE TITLE
Re-audit updated MVP

### ISSUE THREAD

**Issue by amycole501** [GSA/px-benefit-finder#137]
[a11y | error handling date field](https://github.com/GSA/px-benefit-finder/issues/176) [#532](https://github.com/GSA/px-benefit-finder/issues/176)
[a11y | date input labels](https://github.com/GSA/px-benefit-finder/issues/177) [#531](https://github.com/GSA/px-benefit-finder/issues/177)
[a11y | step-indicator buttons](https://github.com/GSA/px-benefit-finder/issues/178) [#530](https://github.com/GSA/px-benefit-finder/issues/178)
[a11y | radio labels](https://github.com/GSA/px-benefit-finder/issues/185) [#511](https://github.com/GSA/px-benefit-finder/issues/185)
[a11y | unique ID's](https://github.com/GSA/px-benefit-finder/issues/186) [#510](https://github.com/GSA/px-benefit-finder/issues/186)
[a11y | tab order](https://github.com/GSA/px-benefit-finder/issues/188) [#508](https://github.com/GSA/px-benefit-finder/issues/188)
[a11y | color contrast](https://github.com/GSA/px-benefit-finder/issues/189) [#507](https://github.com/GSA/px-benefit-finder/issues/189)

**Comment by scottqueen-bixal** [comment]
I put any remaining tickets that had improvement comments in the product back log. We can work to iterate on those  in future sprints. cc: @fongcindy
