### ISSUE TITLE
QA | Design v0.4.0.

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#1380]
### Domain

design

### Related Issue(s)

[Button outline styles on focus are not displaying as expected](https://github.com/GSA/px-benefit-finder/issues/1214)	https://github.com/GSA/px-benefit-finder/issues/1214

Due June 5th - Pending Kickoff confirmation 

### Description

Design final QA for button funtionality related updates

**Comment by scottqueen-bixal** [comment]
closing in favor of https://github.com/orgs/GSA/projects/48/views/17?pane=issue&itemId=65027213
