### ISSUE TITLE
Required questions on Dev mode=draft

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1386]
### What's expected

Life events in Dev draft mode are showing to have all questions marked as required. Must be a bug bc it's not showing as required on the CMS or on Dev regular mode.
Muerte:
![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/1b7061ec-111d-47cf-b935-010248cb8045)

Jubilacion:
![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/54f8c3ad-c6be-4072-9f67-1eb6675d48e6)

Death:
![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/5b0b4e01-5339-4d1e-9730-0dad647033cb)

Disability:
![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/59766337-9c68-4ce3-b716-1404e692c8f8)

### What happened

Need to see the same content on the CMS as on the form. 

### How to replicate

Should only see the questions marked as required as required.

**Comment by gchi25** [comment]
Fixed the issues. 
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/09b28f1c-37cc-4f9f-9991-fd96782c7b4d)

**Comment by diegocob** [comment]
Thanks, Gene. Closing this out.
