### ISSUE TITLE
Requirements Gathering | Content for Integration

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#139]
`**Needs to be ready by 12/5**`

We need clear access to copy and paste values of content for the following items: 

in both  English and Spanish

1. Alias paths, ie. `benefit-finder/death`
2. Content for landing page `/benefit-finder`
3. Content for Block in view page `/benefits`

**Comment by EnriqueOrt** [comment]
@diegocob - we have confirmed the "ask" with the Tech team and they need links to the location of all the content. 
Content doesn't need to be centralized into a single doc, however, they need a clear map of access points to all content for the migration.

**Comment by diegocob** [comment]
Is [this G-doc](https://docs.google.com/document/d/1B19BMRftZq3kd-J93XjkY94PMXZE2oKQREOJiYEsoCk/edit) sort of what you are looking for or is this too basic?

**Comment by fongcindy** [comment]
We need all 3 items requested by 12/5 prior to deployment, everything should be in the CMS. 

IF **not**, here's more context: 

1.  Alias paths ie. benefit-finder/death for each LE
2. We need content for the landing page, currently there's brief placeholder text. 
3. Content for the block in view page: 

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/502b248b-d63a-419f-9d60-ce2e602cc337)

**Comment by scottqueen-bixal** [comment]
Bringing over to Sprint 20

**Comment by EnriqueOrt** [comment]
@diegocob - could you review the clarification above and provide the information needed by end-of-week (12/01) - The  tech team needs this information asap. - Thank you!

**Comment by diegocob** [comment]
The items on this ticket are almost complete. Added them to the content data bank [(CDB)](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit#gid=231320183). Pls check and lmk if sth is missing @gchi25 @scottqueen-bixal 

1. Alias path - Life event tab (TBC by @erniedeeb once he checks with Maria for ES urls)
2. Landing page added on the CDB Landing page tab and on [this Gdoc](https://docs.google.com/document/d/1tbpqNrMscDdIQXGIw5ek7TdAVYAz-uRfXvhgoCuRyMA/edit#heading=h.rk4j4vvkexpb)
3. Benefit cards/blocks on CDB on Cards tab

**Comment by diegocob** [comment]
Ernie, confirmed the URL paths in ES. Added them to the [CDB](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit?usp=sharing), the [Content Integration Doc](https://docs.google.com/document/d/1B19BMRftZq3kd-J93XjkY94PMXZE2oKQREOJiYEsoCk/edit?usp=sharing) and the G-doc content for each LE.

**Comment by diegocob** [comment]
This ticket should be completed. Lmk if anything is missing.
