### ISSUE TITLE
[Run Cypress e2e Prod Links Tests] failed during [workflow_dispatch]

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/px-benefit-finder#1396]
## Failure Report:

> [!IMPORTANT]
> Details on failed run: https://github.com/GSA/px-benefit-finder/actions/runs/9390025142

- Workflow Path: `GSA/px-benefit-finder/.github/workflows/test-cypress-prod-e2e.yml@refs/heads/dev`

**Comment by scottqueen-bixal** [comment]
test
