### ISSUE TITLE
Data Layer Values Persist in Google Tag Manager 

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1404]
### What's expected

This is something new for me, so I didn't have expectations. 

### What happened

When the bf_count event fires, it pushes a count of the eligible, not eligible, and more info needed events. Then when you click back, all fo the subsequent events that fire retain the same values. When you resubmit with different info, the data layer values update to the correct values. I believe this is just how Google Tag Manager works. Whenever a datalayer value is pushed, it associates all of the previously pushed values to each subsequent event. This could potentially lead to tracking issues. But if we use the correct events to track these variables, it shouldn't be an issue.

### How to replicate

Test with GTM preview on https://bf-cms-dev.bxdev.net/benefit-finder/death. Submit the form and see results, then click back and change the answers in order to get a different number of results. Then submit again. You will see that the data layer values from the first submission persist when you click on any of the events between the first and second submissions.

**Comment by scottqueen-bixal** [comment]
I am unable to replicate this issue with my local tooling (adswerve https://chromewebstore.google.com/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom)

1. it is possible to make a change in the form and get the same results
2. we have an assumption that GTM will retain the value in the dataLayer Array once it exists until it has been updated

May require more triage, but will revisit if it causes more challenges for data team collection and tracking
