### ISSUE TITLE
Create public access page for all benefits testing

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1405]
### Description

Content and User testing team would like to have a site to test life event "All benefits" for more people, such as people from usertesting.com.

The current Benefit Finder DEV site is mainly for development team with its database updated anytime.
CMS App: https://bf-cms-dev.bxdev.net/
Static Site: https://bf-static-dev.bxdev.net/

### Acceptance Criteria
An environment for life event "all benefits" testing

**Comment by gchi25** [comment]
We have 2 options.
The option 1 is preferred.

1. Publish on USAGov prod and ignore from indexing. Then remove when done.
Only people with the links can access and do the testing. 
This is preferred since they are sharing the link to anonymous folks on usertesting.com.

2.  The development team coordinate publish on Benefit Finder main dev env.

**Comment by scottqueen-bixal** [comment]
updated the title on this, `environment` was a bit confusing for what the AC is

**Comment by gchi25** [comment]
Set up @Ndoyle118 account in MAIN.

**Comment by gchi25** [comment]
Testing is completed.
