### ISSUE TITLE
Accordion not opening in DOLO benefits

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1410]
### What's expected

All accordions should open when clicked
benefit listings should not include duplicate content

### What happened

duplicate `Survivors benefits for parents` on results causing conflict with id collision on uswds script

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/0d541647-e448-4e84-939f-84f2e5348a25)

### How to replicate

navigate to https://bf-cms-dev.bxdev.net/benefit-finder/death
find both `Survivors benefits for parents`

**Comment by gchi25** [comment]
https://bf-cms-dev.bxdev.net/admin/content?combine=Survivors+benefits+for+parents&type=bears_benefit&status=All&langcode=All

![image](https://github.com/GSA/px-benefit-finder/assets/88853916/a8e757f7-a48c-4cd8-aff5-b7edbc0ea8e4)

**Comment by diegocob** [comment]
This was edited in dev and prod. 

Is this something to avoid in the future? Some benefits may have the same name but have different eligibility criteria, life events and description.

**Comment by gchi25** [comment]
Updated 1 benefit to "Survivors benefits for parents caring for a child".
Tested. Worked as expected. All accordions open when clicked.



![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/319efca8-6d67-43a1-a718-1f6516cb8d7b)



![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/03e39e7b-10ed-4901-857c-3df2fcf94e26)
