### ISSUE TITLE
Add search title field in life event form

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1427]
### Description

The new benefits search [landing page](https://www.usa.gov/benefit-finder) is supposed to show the life events like the block below. 
This requires a new field for the title that links to the page.
Add "Search title" field in life event.
Content editor cannot edit life event content.
Will add search title field in life event form, and sync with search title field of life event content.

<img width="600" src="https://github.com/GSA/px-benefit-finder/assets/88853916/706e13ae-d3ca-4a02-a9ae-becb6d1a85e8">

### Acceptance Criteria
- [ ] Search title field added in life event form content type
- [ ] Search title field of life event and life event form sync

**Comment by fongcindy** [comment]
JSON values for BF to be updated to match card titles in benefits.gov (screenshot above).

**Comment by diegocob** [comment]
Added the Search titles in EN in draft mode. May have some changes and need to confirm the ES content before adding it.

**Comment by diegocob** [comment]
This is the content in Spanish:
![image](https://github.com/user-attachments/assets/50ad9931-a318-4330-958b-a8394b05736a)

**Comment by diegocob** [comment]
@gchi25 I am reopening this ticket to have the content in ES and EN for the Search title:
#### **English**
- Living with a disability or illness
- Approaching retirement
- Dealing with the death of a loved one
- Facing financial shock

#### **Spanish**
- Vivir con una discapacidad o enfermedad
- Prepararse para la jubilación
- Afrontar la muerte de un ser querido
- Enfrentar dificultades económicas

We still need to finalize the all-benefits content which may change.

**Comment by scottqueen-bixal** [comment]
closing since we have content ticket tracking [Add search title content #1673](https://github.com/GSA/px-benefit-finder/issues/1673)
