### ISSUE TITLE
Data Analytics Post-Mortem Analysis

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1443]
### Description

To better capture the issue of the missing data, Ernie has requested a post-mortem to be shared with stakeholders.

This analysis/report should capture dates, what event/bug or change(s) that triggered the issue/failure, how was event detected, resolution actions taken, and description of the impact of the change. 

Please also capture examples of mistakes either from our end or GSA side. Communications improvement recommendation/solution to be proposed i.e. slack comms to tech team instead of only the data team. 

### User Story

As a USAGov stakeholder, I want a description of why there were inaccuracies in the data collection and what steps were taken to prevent future occurrences.

### Acceptance Criteria

- [ ] Communication of post-mortem to be sent to USAGov stakeholders. 

Port-Mortem Report [Template](https://docs.google.com/document/d/1fIh5c6sdOqVEITW-zQRhKMAvXJgbU6N0/edit) to use.

Related:#1439 

@erniedeeb & @EnriqueOrt for viz

**Comment by fongcindy** [comment]
@nickpistone client is expecting to see this 6/25

**Comment by nickpistone** [comment]
post-mortem summary here: https://docs.google.com/document/d/1YK0AYh4sOTdqtr15UWHnUiN428eyh3BC/edit?usp=sharing&ouid=101748146526059821165&rtpof=true&sd=true

**Comment by fongcindy** [comment]
Reopening ticket because Definition of Done is to send out the report and communication to stakeholders.

**Comment by fongcindy** [comment]
Most updated [Post Mortem](https://docs.google.com/document/d/1d5KvQjaLQr2jsOATAf0lBKh8MaMQOqy1/edit)
Ernie and Scott have reviewed and provided feedback. Cindy and Enrique to revise based on comments, team to review 7/8. 

Goal to send out comms week of 7/8.
