### ISSUE TITLE
DESIGN | Update Relative Events CTA Cards

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1448]
### Description

**For default:** 
![Image](https://github.com/user-attachments/assets/619e518c-485e-4e8b-978e-5adbebbf63be)
![Image](https://github.com/user-attachments/assets/f01e0be1-4f08-4332-bd60-359b32c97305)

**For Hover:** 
![Image](https://github.com/user-attachments/assets/cdcdc175-500e-405e-97ac-9a4c5f077e90)

Figma file [link](https://www.figma.com/design/xij2PUZTouE6cco8f1F2Bn/USAgov-ReDesign-Benefit-Finder?node-id=328-552&t=t4CXZDxaxinC0HjE-0):

**Comment by fongcindy** [comment]
@scottqueen-bixal The description and screenshots have been updated. 

@ErnestoFernandezAlvarez & @EnriqueOrt-GSA for viz
