### ISSUE TITLE
a11y | Fonts are not scaling on magnification

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1452]
### What's expected

Font sizes should adjust proportionately to relative scale

This could impact scaling issues when users zoom/magnify the screen

reference: https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html

### What happened

Beta release has fixed font sizes using an [absolute length unit](https://www.w3.org/TR/css-values-3/#absolute-lengths), px

Attachments
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/7c2ce40d-a046-416a-8ff2-1231e5e8fa1a)

### How to replicate

Chrome: Open Settings or Preferences and change the font size to Very large or Very small.

Example at "Very Large"
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/9cbf9623-9735-4e75-bcf9-ba5dd59d6151)

**Comment by angelina-smith** [comment]
Reviewed this on https://bf-cms-dev.bxdev.net/benefit-finder/death# environment and it looks good to go!
