### ISSUE TITLE
Run Test between two usa.gov URLs involving a 301 redirect

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1454]
### Description

The two I identified with Nick are:
 
https://benefits-tool.usa.gov/death-of-a-loved-one
currently redirecting to https://www.usa.gov/benefit-finder/death
 
We want to temporarily update the redirect to include a UTM code to see how it performs in GA4. This will let us know if the format we decided will work with the transition at the end of AUG.
 
https://benefits-tool.usa.gov/death-of-a-loved-one

change redirection to

https://www.usa.gov/benefit-finder/death?utm_source=USA_usa-gov&utm_medium=redirect&utm_campaign=redirect_benefits-tool&utm_content=en_death-of-a-loved-one
 

usa gov has lot's of redirects and some docs for many of the cases
https://github.com/usagov/usagov-2021/blob/cede7e9a89c089b2685a357671e74f482ba987a8/docs/redirects.md?plain=1

here is our current redirect snippet
https://github.com/usagov/usagov-2021/blob/cede7e9a89c089b2685a357671e74f482ba987a8/.docker/src-waf/etc/nginx/snippets/domain-rewrites-benefits-tool.conf

Amy's (USAGov) tech lead has asked that we put in a Jira ticket for webops to handle the getting-it-done part. 

@gchi25 from Benefit Finder team will work with Amy to support Benefits transition data team to completion of test.

note:

> Thanks for looking into that. If UTM parameters fire directly from the redirect link that's what we want to see. If params drop after that should be fine. 

### User Story

As a data analyst on benefits.gov transition, I'd like to test a temporary redirect to include a UTM code to see how it performs in GA4. 

### Acceptance Criteria

- [ ] 301 redirect is established in an environment where data UTM parameters fire directly from the redirect link

**Comment by gchi25** [comment]
We are also making a slight update to the UTM code compared to the one previously shared in this thread. 
?utm_source=USA_usa-gov_test&utm_medium=test_redirect&utm_campaign=redirect_benefits-tool_test

**Comment by gchi25** [comment]
[1] We want this canonical not changed.
`<link rel="canonical" href="https://www.usa.gov/benefit-finder/death">`

[2] How to revert back quickly if found UTM incorrect once deployed into prod?
We also want to know if UTM code not updated correctly in prod, how we can fix it quickly?

[3] 24 hours
We only this UTM code up in prod for around 24 hours.

**Comment by gchi25** [comment]
https://github.com/usagov/usagov-2021/pull/1649
Merged.
It will be in prod on June 28 Tuesday in prod deployment.

**Comment by gchi25** [comment]
The USAGov prod deployment is completed.
Tested. The updated redirect works well as expected.

https://benefits-tool.usa.gov/death-of-a-loved-one
redirects to 
https://www.usa.gov/benefit-finder/death?utm_source=USA_usa-gov_test&utm_medium=test_redirect&utm_campaign=redirect_benefits-tool_test

**Comment by gchi25** [comment]
https://github.com/usagov/usagov-2021/pull/1663
Merged PR to revert back redirect for benefits tool.
It will be in prod on July 2 Tuesday in prod deployment.

**Comment by gchi25** [comment]
The revert direct was deployed into prod in USAGov prod development.
https://benefits-tool.usa.gov/death-of-a-loved-one redirects to https://www.usa.gov/benefit-finder/death
