### ISSUE TITLE
Contribute cypress test to cover Benefit Finder on USAGov

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1458]
### Description

provide USAGov code base with a simple cypress test that can be run by their developers locally, to check if any issues arrise with new code contributed by USAGov Developers

some considerations

- better alignment of USAGov element structure to inherit styles more cleanly
- create a megaview of all components to be accessible on usagov project in dev environments
- include functional test to focus on click-ability
- include visual regression 
- create  axe scanning on the application 

nuclear option
- commit fully compiled usagov theme + bf finder styles during each realease and scope under the benefit finder ID. this would prevent any new breaks from impacting benefit finder while usagov code is out dated

**Comment by scottqueen-bixal** [comment]
exploring an approach with DevOps Github action here https://github.com/orgs/GSA/projects/48/views/16?filterQuery=sprint%3A%40current+assignee%3AXavierMetichecchia&pane=issue&itemId=68864778

**Comment by scottqueen-bixal** [comment]
new tracking in JIRA usagov https://github.com/usagov/usagov-2021/tree/USAGOV-1901-benefits-finder-regression-test

**Comment by XavierMetichecchia** [comment]
This is done just waiting for Amy to schedule an implementation meeting she requested.

**Comment by scottqueen-bixal** [comment]
closing as this is integrated into their repository, new work will be ticketed.
