### ISSUE TITLE
Benefits not appearing in results page for eligible users

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#147]
We tested a few scenarios and we found that benefits we were expecting like Covid, public safety officer in line of duty, etc. produced inaccurate results one time, and no results a second time. 

**Example Scenario:**
ABOUT THE APPLICANT:
Date of Death:
5/5/1960
Spouse
Widowed
US Citizen
Caring for a child under the age of 16
Paid for the funeral

ABOUT THE DECEASED:
Date of Death:
3/3/2022
Date of Funeral:
3/5/2022

Person died in the US.
Paid SS Taxes.
Was a public safety officer in the line of duty (NO)
Worked in the Coal mines (NO)
Was member of Native American Tribe (NO)
Died of Covid (YES)
Serve in the military (NO)

This scenario produced inaccurate results,  It only shows one the benefit for Survivor Mothers and Fathers, triggered  by answering Yes to “Caring for a child under the age of 16”

Results for this scenario: 
![Image](https://github.com/GSA/px-bears-drupal/assets/128498116/ba12ecd9-a534-45e7-b89f-5578643e34a9)

**Comment by diegocob** [comment]
Working correctly. Thanks for fixing it.
