### ISSUE TITLE
NEW FEATURE | Return to first step of form, without clearing the form

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1473]
### Description

Right now we can, 

- navigate to the results view with a populated query
- reset the form with the click of a button

but, we would like to have the ability to,

- return to first step of form, without clearing the form, with the click of a button

### User Story

As a user who has arrived at the eligible results view, with zero benefits - I would like to click a button that will take me back to the first step of the form with all of my form values

### Acceptance Criteria

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/fcc2a40c-3826-405f-9d33-bff7980f6458)

- [ ] clicking the "Go back to form" button takes the user back to the first step of the form without loosing form values

**Comment by EnriqueOrt** [comment]
Organizing final decision and gathering buy-in from team.

**Comment by fongcindy** [comment]
Team has discussed and agreed to proceed with this ticket and feature

**Comment by scottqueen-bixal** [comment]
needing translation for "Go back to form"

**Comment by EnriqueOrt-GSA** [comment]
This is what I would use - **"Regresar al formulario"** 
22 vs 15 characters including spaces
@diegocob for review
@scottqueen-bixal for vis

**Comment by diegocob** [comment]
Thought I answered this yesterday but seeing my message didn't go through.
We've hesitated to use the word "form" bc it sounds technical (esp in ES) and may be confused as an application form. 
Suggest: 
EN: Go back to the start
ES: Volver al inicio 

If we stick with the original, we can use: "Regresar al formulario"

**Comment by diegocob** [comment]
Manual QA on Main is working well.
