### ISSUE TITLE
Provide warning message when deleting benefit in use

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1479]
### Description

Provide warning message when deleting benefit in use.

### Acceptance Criteria

Provide warning message when deleting benefit in use

**Comment by scottqueen-bixal** [comment]
Is this similar work to https://github.com/orgs/GSA/projects/48/views/17?pane=issue&itemId=69402420 ?

**Comment by gchi25** [comment]
It is different.
The life event form can not be deleted if still used in relevant benefit of other life event form.
This ticket is to not delete a benefit if still used in life event form.
