### ISSUE TITLE
Create BF report navigation

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1488]
### Description

Create benefit finder report menu for users to navigate benefit report, agency, criteria, benefit, life event form...

### User Story

As a content editor, I would like to have a User Interface, such as menu, to navigate the benefit finder reports.

### Acceptance Criteria

benefit finder report menu

**Comment by scottqueen-bixal** [comment]
HOLD as do not work on, will discuss with Cindy
