### ISSUE TITLE
Implement Trufflehog

### ISSUE THREAD

**Issue by XavierMetichecchia** [GSA/px-benefit-finder#1500]
### Description

Trufflehog will scan for secrets in commits and and alert based on its findings.

### User Story

We want better secrets scanning in commits to make sure it stays out of our public repo.

### Acceptance Criteria

Secrets are alerted on ASAP as the scan detects them, It would make sense to do this on a PR as well.

**Comment by fongcindy** [comment]
At a quick glance I thought "Trufflehog" was a new software tool or program we are adding to our tech stack hahah 😂
