### ISSUE TITLE
Create data layer event(s) to track error messages in analytics

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1501]
Create a data layer event to track error messages. There could be two associated values. One shows the text of the error message. This would change based on the language of the page. Another would be an error ID that would be the same across languages and life experiences with values such as "birth-date-month-error" and "marital-status-error". 

As an analyst I want to be able to show the team how often error messages are being triggered and analyze patterns to see if certain user segments are more likely to encounter errors based on browser, device, language, etc.

Acceptance Criteria:
-data layer event fires whenever an error message appears
-data layer value shows error ID 
-data layer event fires whenever a user successfully moves forward

**Comment by scottqueen-bixal** [comment]
We need to define data event structure and terms

**Comment by scottqueen-bixal** [comment]
tracked from convo on teams:

we need to massage the AC a bit so I know exactly what we want to implement there
 
currently we have 

```
Acceptance Criteria:
-data layer event fires whenever an error message appears
-data layer value shows error ID
-data layer value shows error message text
```
 
 
`-data layer event fires whenever an error message appears`

Do we need a closing event after all have been resolved, or can you presume that based on the users next event, which would be an incremented virtual page event?
 
 ```
-data layer value shows error ID
-data layer value shows error message text
There we need to build this where it can handle multiple errors
```
 

For example, if you don't fill out required fields on the first step of death you get 5 errors
 
If we bind it to a `bf_page_change` event it may look something like this,
 
```
 {
    event: 'bf_page_change',
    bfData: {
      pageView: 'bf-error-alert',
      viewTitle: STRING
      errors: [
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
       ],
       errorCount: { number: NUMBER, string: STRING }
    },
  },
```

 If we bind it to a `bf_error` event it may look something like this,
 
```
 {
    event: 'bf_form_entry_error',
    bfData: {
      errors: [
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
         { errorId: STRING, errorMessage: STRING },
       ],
       errorCount: { number: NUMBER, string: STRING }
    },
  },
```

@nickpistone to have discussion with USAGov Data Lead and discuss the pros and cons of each and determine a path forward.

**Comment by scottqueen-bixal** [comment]
final structure after discussion looks like this,

```
{
    event: 'bf_form_entry_error',
    bfData: {
      errors: [
         "STRING","STRING","STRING","STRING","STRING"
       ],
       errorCount: { number: NUMBER, string: "STRING" }
    },
  },
   {
    event: 'bf_form_page_success',
    bfData: {
        formSuccess: true,
    },
  },
   {
    event: 'bf_page_change',
    ...
    }
```
