### ISSUE TITLE
Remove `data-analytic*` attributes from DOM

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1507]
### Description

We have moved to consistently using the `dataLayer` for pushing custom events, and are including the values that were previously in the `data-attributes*` in those objects.

It would be better to remove these attributes so they are no longer in the DOM

### User Story

As a developer I would like to centralize data structure and values into dataLayer custom events rather than DOM attributes

As a data analyst I expect to see tracking values in the dataLayer rather than in the DOM attributes

### Acceptance Criteria

- [ ] data attributes for analytics are removed from the DOM
- [ ] includes, `data-analytics` and `data-analytics-content` only

**Comment by nickpistone** [comment]
The tags using the data-analytics* attributes have been removed from GTM, so there is nothing relying on them. To clarify, we are talking about two attributes (data-analytics and data-analytics-content), right @scottqueen-bixal ? Are there any other attributes that fall into that category that I'm missing?

**Comment by scottqueen-bixal** [comment]
Thanks for the update @nickpistone. This is exactly the confirmation that we need to remove those attributes from our DOM rendering.

As far as I am aware you are correct, `data-analytics` and `data-analytics-content` will be the two attributes that will be removed with the completion of this work.

I've updated the AC to clarify. 👍

**Comment by nickpistone** [comment]
Verified that this is no longer showing up in Dev
