### ISSUE TITLE
DATA | `dataLayer` Improvements

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1509]
### Domain

data

### Related Issue(s)

Due: 7/5

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

[Create a unique data layer value for the modal ](https://github.com/GSA/px-benefit-finder/issues/1478)	https://github.com/GSA/px-benefit-finder/issues/1478
[bf_page_change fires multiple times on inital page load](https://github.com/GSA/px-benefit-finder/issues/1468)	https://github.com/GSA/px-benefit-finder/issues/1468
[Update pageView data layer variable to differentiate between form pages](https://github.com/GSA/px-benefit-finder/issues/1477)	https://github.com/GSA/px-benefit-finder/issues/1477
[Create data layer event to track benefit link click](https://github.com/GSA/px-benefit-finder/issues/1467)	https://github.com/GSA/px-benefit-finder/issues/1467
[Add data layer value to track benefit accordion open](https://github.com/GSA/px-benefit-finder/issues/1466)	https://github.com/GSA/px-benefit-finder/issues/1466

### Description

Testing env: https://bf-cms-main.bxdev.net/benefit-finder/death

Please take some time to QA the above items ensuring that the event behavior is working as expected and confirm that you can use it with integrating tracking in GTM.

cc: @fongcindy, @EnriqueOrt

**Comment by nickpistone** [comment]
I'm getting a 404 error when I try this link: https://bf-cms-main.bxdev.net/benefit-finder/death.

**Comment by nickpistone** [comment]
I was able to test using https://bf-cms-dev.bxdev.net/benefit-finder/death instead of bf-cms-main. Testing in this environment, I found the following:

Confirmed:

- Modal has unique data layer value #1478 
- page_change only fires once on load (fix for #1468)
- pageView data layer variable can be used to differentiate between all form pages; BUT is not showing any value that differentiates between eligible and ineligible results #1477 
- Benefit link event fires as expected
- Benefit accordion event fires as expected, but request name change from benefit_click to benefit_accordion_open

**Comment by fongcindy** [comment]
Scott will sync with Nick to figure out the issue he's seeing on his end.

**Comment by scottqueen-bixal** [comment]
confirmed the 404 on main https://bf-cms-main.bxdev.net/benefit-finder/death, I'll reach out to DevOps to see what's going on with the `main` env.

**Comment by scottqueen-bixal** [comment]
> I was able to test using https://bf-cms-dev.bxdev.net/benefit-finder/death instead of bf-cms-main. Testing in this environment, I found the following:
> 
> Confirmed:
> 
> * Modal has unique data layer value [Create a unique data layer value for the modal  #1478](https://github.com/GSA/px-benefit-finder/issues/1478)
> * page_change only fires once on load (fix for [bf_page_change fires multiple times on inital page load #1468](https://github.com/GSA/px-benefit-finder/issues/1468))
> * pageView data layer variable can be used to differentiate between all form pages; BUT is not showing any value that differentiates between eligible and ineligible results [Update pageView data layer variable to differentiate between form pages #1477](https://github.com/GSA/px-benefit-finder/issues/1477)
> * Benefit link event fires as expected
> * Benefit accordion event fires as expected, but request name change from benefit_click to benefit_accordion_open

Looks like all items are confirmed, and notes of additional work  were requested after sprint34, and are being tracked in the current sprint 35 under the associated items


> * pageView data layer variable can be used to differentiate between all form pages; BUT is not showing any value that differentiates between eligible and ineligible results [Update pageView data layer variable to differentiate between form pages #1477]

https://github.com/GSA/px-benefit-finder/issues/1514 

> * Benefit accordion event fires as expected, but request name change from benefit_click to benefit_accordion_open

https://github.com/GSA/px-benefit-finder/issues/1516

because these two requests were done after the work in sprint34, you should expect that they will be part of the upcoming QA sprint.

@nickpistone if you agree, with the above - please confirm and mark this ticket as done.


CC: @fongcindy
