### ISSUE TITLE
BF add search title field in event

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1510]
### Description

Context:
Benefits.gov project has changed the new benefits search landing page, it shows the life events below. This requires a new field for the title that links to the page.
Add "Search title" field in life event.
![image](https://github.com/GSA/px-benefit-finder/assets/128498116/f0c0d49d-6ee4-4ee7-befd-fd841602f4d5)

We will need to update out JSON values for BF to match card titles in benefits.gov (image above). 

- Our BF LE Cards in results more benefit page, title to match (remove "benefit finder: ...")

### Acceptance Criteria

- [ ] Our BF LE Cards in the results more benefit page, title will need to change from "Benefit Finder: Dealing with the death of a loved one" to "Dealing with the death of a loved one"

Related:#1427

**Comment by diegocob** [comment]
From the content side, I'll wait until the new field is ready in the CMS to update the titles. 

I suggest taking out the verb and keeping the title as a noun:
- Death of a loved one
- Disability or illness
- Retirement

**Comment by diegocob** [comment]
This was completed. Closing it.
