### ISSUE TITLE
[Production Links Test] failed

### ISSUE THREAD

**Issue by XavierMetichecchia** [GSA/px-benefit-finder#1517]
## Failure Report:

> [!IMPORTANT]
> Details on failed run: https://github.com/GSA/px-benefit-finder/actions/runs/9736124805

**Comment by scottqueen-bixal** [comment]
now that this flaky failure is confirmed, we are tracking a potential fix here -> https://github.com/GSA/px-benefit-finder/issues/1392#issuecomment-2200162388
