### ISSUE TITLE
Screen reader audit of live Disability

### ISSUE THREAD

**Issue by angelina-smith** [GSA/px-benefit-finder#1522]
Conduct screen reader audit of live Disability page and document unique issues specific to Disability.

- [x] JAWS
- [x] NVDA

**Comment by fongcindy** [comment]
IT is helping with getting JAWS for Angelina and team. Hopefully end of week this will be completed.

**Comment by angelina-smith** [comment]
Heard oddities with NVDA reading any additional/helper text across DOLO and Disability. Did not experience this issue with JAWS.

Plan to bring this up to Dave and Julia for verification on Monday's accessibility sync (7/15/2024)
