### ISSUE TITLE
Review and Edit Multilingual Blog Entry

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1530]
### Description

Going through the editorial process of the [blog entry](https://docs.google.com/document/d/1pCJr8_YSXnf48UfLEQQ45iBAwmoegu6IHeUlB3kmheA/edit).

### Acceptance Criteria

UX Team @Ndoyle118 > @erniedeeb  > USAGov Content Team

**Comment by ernie** [comment]
Hi! Still the wrong Ernie. 😄

**Comment by diegocob** [comment]
Thanks for letting me know and sorry about that :/

**Comment by diegocob** [comment]
Completed reviewing. Nick Doyle reviewed it and now Ernie and Claire will review it. Will create another ticket for that.
