### ISSUE TITLE
Section heading as h1 not scaled appropriately

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1535]
### What's expected

h1 section headings should sit at `2rem`

### What happened

h1 section headings should sit at `2rem` but are being overridden at `1.375rem`

### How to replicate

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/26aa2b0a-2124-4630-828e-0a98ef9c212b)
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/8e2afef6-394f-42f9-8249-a682c0bb009d)

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal @angelina-smith @scottqueen-bixal 

Hello guys please see screenshot attached with font details:

"Answer these questions" Heading use **Public Sans Extra Bold 36pt.**
"About the applicant" Subheading use **Public Sans Bold 32pt**
<img width="1902" alt="Screenshot 2024-07-16 at 10 38 28 AM" src="https://github.com/user-attachments/assets/4d7f04de-883d-40ac-a189-39cc0588d194">
