### ISSUE TITLE
Remove viewState data layer variable

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1536]
### Description

Since we are capturing eligible vs ineligible in the pageView variable, we won't need this anymore. And we will be able to capture the zero benefits with the eligible benefit variable.

### Acceptance Criteria

viewState data layer variable/attribute is removed

**Comment by scottqueen-bixal** [comment]
makes sense, we will remove this key value pair https://github.com/GSA/px-benefit-finder/blob/dev/benefit-finder/src/shared/utils/dataLayerUtils/dataLayerStructure.js#L32C1-L36C9

**Comment by nickpistone** [comment]
Confirmed
