### ISSUE TITLE
Change modal_open event to a page_change event

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1537]
### Description

After discussing with David, it makes more sense from a reporting standpoint to consider this another page change rather than a different event. It needs to have unique values for the associated data layer variables.
pageView=bf-form-completion-modal
viewTitle=See Results or Review Selections 
Question: is it possible for the viewTitle to populate with a language-specific value since that is what the other viewTitle values do? It could just be the text on the two buttons. But it would be good for it to be the title of that unique page, even if it's technically part of the second page of the form. If not, the pageView variable is what's most important.

### Acceptance Criteria

page_change event fires instead of modal_open event when users reach the modal that says "see results or review selections"
page_change event includes a unique pageView variable value (bf-form-completion-modal) and viewTitle value ([button text] or other page-specific identifying text])

**Comment by scottqueen-bixal** [comment]
To confirm you want this data structure for the modal view....
```  
    event: 'bf_page_change',
    bfData: {
      pageView: 'bf-form-completion-modal,
      viewTitle: {current form step heading},
    },
```

**Comment by scottqueen-bixal** [comment]
```   
event: 'bf_page_change',
    bfData: {
      pageView: 'bf-form-completion-modal',
      viewTitle: `${current form step heading} modal`,
    },
```

**Comment by nickpistone** [comment]
Confirmed
