### ISSUE TITLE
QA | Design v0.5.0.beta.1

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1540]
### Domain

design

### Related Issue(s)

[a11y | Fonts are not scaling on magnification](https://github.com/GSA/px-benefit-finder/issues/1452) #1452 
[NEW FEATURE | Zero Benefits View](https://github.com/GSA/px-benefit-finder/issues/1367) #1367 

Due July 17

### Description

Design final QA for fonts and zero benefits view

Testing environment: http://bf-cms-main.bxdev.net/

**Comment by scottqueen-bixal** [comment]
already aware of this as an issue [Section heading as h1 not scaled appropriately](https://github.com/GSA/px-benefit-finder/issues/1535)	https://github.com/GSA/px-benefit-finder/issues/1535

**Comment by ErnestoFernandezAlvarez** [comment]
@EnriqueOrt @scottqueen-bixal 

Hello guys please see screenshot attached with font details:

"Answer these questions" Heading use Public Sans Extra Bold 36pt.
"About the applicant" Subheading use Public Sans Bold 32pt

I also added this comment to ticket https://github.com/GSA/px-benefit-finder/issues/1540



![Image](https://github.com/user-attachments/assets/5a9f44ad-fb0d-400d-82fc-ff2f7127c033)

Please let me know if you need further info/resources.
Thank you

**Comment by scottqueen-bixal** [comment]
Thanks at @ErnestoFernandezAlvarez , this issue should be covered by the bug ticket we are tracking here [Section heading as h1 not scaled appropriately](https://github.com/GSA/px-benefit-finder/issues/1535)	https://github.com/GSA/px-benefit-finder/issues/1535
