### ISSUE TITLE
QA Testing | e2e test for zero benefits view

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1544]
### Description

We now have a view that renders when no benefits are eligible, we would like to put some automated testing to ensure this does not regress.

### Acceptance Criteria

- [x] expect completing required fields only in `death` results in the zero benefits state, on the eligible
- [x] expect no accordions are on this view
- [x] expect see all benefits button
- [ ] ~~expect clicking see all benefits button takes you to the ineligible view, with zero benefits content~~

Testing environment: http://bf-cms-main.bxdev.net/

**Comment by scottqueen-bixal** [comment]
- [ ] expect clicking see all benefits button takes you to the ineligible view, with zero benefits content

This is a new feature that is planned for Sprint 37 and not part of this release

https://github.com/orgs/GSA/projects/48/views/10?pane=issue&itemId=68570725

**Comment by nehemiah-abuga** [comment]
I have verified this change


![Image](https://github.com/user-attachments/assets/16e9ec1a-bca6-4554-98bb-bdb4a88530c5)



![Image](https://github.com/user-attachments/assets/9e583b58-30b5-4b24-9ca1-17b2afff56c0)

**Comment by nehemiah-abuga** [comment]
Ready for review - https://github.com/GSA/px-benefit-finder/pull/1578
