### ISSUE TITLE
Analyze data from all-benefits page unmoderated testing

### ISSUE THREAD

**Issue by Ndoyle118** [GSA/px-benefit-finder#1552]
### Description

I need to analyze the data collected from 10 unmoderated testing sessions of the all-benefits page 

This includes:
- [x] Review all recordings and record notes on the Mural Board
- [x] Affinity mapping of Mural notes
- [x] Synthesis/reporting findings

**Comment by fongcindy** [comment]
Expected to be complete by ~7/12

**Comment by Ndoyle118** [comment]
Final report: https://docs.google.com/document/d/12QN6bqz3_R3cJPxhNc3yvdw5lux8QA2FUDGu1F-bUE8/edit#heading=h.l34o36ah3122
