### ISSUE TITLE
QA Data | dataLayer check

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1553]
### Domain

data

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

Due by July 17

[Consolidate bf_count data layer event with bf_page_change ](https://github.com/GSA/px-benefit-finder/issues/1538)	https://github.com/GSA/px-benefit-finder/issues/1538
[Change modal_open event to a page_change event](https://github.com/GSA/px-benefit-finder/issues/1537)	https://github.com/GSA/px-benefit-finder/issues/1537
[Remove viewState data layer variable](https://github.com/GSA/px-benefit-finder/issues/1536)	https://github.com/GSA/px-benefit-finder/issues/1536
[Update accordion open data layer event names](https://github.com/GSA/px-benefit-finder/issues/1516)	https://github.com/GSA/px-benefit-finder/issues/1516
[Create data layer push event for open all/close all accordion button on results pages](https://github.com/GSA/px-benefit-finder/issues/1515)	https://github.com/GSA/px-benefit-finder/issues/1515
[Update pageView Data Layer variable](https://github.com/GSA/px-benefit-finder/issues/1514)	https://github.com/GSA/px-benefit-finder/issues/1514
[Create data layer event to track benefit link click](https://github.com/GSA/px-benefit-finder/issues/1467)	https://github.com/GSA/px-benefit-finder/issues/1467
[Add data layer value to track benefit accordion open](https://github.com/GSA/px-benefit-finder/issues/1466)	https://github.com/GSA/px-benefit-finder/issues/1466

### Description

Testing Environment: https://bf-cms-main.bxdev.net/

**Comment by nickpistone** [comment]
Can confirm all of these except for #1515 are working as expected. The data layer event for #1515 is working, but there is a bug where the accordions stay open when the user navigates from the eligible benefits view to the ineligible benefits view. #1554 is the bug ticket.
