### ISSUE TITLE
When user clicks open all accordions and navigates to another page, the accordions are already open on the new page

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1554]
### What's expected

When user navigates from eligible benefits page to "Benefits you didn't qualify for," the accordions will be closed until they are opened on that page.

### What happened

Opened all accordions on eligible results page and then navigated to ineligible results page and accordions were already open.

### How to replicate

Navigate to results, open all accordions, then click to "Benefits you didn't qualify for" and the accordions will already be open when the page loads.

**Comment by scottqueen-bixal** [comment]
I found a few more areas where accordions should be defaulting to closed but are not,

When a user is on zero-benefits + not-eligible-view

https://github.com/user-attachments/assets/039273b1-ab0e-4600-9c31-169e997613bb

When a user individually opens accordions, toggles the view, then returns

https://github.com/user-attachments/assets/8fd75005-8859-41ad-862f-2560f858e039

**Comment by scottqueen-bixal** [comment]
confirming this was only happening on local, not on the related development branch


https://github.com/user-attachments/assets/ff7c3f09-e9ee-42d3-b8ba-2fb19812aa88

**Comment by scottqueen-bixal** [comment]
Fix for this is on https://bf-cms-dev.bxdev.net/benefit-finder/death and could use a confirmation.
