### ISSUE TITLE
Determine consistent translation for inline field errors

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1555]
### Description

Due by: start of Sprint 37

Related to #1121 

While adopting GSA Error handling we noticed two items,

1. There is a consistent format for handling inline error messages, "Fill out the {label} field"

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/f0a4f39a-12c9-4f13-af9c-e3a008f2be35)

2. There is an inconsistent format for handling inline error messages in the `es` locale, see https://www.usa.gov/es/funcionarios-electos#myStreetAddress 

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/95c4b149-e4e1-4903-8af4-f87c619fd1e5)

We would like to have a consistent structure and content for all locales

**Option 1, lowest LOE**
Recommend using similar structure to what we currently use in the Benefit Finder tool

en: `Complete the {label} field`
es: `Responda el {label} campo`

**Option 2, higher LOE**

- Include default consistent structure
- Include Drupal field that allows for string content to be customized an override default UI content if provided

### User Story

As a developer I would like a consistent way of implementing inline error messaging that uses a {prefix}{label}{suffix} structure
As a user I would like to have clear directions on inline error messages
As a product owner, I expect to align well with the GSA error handling while still conforming to best practice, user experience, and technical implementation

### Acceptance Criteria

- [x] Option of decision is provided
- [x] Default content is provided for both EN/ES

**Comment by diegocob** [comment]
Option 2 seems to work better for the longer-term and make it easier to read the error labels. In case we want to make other questions required, like, `Fill out citizen status field` vs `Fill out Are you a U.S. citizen or eligible non-citizen field`.

Since the `field name` in Spanish was in English, I created a translation in the [content bank/criteria tab/column "I"](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit?gid=367875404#gid=367875404)

**In English:**
`Fill out 'criteria title' field`

**In Spanish**
`Complete el campo de 'ES criteria title'`
***Note:*** In GSA's guide they used the word "escriba" (write) which is not accessible for people who don't write, or accurate since most people type, click or tap.

**Would need to:**
- [ ] Change all criteria names in Spanish
- [ ] Suggest also changing criteria names in English to simplify the 
     -  We discussed to take out the "applicant" and "deceased" from the criteria name
          - `Applicant citizen status` --> `Citizen status`

**Comment by scottqueen-bixal** [comment]
regarding this comment since, it doesn't align with the initial option 2 recommendation

```
Would need to:

 Change all criteria names in Spanish
 Suggest also changing criteria names in English to simplify the
We discussed to take out the "applicant" and "deceased" from the criteria name
Applicant citizen status --> Citizen status
```

We do not need to _change all_ criteria names to manage customizations on error messaging.

we would likely only include a "custom error message" field, that would allow a content editor to provide a string value, in the case that the default messaging doesn't make sense

**Comment by diegocob** [comment]
We don't need to change all the fields' names and could opt to change only the ones currently required in a life event form.
However, if we make other questions required, for consistency and long-term sustainability, I suggest changing all field names, which is not a high LoE from the content side.

**Comment by scottqueen-bixal** [comment]
> We don't need to change all the fields' names and could opt to change only the ones currently required in a life event form. However, if we make other questions required, for consistency and long-term sustainability, I suggest changing all field names, which is not a high LoE from the content side.

Criteria Title field is really just for back end CMS organization, not for UI display.

We have a sync this week set up to discuss in more detail. Rather than going back and forth here - let's hold off until after that meeting. Once we are all on the same page with acceptance criteria and the options described above, we will document decision here for implementation considerations.

**Comment by fongcindy** [comment]
Diego will check with BF UX team to get confirmation on Spanish translation replacement for "escriba". Once confirmed, Diego will check with usa.gov content team for approval. 

Then Scott can go ahead and make this change.

**Comment by scottqueen-bixal** [comment]
Option 2, higher LOE is preferred

Include default consistent structure
Include Drupal field that allows for string content to be customized an override default UI content if provided

- [ ] @diegocob to confirm on our recommended variation for ES, but need confirmation from USAgov

**Comment by diegocob** [comment]
I am checking with our UX and USAGov content teams about changing the "escriba" word.

Regarding the inconsistency of articles and names for the fields, the approach I suggested sounds grammatically incorrect. 
Complete el campo [`article` ES field name]
Complete el campo de [la ciudad]
Complete el campo de[l código postal]

If we are creating a custom field for the error handling, I suggest adding the article to the error field name: 
Complete el campo `error handling name`
Complete `la dirección`
Complete 'el codigo postal`

Would this work?

**Comment by scottqueen-bixal** [comment]
> I am checking with our UX and USAGov content teams about changing the "escriba" word.
> 
> Regarding the inconsistency of articles and names for the fields, the approach I suggested sounds grammatically incorrect. Complete el campo [`article` ES field name] Complete el campo de [la ciudad] Complete el campo de[l código postal]
> 
> If we are creating a custom field for the error handling, I suggest adding the article to the error field name: Complete el campo `error handling name` Complete `la dirección` Complete 'el codigo postal`
> 
> Would this work?

We _need a default_ that will handle most cases, you can customize whatever you want in the override field.

**Comment by diegocob** [comment]
This should work then.

**Comment by diegocob** [comment]
USAGov content (Shoshana) and design (Maria) teams approved using this for the Spanish inline error message:
`Complete [error field name]`

I will work on getting the error field messages for English and Spanish on another ticket.

**Comment by diegocob** [comment]
@scottqueen-bixal here's the [inline error message doc](https://docs.google.com/spreadsheets/d/12eb890YChX7fxk5moai7l9KZOzFhdwklphHpavHx_vM/edit?usp=sharing)

You can also find the inline error message in the inline error or criteria tab of the [Content data bank](https://docs.google.com/spreadsheets/d/1oR16O1SmdJoD2As_W4pB2DzMvDLTj7cuMyj4qgpB9UY/edit?gid=367875404#gid=367875404)

It's ready for boarding.

**Comment by diegocob** [comment]
The final error messaging text would be:
**English:**
`Fill out [EN_in-line_error] field`

**Spanish**
`Complete [ES_in-line_error]`

**Comment by scottqueen-bixal** [comment]
> The final error messaging text would be: **English:** `Fill out the {EN_in-line_error} field`
> 
> **Spanish** `Complete {ES_in-line_error}`

roger that, thanks @diegocob - will work on implementation
