### ISSUE TITLE
[Production Links Test] failed

### ISSUE THREAD

**Issue by XavierMetichecchia** [GSA/px-benefit-finder#1565]
## Failure Report:

> [!IMPORTANT]
> Details on failed run: https://github.com/GSA/px-benefit-finder/actions/runs/9931860442

**Comment by diegocob** [comment]
Could you confirm if there is a link that is failing I need to look at? @XavierMetichecchia 
Only saw this one in the report: https://www.dol.gov/agencies/owcp/dcmwc/filing_guide_survivor
And it seems to be working.

**Comment by scottqueen-bixal** [comment]
closing - confirmed this link is now working as expected
