### ISSUE TITLE
Update Page Object Selectors to Use Data Attributes

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/px-benefit-finder#1567]
### Description

Modify the existing Cypress test automation suite to use data attributes (data-*) in selectors within the Page Object Model (POM). This will help isolate the tests from potential CSS and JavaScript changes.

### Acceptance Criteria

Existing Cypress test automation suite modified to use data attributes

**Comment by nehemiah-abuga** [comment]
90 percent done. 



![Image](https://github.com/user-attachments/assets/fa043706-9432-42f9-b492-ab3596a93cd9)

**Comment by nehemiah-abuga** [comment]
One of the scenario failing from the update of attributes (expandAll). Working to resolve it



![Image](https://github.com/user-attachments/assets/0efafee0-a300-4a9c-97b2-68a1966e3f37)



![Image](https://github.com/user-attachments/assets/dbaec445-d1fa-4274-8573-228b4ea69fc4)

**Comment by nehemiah-abuga** [comment]
Completed. PR is https://github.com/GSA/px-benefit-finder/pull/1756

**Comment by scottqueen-bixal** [comment]
picking this up to get updated with our dev branch....

**Comment by scottqueen-bixal** [comment]
this has been updated and brought inline with current dev branch, test passing https://github.com/GSA/px-benefit-finder/pull/1756
