### ISSUE TITLE
automate updating submodule hash

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1612]
### Description

Every once in a while we like to update the hash reference in our git submodule config

locally that change will look something like this,

```
diff --git a/usagov-2021 b/usagov-2021
index eb418375..c89e8c94 160000
--- a/usagov-2021
+++ b/usagov-2021
@@ -1 +1 @@
-Subproject commit eb418375f783b0dc9f8ab330f2ba0507242bc053
+Subproject commit c89e8c94e67f143851d6f53bf8cfdd2a9c4af6cf
```

but in the repo it will show up like this

![Image](https://github.com/user-attachments/assets/a9998704-1d16-49fa-8b9f-3851e61534b0)

when we `init` the submodule this is the has that it starts from, then we can update and pull in as needed, getting too far behind on this can potentially cause issues.

We have manually updated this in the past, but I'd be curious to see if we could work it out as part of our release task.

### User Story

as a developer, when I begin a new release cycle, I'd like to start by having the latest hash in our submodule

### Acceptance Criteria

- [ ] git workflow automatically updates submodule hash on release, main, and dev

**Comment by XavierMetichecchia** [comment]
This is all done! Heres is a resultant PR: https://github.com/GSA/px-benefit-finder/pull/1808
