### ISSUE TITLE
Redesign | Buttons Pt2

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1633]
### Description

**Button within the accordions**
- Left and right padding is 24px, top and bottom padding is 16px 
- Font: Source Sans Pro Bold 17.6px
- Font Color: 1B1B1B 
![image](https://github.com/user-attachments/assets/fe375fc5-36c3-45b4-b67d-4b990314ccd4)
- Background color default state: CCECF2
- Background color Hover state: A7D8E3 
- Outline color: 0081A1
![image](https://github.com/user-attachments/assets/adcfa40a-8cae-4aeb-96b2-69ab14d15c4a)

These buttons are at the bottom of each of the expanded/active accordions: 
![image](https://github.com/user-attachments/assets/c657fb43-49da-4de3-a0cc-00a4b97bdb8f)

**Outline button**
- Left and right of padding is 24px - top and bottom padding is 16px
- Font: Source Sans Pro Bold 17.6px
- Font color: 1B1B1B
- Background color default state: FFFFFF
- Background color Hover state: F0F0F0
- Outline color: 1B1B1B 
![image](https://github.com/user-attachments/assets/e20438e7-7323-4be6-a720-c1ea43f6e1fb)

This button is the "back" button at the bottom of the form. 

Related: #1629 & #1632
@ErnestoFernandezAlvarez  & @EnriqueOrt-GSA for viz

**Comment by ErnestoFernandezAlvarez** [comment]
<img width="333" alt="Screenshot 2024-07-30 at 4 31 00 PM" src="https://github.com/user-attachments/assets/001c5949-9959-4f7f-8acc-5e763cef55cd">

**Comment by ErnestoFernandezAlvarez** [comment]
Added a visual for the outline button
