### ISSUE TITLE
Benefit finder page level surveys

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#1638]
### User / Persona

Benefit finder user

### Reason / Justification

Provide feedback on my benefit finder experience

### Acceptance Criteria (AC)

- Page level survey appears on the benefit finder results page
- User can interact with the survey in the same way they can on USAGov
- Submissions are added to Medallia (? - need to validate)

### Other Notes

Duplicate of https://github.com/orgs/GSA/projects/48/views/2?filterQuery=survey&pane=issue&itemId=34180527

![Image](https://github.com/user-attachments/assets/a880ee4e-61ec-4244-9cdb-b04ba6256c34)

Add following code to page: `<div id="pagesurvey-qual-container"></div>`

Around or above the back-to-top link

**Comment by EnriqueOrt-GSA** [comment]
First iteration will focus on getting code up on the Benefit Finder page. 
To be started Sprint 38

**Comment by gchi25** [comment]
https://www.usa.gov/benefit-finder
<img width=600 src="https://github.com/user-attachments/assets/20c96118-1700-41ec-9964-c897f6033f9c"></img>

**Comment by gchi25** [comment]
### Solution

Add following code to page: <div id="pagesurvey-qual-container"></div>
above the back-to-top link

React hides the element by its ID pagesurvey-qual-container in no-result pages.

**Comment by erniedeeb** [comment]
@gchi25 Is it possible to add this to the benefit finder life event pages e.g. https://www.usa.gov/benefit-finder/death? 

It is more important for us to add it there, since https://www.usa.gov/benefit-finder will end up consolidating with the benefits transition category search.

**Comment by gchi25** [comment]
@erniedeeb Yes. It is possible. We can add Benefit Finder page level in all the pages along the Benefit Finder tool.

**Comment by gchi25** [comment]
https://bf-cms-dev.bxdev.net/benefit-finder/death
`<div id="pagesurvey-qual-container"></div>` shows up as expected.



![Image](https://github.com/user-attachments/assets/d90bba60-4c7b-41a1-a325-fdd5a1f26bc9)
