### ISSUE TITLE
Benefit finder content categorization

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#1645]
### User / Persona

member of the public searching for benefits

### Reason / Justification

See both benefit finder and [USAGov benefit](https://beta-stage.usa.gov/find-benefits-category) content categorized for easiest browsing

### Acceptance Criteria (AC)

- All benefit finder content is tagged using the same categories as USAGov

**Comment by diegocob** [comment]
Hey Ernie, 
Is this to categorize each benefit similar to the USAGov categorization? Maybe we can connect on more details about this.

**Comment by erniedeeb** [comment]
@diegocob Exactly - there's no immediate user-facing use case for categorization at the moment, but I think it would be wise to keep our content aligned with USAGov's categories for potential future product exploration.

**Comment by diegocob** [comment]
Ok, will work on this for the next sprint.

**Comment by EnriqueOrt-GSA** [comment]
Goal - end of Qtr

**Comment by diegocob** [comment]
This was completed. Closing the ticket out.
