### ISSUE TITLE
Title and summary content for "All Benefits" card on BF landing page

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#1658]
### Description

In order to launch the all benefits form alongside the benefits.gov transition, we need: 

- an official name for the form
- a single description sentence
 
Both will be shown in the card on the new benefits transition landing page. Screenshot below for reference. 

![Image](https://github.com/user-attachments/assets/74338b27-5030-4dd7-a602-358d07b37202)

**Comment by diegocob** [comment]
Working on getting the team's input for the new all-benefit name.

The one-line description could be: Answer a few questions to learn about all the federal benefits you may be eligible for.

Should we get USAGov's content team's input on this? Perhaps once we have a proposal with the title we can ask about both.

@fongcindy @erniedeeb

**Comment by erniedeeb** [comment]
I don't have a strong preference, I think both "all benefits search" and "general benefits search" are equally vague. "Multiple life event search" could also work, but is also pretty vague. 

@diegocob Can you create the summary copy, and we can use that long with the above title options to decide with USAGov which option is best?

**Comment by diegocob** [comment]
PS: Any update on the possible new name for the all-benefits page?

**Comment by erniedeeb** [comment]
Thanks Diego! I have some ideas for how we can improve the language, but going to run these past Shoshana for feedback.

We're sticking to All benefits as the page name, and trying to be hyper descriptive of the scope of "all" in the summary.

**Comment by erniedeeb** [comment]
We've updated the summary and meta description to be overly clear in order to set user expectations. We just need to have the suggested content translated to Spanish now: https://docs.google.com/document/d/1IGiQHv0OIJBdTogA5FYZJq4Em9L-hGRbPuIvTnGrrOU/edit

I will create a separate ticket for testing this content, which we can do post-launch.

**Comment by erniedeeb** [comment]
@diegocob I also added some updated copy for the start page summary. It's a hybrid of the original and suggested copy to be used on the cards.

**Comment by diegocob** [comment]
This ticket was completed and the all-benefit pages were published.
