### ISSUE TITLE
TSP eligibility criteria

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1665]
### Description

Need to edit Thrift savings plan eligibility criteria currently is:
1. Applicant paid into SS
2. Applicant is over 60 years
3. Applicant is a US citizen

This plan is eligible for federal employees and members of the uniformed service. Would need to edit that the applicant does not need to be 60 years old but not open it to someone who is not a federal employee or part of the the uniformed services.

### User Story

As a federal employee or member of the uniformed services I need to know when I am eligible for TSP.

### Acceptance Criteria

Figure out a way to tailor the eligibility criteria to be more accurate.

**Comment by diegocob** [comment]
@erniedeeb, do you have any thoughts on how to make this eligibility criteria more accurate?

**Comment by diegocob** [comment]
Ok, like where this is going. But, if we use the same question to ask if they are military or a fed, and a federal employee is not military they will become eligible for many other benefits that they are really not eligible for. And, if we add it as a separate branched/child question of the military parent question, they may not even see it if they are not military. 

Also, if we add the question of federal employee as a stand alone in the retirement life event form, bc of the way the logic works, they would have to be a federal employee and served in the military. This is one of the cases where we could improve our logic to allow OR categories, where you can be either military or federal employee, and not necessarily both.

**Comment by erniedeeb** [comment]
Good point. Another option would be to make active duty military a requirement for eligibility, but show TSP as more info needed with some note for federal employees if the user has answered no to the military question.

**Comment by diegocob** [comment]
That could be a good work around. Will work on the content for this.

**Comment by diegocob** [comment]
Hey @erniedeeb, I couldn't do the more info needed for this criteria since that requires for a question to be unanswered, could be a question not listed on the form, but that would apply for both military and fed applicants. So, I just changed the description and bolded the part about the federal employees being eligible.

#### EN:
A Federal Government-sponsored retirement savings and investment plan for members of the uniformed services. **Federal employees are also eligible.** The TSP offers the same type of savings and tax benefits that private corporations offer employees under '401(k)' plans.

#### ES:
Un plan de ahorro e inversión del Gobierno federal para la jubilación de miembros de los servicios uniformados. **Los empleados federales también son elegibles.** El TSP ofrece los mismos tipos de ahorro y beneficios fiscales que las empresas privadas le ofrecen a sus empleados con planes llamados '401(k)'.

Lmk if that works

**Comment by erniedeeb** [comment]
It's not a perfect solution but it works for now. Are we showing TSP as likely eligible to users who answer no to the military question?

**Comment by diegocob** [comment]
If they answer no to serving in the active military, the benefit will be not eligible, and they will only read about it in that section. Unless they see the not eligible benefits and read the summary, they won't know they are eligible in the BF.

We'd have to fix the logic of the finder which would also help us improve how we show eligibility for other benefits. We've spoken to Scott and Gene about it but it seems to be a high LoE. Flagging @fongcindy.

**Comment by diegocob** [comment]
These are the summary descriptions I edited. Added the active military requirement. If I added the federal employee as an unanswered/more info criteria then all military members will not see this benefit. Since there are about 2M federal employees vs 18M military plus families, proritized this. 

Another option would be to create another benefit with the federal employee criteria, but no question. So it will show up in not eligible for anyone who is a citizen and 60+ years and may add another benefit to that long list to everyone, which doesn't seem like a great trade off, given that federal employees may already know about TSP from their agency.


#### Summary
A retirement savings and investment plan sponsored by the Federal Government for members of the uniformed services and federal employees. The TSP offers similar savings and tax benefits that private corporations offer under '401(k)' plans.

#### ES Summary
Un plan de ahorro e inversión del Gobierno federal para la jubilación de miembros de los servicios uniformados y empleados federales. El TSP ofrece los mismos tipos de ahorro y beneficios que las empresas privadas ofrecen con planes llamados '401(k)'.
