### ISSUE TITLE
DESIGN | Update Summary Box Styles

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1666]
### Description

![Image](https://github.com/user-attachments/assets/fed51834-fa7f-4952-b313-448eb49a09fb)

### Acceptance Criteria

- [ ] summary box styles are updated to align with usagov requirements

**Comment by ErnestoFernandezAlvarez** [comment]
@EnriqueOrt-GSA @scottqueen-bixal 
The summary box looks great. Thank you!
