### ISSUE TITLE
Add search title content

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1673]
### Description

Add search title content.

Benefit finder: death of a loved one
Dealing with the death of a loved one

Benefit finder: retirement
Approaching retirement

Benefit finder: disability
Living with a disability or illness

### Acceptance Criteria

search title content added into life event

**Comment by diegocob** [comment]
The Spanish search titles are:
ES Discapacidad/disability
Vivir con una discapacidad o enfermedad

ES Jubilación/Retirement
Prepararse para la jubilación

ES Muerte/Death
Afrontar la muerte de un ser querido

ES Dificultad económica/Financial hardship
Enfrentar dificultades económicas

We still need to finalize the all-benefits content which may change. 

Had also worked and added this to [ticket 1427](https://github.com/GSA/px-benefit-finder/issues/1427)

**Comment by diegocob** [comment]
@gchi25, the search fields for all-benefits are TBD.

**Comment by diegocob** [comment]
This can be closed. All benefit search titles were confirmed to: 
EN: All benefits
ES: Todos los beneficios
