### ISSUE TITLE
QA | BUGFIX error dataLayer event

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1684]
### Domain

data

### Related Issue(s)

DUE: 8/19
ENV: https://bf-cms-main.bxdev.net/benefit-finder/death

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

[Submit dataLayer update if errorCount changes](https://github.com/GSA/px-benefit-finder/issues/1669)	https://github.com/GSA/px-benefit-finder/issues/1669

### Description

please verify that the issue reported in [QA | Data Analytics v0.6.0.beta.1](https://github.com/GSA/px-benefit-finder/issues/1660)	https://github.com/GSA/px-benefit-finder/issues/1660, has been resolved

**Comment by nickpistone** [comment]
tested here: https://bf-cms-dev.bxdev.net/benefit-finder/death

I tested by completing one required question at a time and submitting until I got through all 5. I was able to see the submission attempt event fire on each submission and the error count updated each time to show the new errors. RESOLVED.

**Comment by scottqueen-bixal** [comment]
completed
