### ISSUE TITLE
QA | DESIGN v0.6.0.beta

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1685]
### Domain

design

### Related Issue(s)

DUE: 8/19
ENV: https://bf-cms-main.bxdev.net/benefit-finder/death

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

The following issues have been addressed and are ready for design review

https://github.com/GSA/px-benefit-finder/issues/1666
https://github.com/GSA/px-benefit-finder/issues/1661
https://github.com/GSA/px-benefit-finder/issues/1633
https://github.com/GSA/px-benefit-finder/issues/1656
https://github.com/GSA/px-benefit-finder/issues/1632
https://github.com/GSA/px-benefit-finder/issues/1629
https://github.com/GSA/px-benefit-finder/issues/1451
https://github.com/GSA/px-benefit-finder/issues/1449
https://github.com/GSA/px-benefit-finder/issues/1448
https://github.com/GSA/px-benefit-finder/issues/1447

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1666
@gscottqueen The summary box looks great. Just would like to confirm the color of the Link: "1A4480
Blue-link". On my screen it looked a bit darker but It might just be my monitor. If the color code is correct, please disregard the note.
Thank you

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1661

This item was resolved and looks great!
Thank you!

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1633

The buttons look good and follow the color and padding specification from the Client.
However, please note that for the redesign these CTA's-buttons have changed:

**Form: The new design uses "Next" Cta, instead of "Continue" Cta.
Landing page: The new design uses "Start finding benefits", instead of "Start" Cta**

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1656
This update has been completed and looks great!
Note: initially the client wanted body copy text size for this component, but we pushed back. There might be a revision in the future as we complete the entire design of the user flow.

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1632

@gscottqueen 
This comment is about the MODAL BUTTONS only: the size and padding look good! However please note that the legend was changed for the redesign, following A11y recommendations:

**Change "See results" to "See your results"
Change "Review selections" to "Review your selections"**


<img width="796" alt="Screenshot 2024-08-16 at 2 50 09 PM" src="https://github.com/user-attachments/assets/93c2f493-63e3-436c-99f4-d8b592d525cd">

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1629

Color changes requested by client have been address and look good!

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1451
@gscottqueen @fongcindy 
This is pending further revisions and will include the size and margins of the entire pages.

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1449

The accordions look great! The following are minor details to refine:

**1. There is not outline around the active state container of the accordion (Client'r Request) (see image ref)
2. Space between the CTA and the border of the container is 32px (see image ref)
3. The lines between the criteria items are too thick. Please take a look at the close up screenshot taken from the site. (see image ref)**

<img width="1462" alt="Screenshot 2024-08-16 at 3 34 55 PM" src="https://github.com/user-attachments/assets/89cf0f0c-0461-4083-8ac9-e317999dfd5f">


This is the new ticket to capture these items:

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal @fongcindy 
This is the ticket created to capture the Red Error Line Spacing Issue that we discussed last week.

https://github.com/GSA/px-benefit-finder/issues/1704#:~:text=Space%20between%20ERROR%20message%20line%20and%20next%20fied%20%231704


![Image](https://github.com/user-attachments/assets/b0ca2119-d2a7-44b2-826f-0501656a7834)
![Image](https://github.com/user-attachments/assets/763b842f-a45f-431d-8126-5ad43bae7a85)

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1448

The cards look correct according to design details and proportions, however please note that the font changes has not been applied yet.

The font details are as follows and they are listed in the [Figma File](https://www.figma.com/design/xij2PUZTouE6cco8f1F2Bn/ReDesign-Benefit-Finder?node-id=1033-1171&t=gZ1doNJCpUNO3Wbl-1):



![Image](https://github.com/user-attachments/assets/1f83be63-f92c-4198-89da-8df22b3d54b0)

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal @fongcindy 

Radio button change to Client's design style #1708

**Comment by scottqueen-bixal** [comment]
> 1A4480
confirmed:
<img width="1508" alt="Screenshot 2024-08-19 at 3 34 53 PM" src="https://github.com/user-attachments/assets/e66436dd-60b3-4a27-9ccd-c72be88c7b12">

**Comment by ErnestoFernandezAlvarez** [comment]
https://github.com/GSA/px-benefit-finder/issues/1447

The icons display correctly on the Benefit cards.

These icons have been updated to 45x45 box size and converted to SVG: https://drive.google.com/drive/folders/17qpXww2C_oFq4ybIS_D0W3fxzvSYKjgP?usp=drive_link

**Comment by scottqueen-bixal** [comment]
> #1447
> 
> The icons display correctly only in some result pages.
> 
> A new ticket has been created to capture this bug: #1711
> 
> Please see how the DOLO icon displays filled in one of the result pages:
> 
> ![Image](https://private-user-images.githubusercontent.com/125310691/359227187-738d2d5d-f30c-4779-bc9f-58ca2481c726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTc1ODcsIm5iZiI6MTcyNDA5NzI4NywicGF0aCI6Ii8xMjUzMTA2OTEvMzU5MjI3MTg3LTczOGQyZDVkLWYzMGMtNDc3OS1iYzlmLTU4Y2EyNDgxYzcyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxOTU0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzZkYjFkYzNjYWIyZTU4OTA5YmI3MGYwZTEyNmY3ODk4YjhkOGNjZWRmZmJmYThjZDA4ZjQxZWRkMzUyZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B95AWE7T-_Sm8m6YjdGBGtUKNBmFzIjTjfEU1pgCGTo)
> 
> These icons have been updated to 45x45 box size and converted to SVG: https://drive.google.com/drive/folders/17qpXww2C_oFq4ybIS_D0W3fxzvSYKjgP?usp=drive_link

the death icon was missing some fill paths on the previous export, this new export seems to do the trick.

All the svgs are still exported as 46 x 45

**Comment by ErnestoFernandezAlvarez** [comment]
thanks @scottqueen-bixal 
Let me know if you need them exported again. Sometimes these files get corrupted!
