### ISSUE TITLE
Confirm new transition page will not affect breadcrumbs and IA

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#1689]
### Description

The page at [benefit finder page](https://beta-stage.usa.gov/find-benefits-category#category-finder) on stage will be replacing the [existing benefit finder page](https://www.usa.gov/benefit-finder). The new page will use the current `/benefit-finder` URL. 

We need to make sure that this change will not break anything in the breadcrumbs or nav, and that users will be able to navigate between benefit finder life experiences and the new benefit finder page.

**Comment by gchi25** [comment]
http://localhost/find-benefits-category
![image](https://github.com/user-attachments/assets/65b7ebbb-1527-47c5-b454-d80d79703285)

Edit Basic Page What government benefits go you qualify for?
Page Type: Benefits Category Search 

Tested in local development site.

Update menu link of Benefit Finder to link to transition page.
http://localhost/admin/structure/menu/manage/left-menu-english
![image](https://github.com/user-attachments/assets/1780732a-6d4e-43c4-989c-5e4b2cecb40f)

Navigate to benefits page.
http://localhost/benefits
![image](https://github.com/user-attachments/assets/9d4c4c16-ed78-4272-ac18-c4322bd8969e)

CLICK "What " to get into transition page.
http://localhost/find-benefits-category
![image](https://github.com/user-attachments/assets/24384248-da30-4c96-be80-e6643bdc168b)

CLICK  "Benefit finder: death of a loved one" link. It goes to Benefit Finder life event page as expected.
The breadcrumb works well as expected.
![image](https://github.com/user-attachments/assets/2300434f-41a1-41ab-a061-a9071bfafbdf)

Make screen narrow. The mobile menu works well as expected.
![image](https://github.com/user-attachments/assets/f1134ea6-0ec1-4c38-a61a-47169abd7133)
