### ISSUE TITLE
Create life event and life event form in ES for all benefits

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1692]
### Description

Create a life event and life event form in ES for all benefits.

### Acceptance Criteria

a life event and life event form in ES for all benefits created

**Comment by gchi25** [comment]
@diegocob 

In production:

1. Created ES life event "Buscador de beneficios: ES all benefits" 
2. Created ES life event form "Buscador de beneficios: ES all benefits" as published

You can work on life event form.

**Comment by diegocob** [comment]
Completed entering the content for ES buscador de beneficios: todos los beneficios. 

@gchi25, you can run any tests necessary on Main so we can publish next week on 9/5.

**Comment by diegocob** [comment]
This is created and was shared with the UX team for review.

**Comment by diegocob** [comment]
Created it in Spanish and ready for publishing.
