### ISSUE TITLE
TEST page level survey on usagov dev

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1694]
### Description

Since we have qualtrics set up with GTM we can run a test on usagov dev to see how the application will perform and look when in the usagov env.

### User Story

- [x] as a developer I want to confirm functionality of survey rendering on the benefit finder rendered twig template

### Acceptance Criteria

- [ ] PR to usagov dev with twig change in template
- [ ] merged to dev
- [ ] confirmed survey renders
- [ ] confirmed survey is visible with usagov analytics
- [ ] integration shared with BF tech team and product lead for review
- [ ] PR to usagov dev to revert twig change in bf template
- [ ] merged to dev
- [ ] confirmed change removed

**Comment by gchi25** [comment]
https://beta-dev.usa.gov/benefit-finder/death
Page level survey shows up in benefit finder life event.
The survey works well as expected.

![Image](https://github.com/user-attachments/assets/6a38ea17-a901-4deb-af7e-7140f31b2fb2)

**Comment by scottqueen-bixal** [comment]
because or main element doesn't have a container, we need to add some additional markup to align better with other USAGov implementations of the form - ie. https://www.usa.gov/life-events

We can try wrapping the survey with
`grid-container` and `additional_body_info` classes, so our new markup would look like,

```HTML
<div class="bf-qual-survey grid-container" >
    <div class="additional_body_info" >
        <div id="pagesurvey-qual-container"></div>
    </div>
</div>
```

**Comment by scottqueen-bixal** [comment]
confirmed this is working on usagov `beta-dev`
