### ISSUE TITLE
Avoid redundancy " 2 of 2 " in this H2 is being called out in step indicator

### ISSUE THREAD

**Issue by ErnestoFernandezAlvarez** [GSA/px-benefit-finder#1695]
### What's expected

@scottqueen-bixal @diegocob @angelina-smith @fongcindy @diegocob 

This ticket is part of the QA due 8/19.
The " 2 of 2 " in this H2 is not needed as the step indicator serves that purpose. It could be  confusing for users and screen readers, specially in that size of font.

Adding Diego and Angelina for visibility.
**NOTE: Will be addressed in a future release.**

<img width="726" alt="Screenshot 2024-08-16 at 12 18 45 PM" src="https://github.com/user-attachments/assets/564457b1-2129-451d-ae33-58a75c8d7f5c">

### What happened

Redundant message "2 of 2" in H2

### How to replicate

Eliminate the "2 of 2" from H2

**Comment by diegocob** [comment]
Hi Ernesto, thanks for pointing this out. The way the content is structured on Drupal, the step indicator is the same field as the H2. There is no way, currently, to have different fields for each. This could be something we can bring up for in the future.

**Comment by ErnestoFernandezAlvarez** [comment]
Thank you @diegocob
We briefly discussed on a call with @fongcindy and  @scottqueen-bixal, this would require some heavier lift to fix, so we will try to correct it for a future release/ Sprint

**Comment by scottqueen-bixal** [comment]
This occurs only because of content in our `main` env. Unless this is a change planned to be made upstream, we won't be implementing.

CC: @fongcindy

**Comment by ErnestoFernandezAlvarez** [comment]
Thanks for the follow up @gscottqueen @diegocob @fongcindy 
I think this is probably the #1 thing to fix whenever it can be done.

**Comment by diegocob** [comment]
We took out the # of #, 1 of 2 description in the headings and it makes it read a lot smoother.

**Comment by fongcindy** [comment]
Resolved
