### ISSUE TITLE
CTA legend changes

### ISSUE THREAD

**Issue by ErnestoFernandezAlvarez** [GSA/px-benefit-finder#1697]
### What's expected

Following Client's feedback for the redesign as well as A11y recommendations based on AT User testings, we changed the following CTAs:

**Form: The new design uses "Next" Cta, instead of "Continue" Cta.
Landing page: The new design uses "Start finding benefits", instead of "Start" Cta** 

Note: these are not Critical Issues

<img width="1128" alt="Screenshot 2024-08-16 at 2 24 48 PM" src="https://github.com/user-attachments/assets/625aded0-d6d8-4c8e-830b-103bac94fb97">
<img width="1118" alt="Screenshot 2024-08-16 at 2 24 58 PM" src="https://github.com/user-attachments/assets/58d79015-10ba-4586-8644-680321113a5a">

### What happened

Design changes based on UT and client's feedback.

### How to replicate

These cta's will need a legend change as described above.

**Comment by scottqueen-bixal** [comment]
Blocked need conte t

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal @fongcindy I'd consider it resolved from the design point view. Please monitor the content changes: if the "Continue" button changes to "Next", the button total size should not change and match the "Back" button.

**Comment by scottqueen-bixal** [comment]
tracking the content changes here -> https://github.com/GSA/px-benefit-finder/issues/1662
