### ISSUE TITLE
Modal CTA's legend change

### ISSUE THREAD

**Issue by ErnestoFernandezAlvarez** [GSA/px-benefit-finder#1698]
### What's expected

Following A11y recommendations, we changed these CTA's as follows:
Change "See results" to "See your results"
Change "Review selections" to "Review your selections"
<img width="796" alt="Screenshot 2024-08-16 at 2 50 09 PM" src="https://github.com/user-attachments/assets/28a73404-bf23-490b-ad6f-c34b0d1929eb">

### What happened

Change described above

### How to replicate

Follow change described above.

**Comment by scottqueen-bixal** [comment]
Bllocked need content

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @scottqueen-bixal Closing this ticket from the design side.
Content had suggested to use "Your" in these cta's. However, this change could be done on Drupal directly.

**Comment by scottqueen-bixal** [comment]
tracking the content changes here -> https://github.com/GSA/px-benefit-finder/issues/1662
