### ISSUE TITLE
Benefit Finder menu and breadcrumb

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#170]
Review usa.gov life event "Survivor Benefits" menu and breadcrumb.
Implement Benefit Finder life event menu and breadcrumb.
Make mobile menu showing up in Benefit Finder app.

**Comment by EnriqueOrt** [comment]
@gchi25 could you provide an update or close out the ticket? Thanks!

**Comment by scottqueen-bixal** [comment]
closing as stale
