### ISSUE TITLE
Sync field(s) in life event form with life event node

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1720]
### User / Persona

content editor

### Reason / Justification

The content editor needs to manage search title. But the search title field is in life event content, used for content structure and benefit category search etc. The life event content is managed by dev team. So we need to provide a mechanism for content editor to manage search title content.

The ID of life event and the ID corresponding life event form are same. We will add search title field in life event form, and sync this field value into life event content. When content editor updates the search title in life event form, the system will sync it into the search title of corresponding life event.

So this work will provide a mechanism for content editor to manage search title content but no needing to tell dev team to make the input in life event content.

### Acceptance Criteria (AC)

- [ ] have search title field in life event form
- [ ] the search title of life event form and life event sync

**Comment by scottqueen-bixal** [comment]
These are the fields we need to sync to life-event form 

Title
ID
Page Intro
Meta Description
Short Description
Search Title
Summary
Header HTML

**Comment by gchi25** [comment]
Do not use this method.
