### ISSUE TITLE
Resolve "Limited income" question confusion

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1738]
### Description

Based on unmoderated testing [findings](https://app.mural.co/t/gsa6/m/gsa6/1724703050632/babc09ae934fd95dc174539c83b88a14ab210588?sender=uc3d84fb6131585f59fdc6776) there was confusion regarding the 'limited income' question (Do you have limited income and resources?), in the disability and retirement LE pages. 

Options:

**1. Define "limited income"**, we could use the federal poverty level. This might discourage users if they do not meet this income requirement. Might have to redefine the income based on different benefits and eligibility. If we state a specific income amount, we might need to revise the value when this amount changes (maintenance). 
**2. Revise the question** to be more general but can still help users without defining "limited income". This might be the easiest option, clearly wording "limited" or "low" income to prevent confusion. Con: we are still not being specific enough. Low income varies and is often based on region, can use federal income. 
**3. Eliminate the question**, will keep things more simple, however users might be unsure if they qualify based on their income. Users will need to address income question at some point, if we remove this, they will face this on agency website/application.

**Comment by diegocob** [comment]
Based on our UX sync we are going to put a hint in the question with a hyperlink: Your annual income is within the [federal poverty guidelines.](https://aspe.hhs.gov/topics/poverty-economic-mobility/poverty-guidelines) 

@gchi25, assigning this to you so we can confirm when we could hyperlink in this section.

**Comment by fongcindy** [comment]
@diegocob @gchi25 Any updates? Are we able to add a hyperlink?

**Comment by diegocob** [comment]
@fongcindy, not sure if this was prioritized and if the tech team was working on it. I understood it was in the backlog.

**Comment by diegocob** [comment]
This ticket is tracked on #1787 . Closing this ticket out in the mean time.
