### ISSUE TITLE
a11y | date input labels

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#177]
8 | 1-High | about the applicant |   |   | unclear wording in the numeral fields. The year says "year edit, has popup. Type in text" | In the image to the left I hear "type in text. Has popup" which is weird and confusing. It says type in text but not "enter numerals for day"
-- | -- | -- | -- | -- | -- | --

<google-sheets-html-origin><style type="text/css"></style>

9 | 1-High | about the applicant | see image attached |

![Image](https://github.com/GSA/px-bears-drupal/assets/37077057/5f6737ad-3b06-4558-87a2-7dc5298bc958)

**Comment by amycole501** [comment]
Regarding this:
When I load this page https://bears-storybook.app.cloud.gov/iframe.html?id=app--primary&viewMode=story the first thing I hear in JAWS and NVDA is the error status message.

We have found this same issue in the USWDS site. There may be a CSS/aria label where the error is presenting/being announced as a label in JAWS.

**Comment by scottqueen-bixal** [comment]
sounds good @amycole501 , will investigate and reach out to our USWDS team for some information on potential fixes.

**Comment by scottqueen-bixal** [comment]
closing this ticket in lieu of ticket for tracking new issue here https://github.com/orgs/GSA/projects/48/views/16?filterQuery=sprint%3A%40current+assignee%3A%22scottqueen-bixal%22&pane=issue&itemId=47462588
