### ISSUE TITLE
Get AJAX HTTP error in JSON file generation when creating new life event

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1770]
### What's expected

When edit and save benefit finder content, the system automatically generates JSON files.

### What happened

When edit and save benefit finder content, the system automatically generates JSON files but gets "AJAX HTTP error".

### How to replicate

Create a new life event and save as draft
Create the corresponding life event form and save as draft
Edit an existing benefit finder content
Save as published 
The system automatically generates JSON files
Get "AJAX HTTP error" and generating JSON files incomplete

![image](https://github.com/user-attachments/assets/2b1ccb04-27c3-4530-aacc-dde58ffbde57)

**Comment by scottqueen-bixal** [comment]
[4] Still working on this

https://github.com/GSA/px-benefit-finder/issues/1770
Get AJAX HTTP error in JSON file generation when creating new life event #1770
>>this work was planned for Sprint 42, but can you confirm if it is completed
Still working on this.
