### ISSUE TITLE
Redesign | Mobile Typography 

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1776]
### Description

Changes to typography and type scale for mobile. 
Ernesto will make slight changes from desktop to mobile format

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @gscottqueen 

Attached is the Mobile type scale for the Benefit Finder.
For now I just added it next the Desktop version on the Hand off to devs page.

Note: all the fonts have been reduced for Mobile, except for the fonts used on CTA's which is 17.6pt for both Desktop and Mobile, therefore all buttons should be used for mobile as well (according to client)

If we need to further tweak the scale when we see it applied to wireframes, I will let you know and update the file accordingly.
![Group 1205](https://github.com/user-attachments/assets/bb6af533-ad99-4967-a3a4-ed2d9d35e6c5)

https://www.figma.com/design/xij2PUZTouE6cco8f1F2Bn/ReDesign-Benefit-Finder?node-id=1033-1171&t=alMBNXy4wVXlA5E2-1

**Comment by scottqueen-bixal** [comment]
this hasn't been implemented on mobile yet, did I miss an update?

**Comment by ErnestoFernandezAlvarez** [comment]
Good morning @scottqueen-bixal, last time I checked in with @fongcindy about the mobile typescale, it seemed that it was ready to get implemented, however I don't know how it was prioritized for your area.

**I am currently working on the mobile screens and will apply to type scale, I think you are working ahead of me.**

This is the link to the file (the files are now under GSA's PX portfolio, they are the admin now):
https://www.figma.com/design/3qui91uX0iE4YMNrnx4gzK/ReDesign-Benefit-Finder?node-id=16-2035&t=m7sKURg5ZsauvGTt-1

**Comment by fongcindy** [comment]
Let's combine this with #1837, Do **not** close, unless #1837  is closed. Will make sure that the Mobile screens captures mobile typography. 
@ErnestoFernandezAlvarez
