### ISSUE TITLE
replace all_benefits icon

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1779]
### Description

current

![Image](https://github.com/user-attachments/assets/7ecdea97-185b-4791-9e53-bfdc344d2df6)

updated

![Image](https://github.com/user-attachments/assets/f0f38ce4-2e90-4c76-9e95-0ccff2de15ff)

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @scottqueen-bixal 

Hello, adding a visual and the link to the Icon Folder. 
Thank you!
<img width="1871" alt="Screenshot 2024-09-06 at 10 02 16 AM" src="https://github.com/user-attachments/assets/617d6cff-9dfb-40a6-97d3-60d1f06a774e">
https://drive.google.com/drive/folders/17qpXww2C_oFq4ybIS_D0W3fxzvSYKjgP?usp=drive_link
