### ISSUE TITLE
Form-page-2 page change event firing twice 

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1786]
### What's expected

Each time the virtual page changes, one bf_page_change data layer event should fire

### What happened

When the second page is submitted and you get to the modal, you also get an additional page_change event for bf-form-2. So it's like the second form page is reloading when you submit it and you end up with a virtual pageview for the modal as well as two virtual pageviews for bf-form-2 preceding it.

### How to replicate

Go to /disability and go through the pages until you get to the modal. Check the data layer on every page, and you will see that an extra page_change event fires when you click to submit bf-form-2 (More about you).

**Comment by nickpistone** [comment]
Just tested this on /disability and I still see 2 page change events for bf-form-2.

**Comment by scottqueen-bixal** [comment]
during deployment technical testing, we found that this fix was inconsistent and needs additional work. Will release as next patch.

**Comment by nickpistone** [comment]
Tested here: https://bf-cms-main.bxdev.net/benefit-finder/disability
Verified that the page_change event is no longer double firing.
