### ISSUE TITLE
Create hyperlink for 'hint' section

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1787]
### Description

We need to be able to add a hyperlink in the 'hint' section of a question. 

In the question, "Do you have limited income and resources" we would like the hint to be Your annual household is within the [poverty guidelines.](https://aspe.hhs.gov/topics/poverty-economic-mobility/poverty-guidelines)

![Image](https://github.com/user-attachments/assets/5720bece-666d-4d65-9ccc-026e915c95b4)

### User Story

As a content editor I should be able to hyperlink text in the "hint" section.

As a user I need to know what the federal poverty guidelines is through a hyperlink.

### Acceptance Criteria

- [ ] Change the hint section so that content editors can hyperlink
- [ ] Create hyperlink test in staging/dev environment
- [ ] Test and QA in dev
- [ ] Create test in Production
- [ ] Test and QA
- [ ] Publish

**Comment by scottqueen-bixal** [comment]
We need to  update hint field to be rich text, return HTML, in JSON if this is required.

**Comment by gchi25** [comment]
Wait for approval.

**Comment by fongcindy** [comment]
There is UX discussions regarding tool tips vs links, etc. Need more discussions and verified solution, may be v1 need, but need a solution
