### ISSUE TITLE
All Benefits content needed to launch

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1791]
### Description

Life event "all benetifs" English and Spanish version.

- [ ] 1. Input meta description, short description, search title in English life event "All Benefits"
- [ ] 2. Input meta description, short description, search title in Spanish life event "All Benefits"
- [ ] 3. Make English app published version ready https://cms.usa.gov/benefit-finder/all-benefits
- [ ] 4. Make Spanish app published ready https://cms.usa.gov/es/buscador-beneficios/todos-beneficios
- [ ] 5. Publish life event English All Benefits
- [ ] 6. Publish life event Spanish All Benefits
- [ ] 7. Add language toggle

https://cms.usa.gov/benefit-finder
Then they will appear in landing page like other 3 life events.

### Acceptance Criteria

- [ ] English life event "All Benefits" app published version up
- [ ] Spanish life event "All Benefits" app published version up
- [ ] English All Benefits app in Benefit Finder landing page
- [ ] Spanish All Benefits app in Benefit Finder landing page

**Comment by diegocob** [comment]
| Field | English | Spanish |
|-----|---|---|
| Meta description | Find benefits across three life events at once: disability, death of a loved one, and retirement. Start here if two or more of these are relevant to you. | Encuentre beneficios de tres eventos de vida a la vez: discapacidad, muerte de un ser querido y jubilación. Empiece aquí si dos o más de estos eventos son para usted.|
| Short description | Find benefits across benefit finder’s three life events: disability, death of a loved one, and retirement. Start here if two or more of these life events are relevant to you. | Encuentre beneficios a través de los tres eventos de vida del buscador de beneficios: discapacidad, muerte y jubilación. Comience aquí si dos o más de estos eventos aplican para usted. |
| Search title | TBC checking with Ernie | TBC Checking with Ernie |

Used the content from [all-benefits content doc](https://docs.google.com/document/d/1IGiQHv0OIJBdTogA5FYZJq4Em9L-hGRbPuIvTnGrrOU/edit). Adding @erniedeeb for visibility.

**Comment by gchi25** [comment]
Do not see icon for all benefits.
![image](https://github.com/user-attachments/assets/44b8d15c-d7e6-40be-bff7-a0c93694390e)

**Comment by gchi25** [comment]
@diegocob @fongcindy 
Do we care about where the life event displays? 
I think that view is sorted alphabetically so it might display differently depending on language, no?

**Comment by diegocob** [comment]
Can it be displayed last?

**Comment by diegocob** [comment]
Hi Gene, still waiting for USAGov to confirm the search title. Once that is confirmed you could go ahead and add the content and publish the event.

**Comment by diegocob** [comment]
@gchi25, the search title is confirmed and we can add it to the life event. Is there a way to publish it in draft mode so we can see how it comes up on the landing page?

**Comment by diegocob** [comment]
Made some changes to the content in ES, that need to be made in the meta and short description.

**Comment by gchi25** [comment]
> Encuentre beneficios en el buscador a través de tres etapas de la vida: discapacidad, muerte de un ser querido y jubilación. Comience aquí si dos o más de estas etapas son para usted.

Updated life event content with updated meta and short description.

**Comment by diegocob** [comment]
@gchi25, could we close this ticket. All benefits pages are up in EN and ES and I think all the acceptance criteria was met.
