### ISSUE TITLE
All benefits in menu system

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1793]
### Description

Make "All benefits" in menu system, same as Death, Retirement, Disability life event.

Currently "all benefits" is not in menu system.

<img width=500 src=https://github.com/user-attachments/assets/146bc977-f7c7-4b24-a8cc-9e4c71425966>

This is its breadcrumb.

![Image](https://github.com/user-attachments/assets/1e1d4cf4-6010-4567-ba75-deea2cdca82f)

This is its mobile menu.

![Image](https://github.com/user-attachments/assets/3f640dcd-f351-4ea6-9d47-614de83ef126)

### Acceptance Criteria

All benefits in menu system

**Comment by diegocob** [comment]
Adding @erniedeeb - should the all benefits show up in the menu of the benfits' pages?

**Comment by erniedeeb** [comment]
Great call out Diego, yes it should! We should treat it the same as the other life events.

**Comment by erniedeeb** [comment]
@gchi25 Per Amy, we should be able to add it as a menu item similarly to how other life events have been added. Here's DOLO for reference. 
![image](https://github.com/user-attachments/assets/7a0faa3d-a5ce-4f29-92c1-926484fec0ee)

**Comment by gchi25** [comment]
Made "All Benefits" life event English and Spanish in menu system.
Tested. The breadcrumb and mobile menu work well as expected.

![image](https://github.com/user-attachments/assets/70311538-6c96-4787-9822-f03e3ca0bc1f)

![image](https://github.com/user-attachments/assets/7014c9cd-e667-4402-bf24-1645ceda0415)

![image](https://github.com/user-attachments/assets/c45a91d2-0366-45e9-b000-63df43edff68)

![image](https://github.com/user-attachments/assets/cb50accb-5bf4-4171-a61f-7c6c55c7cb50)

**Comment by diegocob** [comment]
Looks good Gene, we could close this ticket, it seems.
