### ISSUE TITLE
Add display order field in life event

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1795]
### Description

Add display order field in life event. It will be used to arrange the order of life events in benefit finder box in benefit finder landing page.

### Acceptance Criteria

life event node has numeric field "display order"

**Comment by diegocob** [comment]
Couldn't find the display order field on main envi. @gchi25 is working to show this.
![Image](https://github.com/user-attachments/assets/b8f74fba-67a4-4fe5-ba3d-5f937dc073b5)
