### ISSUE TITLE
QA | Content v0.7.0.beta.1

### ISSUE THREAD

**Issue by EnriqueOrt-GSA** [GSA/px-benefit-finder#1828]
### Domain

ux

### Related Issue(s)

[Add display order field in life event](https://github.com/GSA/px-benefit-finder/issues/1795)	https://github.com/GSA/px-benefit-finder/issues/1795

[Stray HTML on "Explore other potential benefits" page](https://github.com/GSA/px-benefit-finder/issues/1814)	https://github.com/GSA/px-benefit-finder/issues/1814

### Description

Content QA - check display order field in life event

Due date: 09/23/2024 or as soon as available

**Comment by diegocob** [comment]
While QA'ing noticed the results modal was a bit off center on Main. This is out of scope but flagging it here.
![Image](https://github.com/user-attachments/assets/30084b1e-9cf2-43da-9069-cd0ea3632cea)

**Comment by diegocob** [comment]
Communicated with Gene and the display order field is now showing in the life events. ![Image](https://github.com/user-attachments/assets/c3a80fa5-09b3-4b80-a66e-9b03115b6b98)

I was not able to test it since there is code still missing.

**Comment by diegocob** [comment]
This was completed and Gene launched the order of life event cards proposed by Ernie.
