### ISSUE TITLE
NEW FEATURE | client side routing in embedded applications

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1831]
Implementing a client side browser will come with allow us to access more advanced dynamics in location and state organized views, like; 

- [NEW FEATURE | Return to first step of form, without clearing the form](https://github.com/GSA/px-benefit-finder/issues/1473)	https://github.com/GSA/px-benefit-finder/issues/1473
- allow users to navigate history through the native browser button
- remove the need for "back" links in the ui
- etc.

Acceptance Criteria

- virtual routes include, `/<form-step-heading`, `/verify-selections`, `/results`, `/results/not-eligible`
- handles `shared` token and its associated selection params
- when integrated, nginx will handle redirects for unkown child paths to life events, `/<life-event/**/*`, ie. `/death/unknown-path`
- current functionality is expected to work in the same or improved manner

**Comment by fongcindy** [comment]
I QA'ed #1473 , nav history through browser back, removal of "back" link, they are all working properly on my end. LGTM

**Comment by nickpistone** [comment]
Tested the regular flow and tracking looks normal as expected.
