### ISSUE TITLE
Disability & State benefits sync with Teri and Jemi

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1851]
### Description

Review work that Teri and Jemi have done and will be doing here.

### User Story

As a content strategist on benefit finder, I need to collaborate with Teri and Jemi, to improve the disability and state benefits experience on BF

### Acceptance Criteria

- [x] Have initial sync
- [x] See if there are any immediate changes to make
- [x] Come up with a plan for the coming sprints

**Comment by fongcindy** [comment]
@diegocob do you plan to work on this during sprint 44? Any updates on this?

**Comment by diegocob** [comment]
Added most of the changes to the upcoming changes in Oct. Will continue working with Teri and Jemi on state benefits and how to add benefits and resources to the disability page.
