### ISSUE TITLE
Remove all `cy.wait` values in pipeline

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1863]
### Description

let's opt over to `checks` rather than arbitrary times on cypress async tasks

ie. get by update in DOM 

`cy.get([data-testid="dom-ready"])` 

### Acceptance Criteria

- [ ] no `cy.wait` used in testst

**Comment by nehemiah-abuga** [comment]
This is ready for review https://github.com/GSA/px-benefit-finder/pull/1965
