### ISSUE TITLE
Mobile Screens | Form Screens

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#1864]
### Description

We will need to capture the redesign work for the mobile screens. This ticket captures the form application screens section, this is what we currently see on mobile:

![image](https://github.com/user-attachments/assets/f66d6cdb-bfad-426b-bee4-5f5b021d193e)
![image](https://github.com/user-attachments/assets/4eedeef3-b7bc-47a7-a461-e2dcac4b66f2)
![image](https://github.com/user-attachments/assets/8ba0a1b4-b45f-4af6-9df0-1783e0ac3ae1)

Related: #1837

**Comment by ErnestoFernandezAlvarez** [comment]
Note! Thank you! @fongcindy

**Comment by ErnestoFernandezAlvarez** [comment]
Next steps will be to:

- design these around the new margins
- apply type scale
- lay them them out on wireframes to check they are accurate and the space is utilized well

**I also realized that the error messages screens look a bit too cluttered on mobile as well, those will need a design as well :)**

**Comment by ErnestoFernandezAlvarez** [comment]
Hello @fongcindy 
Adding screenshot for tracking purposes.
Currently waiting to confirm radio button sizing for mobile in order to adjust this from screen.
<img width="337" alt="Screenshot 2024-10-18 at 3 15 56 PM" src="https://github.com/user-attachments/assets/36f644a6-c88a-43aa-b50c-5b97b821873a">

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy 
Uploading my progress for the mobile screen design.
Here is the [figma file](https://www.figma.com/design/3qui91uX0iE4YMNrnx4gzK/ReDesign-Benefit-Finder?node-id=16-2035&t=7gS2X1qdRC2kB6yt-1) as well :)

![Image](https://github.com/user-attachments/assets/6b5bd0e3-c6d4-43ae-8cca-2c43806569a2)

**Comment by ErnestoFernandezAlvarez** [comment]
![Image](https://github.com/user-attachments/assets/c601ac8e-166d-443f-ada5-c8e02dcbc1b9)

**Comment by fongcindy** [comment]
@erniedeeb @Ndoyle118 
Note: Ernesto removed the 'open all' button from mobile because the client didn't want it and also based on the analytics report that showed users not clicking on it.
The main reason is to un clutter the screen and save on scrolling space for mobile
Also, the back links have been removed from the form (client routing #1831)

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy thanks for adding the notes Cindy!
Once I have feedback from Maria, I will add a recap here as well.
@erniedeeb please feel free to leave any comments on the Figma file as well.
Thank you!

**Comment by fongcindy** [comment]
Maria has reviewed and approved the mobile screen designs, @scottqueen-bixal, we are ready to hand this off to you

@EnriqueOrt-GSA for viz

**Comment by ErnestoFernandezAlvarez** [comment]
hello @EnriqueOrt-GSA @scottqueen-bixal 
I'm closing this ticket as completed. Please let me know if you have any questions about the design
https://www.figma.com/design/3qui91uX0iE4YMNrnx4gzK/ReDesign-Benefit-Finder?node-id=16-2035&t=g0ViwelzRI7gUwxV-1

![Image](https://github.com/user-attachments/assets/6e02e88d-dd21-4635-b107-2f09182285b5)
