### ISSUE TITLE
Results modal CTAs off center

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1893]
### What's expected

The CTAs in the results modal in desktop seems off centered.
![Image](https://github.com/user-attachments/assets/b7578059-7640-404f-b621-1036e699a5c1)

### What happened

When I reach the Review your selections or Get your results, the CTA's seem off. 

### How to replicate

Go to any life event, answer required questions and select next. View the results modal.

**Comment by scottqueen-bixal** [comment]
please review current backlog of bugs before creating new ones, closing in favor of https://github.com/orgs/GSA/projects/48/views/22?pane=issue&itemId=84247897&issue=GSA%7Cpx-benefit-finder%7C1891
