### ISSUE TITLE
Spanish "back" button is in English

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1900]
### What's expected

The Spanish back button in the BF should be `Volver` but in the question sections it's in English - `Back`.

### What happened

When starting to answer the Spanish BF forms the back button is in English.
![Image](https://github.com/user-attachments/assets/efcab133-2bce-42e4-8fdd-cae1c0947c33)

### How to replicate

Go to any BF page in ES, ex: https://www.usa.gov/es/buscador-beneficios/discapacidad > Click Start > the back button should be in Spanish like in the results section. 
![Image](https://github.com/user-attachments/assets/eb6cda13-b3d6-41ef-a369-58e4a258356e)

**Comment by diegocob** [comment]
Tagging you on this one Scott, since I don't think it's in the locales section. Glad to go in another folder and start the commit process if you point me in what folder it's in.

**Comment by scottqueen-bixal** [comment]
I don't think this is going to be an issue much longer. When we release the client router in v0.8 this "back" button will no longer be on UI.

**Comment by diegocob** [comment]
Ok, will close this ticket out then.
