### ISSUE TITLE
QA | Content v0.8.0 beta.1

### ISSUE THREAD

**Issue by EnriqueOrt-GSA** [GSA/px-benefit-finder#1911]
### Domain

other

### Related Issue(s)

[NEW FEATURE | Return to first step of form, without clearing the form](https://github.com/GSA/px-benefit-finder/issues/1473)	https://github.com/GSA/px-benefit-finder/issues/1473

[1710 content workflow](https://github.com/GSA/px-benefit-finder/pull/1842)	https://github.com/GSA/px-benefit-finder/pull/1842

### Description

Content QA - Please review and confirm the tickets listed above - **you should review and work on [Main](https://bf-cms-main.bxdev.net/benefit-finder/death)** 

Due date: 11/04/2024 or as soon as available

**Comment by diegocob** [comment]
Working on these.

**Comment by diegocob** [comment]
Completed checking these two on Main. Just left a comment for Master @gchi25 on #1842.

**Comment by diegocob** [comment]
Work complete and we can close the ticket off. @gchi25, responded all is well.
