### ISSUE TITLE
QA | Accessibility v0.8.0 beta.1

### ISSUE THREAD

**Issue by EnriqueOrt-GSA** [GSA/px-benefit-finder#1914]
### Domain

a11y

### Related Issue(s)

[NEW FEATURE | client side routing in embedded applications](https://github.com/GSA/px-benefit-finder/issues/1831)	https://github.com/GSA/px-benefit-finder/issues/1831

### Description

A11y QA - Please review and confirm new feature for client side routing does not affect accessibility in any negative way or cause any type of regression - **you should review and work on [Main](https://bf-cms-main.bxdev.net/benefit-finder/death)** 

Due date: 11/04/2024 or as soon as available

**Comment by fongcindy** [comment]
@angelina-smith Friendly reminder this is due Monday 11/4! Please let Enrique know if you experience any issues accessing the env and if there any issues you see on your end. Thank you!

**Comment by angelina-smith** [comment]
Everything looks and sounds good on NVDA and JAWS
