### ISSUE TITLE
Remove instances of "Bears" in Benefit Finder module

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#208]
Remove instances of “Bears” in Benefit Finder module, 
Benefit Finder Module, its types, entities, menu items, etc - should not contain the usage of “bears”.

Currently "bears" term is used instead of "Benefit Finder", should be corrected to only use "Benefit Finder.

To replicate: Navigate menu, search modules view for “bears”

See where this is still found:

![Image](https://user-images.githubusercontent.com/128498116/266441814-05018cf3-12e9-43b0-b293-63d53f20d740.png)

![Image](https://user-images.githubusercontent.com/128498116/266441762-aadec4b7-1b22-4f45-b507-d16acae8910b.png)

![Image](https://user-images.githubusercontent.com/128498116/266441712-e5cacca8-a2e6-45e3-b144-f2137331d3e8.png)

**Comment by gchi25** [comment]
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/37e91983-84f2-4122-98e4-91b34b0b4525)



![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/f67ffcd3-d3dc-49b4-8656-f44722179f9c)

**Comment by scottqueen-bixal** [comment]
closing as completed
