### ISSUE TITLE
Remove unnecessary "Bears" block in module

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#209]
"Bears" block is still visible in module,
Benefit Finder is now using a page template, remove the custom block if unnecessary. 

Current custom block still present in code and configuration. 

![Image](https://user-images.githubusercontent.com/128498116/266441000-1852f500-30a7-489f-b600-ed159dfafeeb.png)

**Comment by scottqueen-bixal** [comment]
closing as completed
