### ISSUE TITLE
URL Correction

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#210]
URL is incorrect, the path should use best practice and include the preferred slugs. 
Currently the URL includes "bears" and underscores. 

We are moving towards "benefit finder" instead of "bears".

![Image](https://user-images.githubusercontent.com/128498116/266439562-f02168a4-1488-4288-8918-4dd4934c1ad3.png)

**Comment by scottqueen-bixal** [comment]
closing as completed
