### ISSUE TITLE
Create script to use awscli commands against s3 in cloud.gov

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/px-benefit-finder#254]
### Description

Create a script to be able to authenticate to use the awscli commands against s3 in cloud.gov for drupal s3/file usage. 

Referencing ticket:
[Set up drupal public file system to use s3/files#346](https://github.com/GSA/px-benefit-finder/issues/308)

**Comment by scottqueen-bixal** [comment]
closing as completed
