### ISSUE TITLE
Life Event "Death" to "Death Benefit" Page Title Change

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#257]
Currently our life event page tab title shows "Death | USAGov", this can potentially trigger users. 

![Image](https://user-images.githubusercontent.com/128498116/264417284-2c43e22a-f6ee-4876-8cac-150e3865750c.png)

Consider changing the standard appendage to "Death Benefits", slug can remain benefits, /retirement, /disability because it does not stand out as much.

**Comment by diegocob** [comment]
This was fixed.
