### ISSUE TITLE
redirect from v1 pages to V2 path during/after integration

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/px-benefit-finder#26]
### Description

Investigate how - if possible - to redirect v1 pages domains to v2 USAGov paths

This ticket should be resolved after [redirect from v1 pages to V2 path during/after integration#26](https://github.com/GSA/px-benefit-finder/issues/26) is unblocked and completed.

**Comment by FatmaBakir** [comment]
Response from pages support team:

> You can create a client side redirect from https://benefits-tool.usa.gov/death-of-a-loved-one to [usa.gov/some-path](http://usa.gov/some-path) the similarly the way you are currently redirecting https://benefits-tool.usa.gov/ to  https://benefits-tool.usa.gov/death-of-a-loved-one and you can deploy the site with the client side redirect using the Pages platform. Downsides of a client side redirects are they are not optimal for SEO and longer load times for users that go to https://benefits-tool.usa.gov/death-of-a-loved-one.
>  
> With [cloud.gov](http://cloud.gov/) Platform, you could deploy your own redirect app to serve as the redirect server using the [NGINX buildback](https://docs.cloudfoundry.org/buildpacks/nginx/index.html) and set the redirect HTTP code to 301 or 302 to improve SEO and the user experience when browsing to https://benefits-tool.usa.gov/death-of-a-loved-one. Once the redirecting app is ready in [cloud.gov](http://cloud.gov/) Platform, we will deprovision your Pages custom domain for [https://benefits-tool.usa.gov](https://benefits-tool.usa.gov/death-of-a-loved-one) and then you could launch you own custom domain in [cloud.gov](http://cloud.gov/) Platform point that url to you new redirect app.

**Comment by FatmaBakir** [comment]
@scottqueen-bixal Based on the email and slack communications with the Pages team, the way to implement a redirect from https://benefits-tool.usa.gov/death-of-a-loved-one/? to `usa.gov/benefit-finder-path` is the below:

1. deploy a lightweight redirect app to cloud.gov to handle the redirects; configure the redirects
2. Schedule with pages team to tear down the old domain


![Image](https://github.com/GSA/px-benefit-finder/assets/81575505/c19e5088-02af-4dce-a417-6dced7c5f1b9)

3. Coordinate with USAGov team to relaunch the same domain and configure it to point to our redirect app


![Image](https://github.com/GSA/px-benefit-finder/assets/81575505/05cf728e-099a-4353-9ad7-6e7ba46582fd)

**Comment by scottqueen-bixal** [comment]
need conversation with Tech folks usagov

**Comment by scottqueen-bixal** [comment]
recommended approach;

12/5
establish redirects config on usagov on production deployment

12/6
deprovision pages
provision benefits-too.usa.gov on usagov DNS

Let's go through Isabel with this request and coordiantion, @FatmaBakir will lead from Benefit Finder side

**Comment by FatmaBakir** [comment]
Started the conversation with Isabel.

**Comment by FatmaBakir** [comment]
This is still in progress as it's in Isabel's corner for the moment. She will check with the team and get back to us.

**Comment by FatmaBakir** [comment]
The conversation is still in progress. The items are below as of now as per USAGov DevOps Engineer's notes:
1. USAGov is migrating their DNS entries from GSA IT's DNS servers to a TTS-managed system.
2. Still needs to be confirmed, but Amy is expecting this migration to be completed early January.
3. So, Amy is suggesting that to add the benefits-tool domains to the TTS-managed system ahead of their migration.

**Comment by FatmaBakir** [comment]
**UPDATE:** 

Amy has just said 

> "I talked to Russell. He thinks we should get the records set up through GSA IT. I'm going to pass this back to 
> [@Isabel Laurenceau (she/her)] to coordinate with Russell. Basically he makes a request which goes through a few people for approval. The request does need to state when you want the switchover to happen, so if the 12/20 date is firm you already have that. Once it's been approved, we do communicate with GSA IT and as I recall they ask for confirmation, so I don't think the date is set in stone"

**Comment by FatmaBakir** [comment]
@erniedeeb has said that he "doesn't want to redirect any traffic until ~second week of Jan". This latest information has been communicated to Isabel and Amy. So, this is bringing us back to Amy's initial approach which is creating the DNS entries after the migration of DNS entries from GSA IT to TTS-managed system.

**Comment by scottqueen-bixal** [comment]
> 2. usagov - needs to set up redirects on nginx config 301 redirect from benefits-tool.usa.gov to usa.gov/benefit-finder. (https://docs.google.com/spreadsheets/d/1IDivDsQPVZ2XVPFpeG1WJEEupVYVUtjn7lNidjsZh1A/edit#gid=0)

@fongcindy verified and approved these mappings

**Comment by scottqueen-bixal** [comment]
update:

Amy has informed us that the server config to catch the traffic will be on USAGov prod 1/23.
We have a meeting set with pages on 1/25
We would like DNS changed over on a Friday, making 1/26 first date
