### ISSUE TITLE
Finalize content workflow process

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#267]
We have reviewed content workflow and moderation. 
Review Content Requirements and Determine LOE GSA/px-benefit-finder#402 

Implement Benefit Finder content workflow.
Finalize Benefit Finder content workflow process.
- Assign benefits content editor the content management roles
- Add benefits content into existing content workflow
- Work out  benefits taxonomy management method

**Comment by diegocob** [comment]
Closing this for now.
