### ISSUE TITLE
"Before you Start" text on Intro Page

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#33]
### Description

There is a typo in the "Before you Start" text in [DOLO's ES intro page.](<img width="320" alt="image" src="https://github.com/GSA/px-benefit-finder/assets/125094772/aca33f59-3692-41de-9a26-d2fd36f782a4">) 

It should read "Antes de empeza**r**". Need to add an "r" at the end. Currently reads "Antes de empeza"

<img width="220" alt="image" src="https://github.com/GSA/px-benefit-finder/assets/125094772/c66fb796-4959-4a52-aefe-e02777b38873">

For some reason the "Antes de empezar" in ES or "Before you start" in EN does not show up on desktop mode and hadn't seen it.

<img width="320" alt="image" src="https://github.com/GSA/px-benefit-finder/assets/125094772/df9bcb42-a24d-4d19-a763-28063e9c9516">

### User Story

As a ES-speaking user I should read all instructions in desktop and mobile without typos.

**Comment by diegocob** [comment]
@scottqueen-bixal, could you please take a look at this?

**Comment by fongcindy** [comment]
Hi Diego, thanks for flagging this! Since we are in a code + content freeze, Scott will probably address this post MVP

**Comment by scottqueen-bixal** [comment]
This has been updated


![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/4a1ffe9b-c045-4eea-8c0c-96e0a9e35188)
