### ISSUE TITLE
Eligible non-citizen info icon

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#376]
Add an info icon or more info next to the question in all the pages about citizenship and what "eligible non-citizen" means.

![Image](https://user-images.githubusercontent.com/125094772/256341323-5790c7b5-ebd8-471c-be57-744354e00d07.png)

**Comment by fongcindy** [comment]
@diegocob, this is an older ticket, is this something you were able to address by now? If not, this seems quick to resolve

@EnriqueOrt for viz

**Comment by diegocob** [comment]
We could resolve it fairly quickly. Many agencies use different definitions for this and it gets long fast. For example it means something for FAFSA for student aid than for SSA, which also adds that non-citizens should have worked 40 credits or 10 years. 

I suggest either not writing anything or adding a small hint to the question:
The definition of non-citizen may vary per agency and could include legal permanent residents, conditional permanent residents, asylees, refugees, or non-citizens whose deportation is being withheld.

It still sounds kind of technical compared to the text we have in the rest of the form. Thoughts?

**Comment by fongcindy** [comment]
Oh wow ok, I see. Looks like it would be easier to just **not write anything** instead of trying to define it for certain agencies.

**Comment by diegocob** [comment]
Sg, will keep as is and close this ticket.
