### ISSUE TITLE
Review Content Requirements and Determine LOE

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#402]
### Description

based on this document https://docs.google.com/spreadsheets/d/1c_CExar92Gt2EhdllinBC9kyohRpKVgsATR4l8b9E_s/edit#gid=89501122

determine if these requirements align with the current USA.gov content moderation workflow, user roles, etc.

If there are differences, please outline those and make a simple LOE estimate so that we can have a conversation with Content and Product to make a decision for moving forward.

**Comment by diegocob** [comment]
Think it's safe to close this.
