### ISSUE TITLE
Set up GTM on Storybook

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#406]
Add GTM snippet to storybook so that Nick can test out different ways of tracking the components before they go live.

Nick needs to set up the right container/workspace for testing and then share the snippet.

**Comment by nickpistone** [comment]
Update on this: I'm meeting with David today, but the plan is to use the USAGov GTM container ID that is inherited on the BF tool. We won't need anything else added on Storybook. And then we will use Zones to link our unique container to the main container and have it fire on our pages. We'll test that with a sandbox "USAGov" header container. I know I'm repeating some things here, but I wanted to sum it up more clearly in one place. I will have more on this later today.

**Comment by scottqueen-bixal** [comment]
closing as stale
