### ISSUE TITLE
Request Roles for usagov admin cms

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#43]
**Create Roles for the following people during Integration**
Gene Chi
Scott Queen
Diego Cobb
Cindy Fong
Ernie Deb

**11/28/23 Adding Nehemiah Abuga to this list

**Comment by scottqueen-bixal** [comment]
@EnriqueOrt  

For the first two stages of integration 11/27(dev) and 11/28(stage) it will be good to have user login access through VDI for @gchi25. This will allow him to make the content implementations rather than having to walk Isabella through things.

2 options:

1. Pull Roles in from Prod Database. If USAGov has roles in prod database before we start these items, then when we update the db on those env the roles will already be available
2. Temp Establish Role for Gene in early stages of integration (dev/stage)

I'll ping Isabella on this to get the conversation started...

**Comment by EnriqueOrt** [comment]
As of 11/21/23, Isabel requested email addresses for user access and confirmed Russell and Amy acknowledged the request. Will provide more information as soon as it is available.

**Comment by EnriqueOrt** [comment]
**Roles for Gene Chi, Scott Queen, Diego Cobb, Cindy Fong, and Ernie Deeb are confirmed to be ready as of 11/28/23 -** 

We added a role request for Nehemiah Abuga - will update once this role is created and ready to go.

**Comment by scottqueen-bixal** [comment]
closing as complete
