### ISSUE TITLE
Edit Armed Forces in DOLO/Disability/Retirement LE Forms

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#44]
For questions and benefit description change served in the military to "Armed forces"

**Comment by fongcindy** [comment]
@diegocob, can confirm if we can archive/delete this ticket? Don't we think plan to change this text

**Comment by diegocob** [comment]
This was update on the questions. I think this is part of a broader ticket that requires updating the criteria labels. Will close this one out.
