### ISSUE TITLE
Adding "in English"

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#50]
### Description

"Is in English” text to apply for benefits in the benefits accordions of the results page in the Spanish form is not showing up. 

Some benefits that have a link on the “How to apply button” that leads to an English page should say “(en inglés)” so Spanish speaking users can know they will be navigating to an EN site. 

Can go to the results page of a [Spanish filled out form]([https://bears-waf.app.cloud.gov/es/benefit-finder/death?es_applicant_date_of_birth=%7B%22month%22%3A%223%22%2C%22day%22%3A%225%22%2C%22year%22%3A%221960%22%7D&es_applicant_relationship_to_the_deceased=C%C3%B3nyuge&es_applicant_marital_status=Viuda%2Fo&es_applicant_citizen_status=S%C3%AD&es_applicant_care_for_child=S%C3%AD&es_applicant_paid_funeral_expenses=S%C3%AD&es_deceased_date_of_death=%7B%22month%22%3A%221%22%2C%22day%22%3A%223%22%2C%22year%22%3A%222022%22%7D&es_deceased_death_location_is_US=S%C3%AD&es_deceased_paid_into_SS=S%C3%AD&es_deceased_public_safety_officer=No&es_deceased_miner=No&es_deceased_american_indian=No&es_deceased_died_of_COVID=S%C3%AD&es_deceased_served_in_active_military=No&shared=true'](https://bears-waf.app.cloud.gov/es/benefit-finder/death?es_applicant_date_of_birth=%7B%22month%22%3A%223%22%2C%22day%22%3A%225%22%2C%22year%22%3A%221960%22%7D&es_applicant_relationship_to_the_deceased=C%C3%B3nyuge&es_applicant_marital_status=Viuda%2Fo&es_applicant_citizen_status=S%C3%AD&es_applicant_care_for_child=S%C3%AD&es_applicant_paid_funeral_expenses=S%C3%AD&es_deceased_date_of_death=%7B%22month%22%3A%221%22%2C%22day%22%3A%223%22%2C%22year%22%3A%222022%22%7D&es_deceased_death_location_is_US=S%C3%AD&es_deceased_paid_into_SS=S%C3%AD&es_deceased_public_safety_officer=No&es_deceased_miner=No&es_deceased_american_indian=No&es_deceased_died_of_COVID=S%C3%AD&es_deceased_served_in_active_military=No&shared=true%27)) and for example the benefit "Beneficios para padres sobrevivientes con hijos" leads to a page in English and the button in the accordion should read "(en inglés)" at the end.

### User Story

Spanish speaker users of the ES form should know if they are navigating to a site in English.

**Comment by diegocob** [comment]
Is this something that will be post-mvp launch?

**Comment by scottqueen-bixal** [comment]
coordinate with @fongcindy to align these changes in post v2beta0.1.0 work

**Comment by fongcindy** [comment]
Hi Diego, this will be a post-mvp launch item, let's backlog this and make we will figure out when will be the best time to incorporate this change (after the code + content freeze).

**Comment by scottqueen-bixal** [comment]
@fongcindy We can add this to next sprint for investigation and scoping

**Comment by EnriqueOrt** [comment]
Information needed is available, can be added to first Sprint of Feb for qtrly release - @fongcindy

**Comment by scottqueen-bixal** [comment]
I think the comment above is misleading. 

- We have the key in the data object that gets returned from the generated content.
- this key is only a Boolean value

```JSON
"SourceIsEnglish": "TRUE",
```
we still need links to the 1. design

I have the content as `(en inglés)` based on description in this ticket.

Seems like a simple implementation, but I don't want to make any assumptions.

CC: @diegocob @ErnestoFernandezAlvarez

**Comment by diegocob** [comment]
V1 just had `(en inglés)` added at the end of the CTA text. 

@ErnestoFernandezAlvarez, I looked at the Figma files but didn't find it included in the accordion designs for v2. Would that be the same? It would add quite a bit of text for the longer button that will soon have the benefit's name (not only the agency name as it is currently).

**Comment by scottqueen-bixal** [comment]
just moving to blocked until final design decision is made.

**Comment by ErnestoFernandezAlvarez** [comment]
Hi @Luis Diego Cob - QQBC-C ***@***.***> @Cindy Fong - QQBC-C
***@***.***> I am not sure what the ticket is calling out. Can we
please discuss this at the UX Check In?
thank you:)

**Comment by fongcindy** [comment]
@diegocob When you return, can you include a screenshot? 
@ErnestoFernandezAlvarez yes let's chat about this tomorrow with Diego during the UX check in

**Comment by ErnestoFernandezAlvarez** [comment]
Sure thing!

**Comment by diegocob** [comment]
Hi @ErnestoFernandezAlvarez,
Here is a screenshot. This is the text that tells users of the spanish forms that they will click a how to apply link that will take them to an English site:
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/686a4be3-8582-47dc-9829-fcee07844466)

**Comment by diegocob** [comment]
@ErnestoFernandezAlvarez, to your point about how many links go to Spanish websites out of 66 benefits:
25 (~40%) in Spanish
41 (~60%) in English

I think this feature is a nice to have. It does add 11 characters to the already long button.

**Comment by ErnestoFernandezAlvarez** [comment]
Thanks! @Luis Diego Cob - QQBC-C ***@***.***>
@Cindy Fong - QQBC-C ***@***.***> Does Scott need a design file for
this? We don't have an updated style guide in Spanish.

**Comment by ErnestoFernandezAlvarez** [comment]
Thanks for sharing @Luis Diego Cob - QQBC-C ***@***.***>
I think when the users are navigating sites in Spanish and they are
directed to external sites most likely those would be in English-
unfortunately not every site is bilingual.
I think we could add "en Inglés", however I just don't know whether any
applications might be offered in Spanish as well.
@Cindy Fong - QQBC-C ***@***.***> Could we discuss this with the UX
team and Ernie?

**Comment by fongcindy** [comment]
@ErnestoFernandezAlvarez Yes, since this is a new content change, I've included Ernie to review and provide his thoughts on this.

**Comment by erniedeeb** [comment]
I support the idea of adding the call out and putting it on the button is in line with USAGov's expectations. LGTM

**Comment by fongcindy** [comment]
@scottqueen-bixal can you proceed with adding "in English" (en inglés) text in the benefits accordions of the results page in the Spanish form? We've decided to make this content change. Thank you!

**Comment by ErnestoFernandez1970** [comment]
@fongcindy As we go into the next version of the design, I will incorporate this change to the Spanish Accordions.

**Comment by fongcindy** [comment]
@ErnestoFernandezAlvarez yes we will have the 'En Inglés' call out as a default for all Spanish accordions in the results page. 

Next step: Ernesto to create a simple design showing this change

**Comment by diegocob** [comment]
My understanding was that the "en inglés" call out will only be for the accordions listed to have the "Is in English" checked in the CMS, not all Spanish accordions. @scottqueen-bixal could you please confirm this?

> @ErnestoFernandezAlvarez yes we will have the 'En Inglés' call out as a default for all Spanish accordions in the results page.
> 
> Next step: Ernesto to create a simple design showing this change

**Comment by ErnestoFernandezAlvarez** [comment]
@diegocob I think "En Ingles" will show for all Spanish accordions.

**Comment by erniedeeb** [comment]
Several agencies support Spanish language versions of their content: FEMA, SSA, etc. We should not be indicating en Ingles for any benefits that lead to a page in Spanish.

**Comment by diegocob** [comment]
That's what I understood. Wanted to double-check.
