### ISSUE TITLE
Review V2 Mobile Spanish design

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#514]
Ernesto's notes: 

Sharing the V2 Mobile Spanish design [LINK](https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=1198%3A15317&t=OqFTroglAvZuzcq8-1)
Figma: ESPAÑOL V2 MOBILE page

Beyond the language, this version implements the changes that we have discussed during the last 4 - 5 weeks and it is very close to what we tested.

Notes:

- Parent/Child interaction, reduced the Form to 2 screens (previous form had 3 screens)

- Eliminated buttons from the section “Sharing and Printing”

- Changed to Radio Buttons answer Yes or No questions, for a more guided flow and to narrow results

- This version reflects a lot of the language reductions and changes implemented in the English version. And I am sure Diego will refine the language further!

- [@Amy Cole (USWDS, Vote.gov, USA.gov, Contractor, AR)](https://gsa-tts.slack.com/team/U04EEPQCMCP) I tried to implement all the accessibility recommendations so far, however we should align on the following:

1. Accordions CTA Buttons, currently we have a fully descriptive text on these, so they can be read by screen readers. Making sure we still want these.
2. Landing page: We have listed 3 important points in the “What you need to know” section. I’d like to make sure if these are final to keep at this point. Please refer to the English Flow for this (I only translated them)

**Comment by diegocob** [comment]
Believe this was finished a while ago. Closing it.
