### ISSUE TITLE
Benefit acceptable values don't match criteria

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#573]
### What's expected

Life Event: https://benefit-finder-waf-main.app.cloud.gov/benefit-finder/death

Criteria values are exact string values for both criteria option values and for benefit acceptable values

### What happened

This is the acceptable value that we see in some benefits

```JSON
{
  "benefit": {
    "title": "Veterans burial allowance",
    "summary": "<p>Assistance with burial, funeral, and transportation costs of a deceased veteran.</p>\r\n",
    "SourceLink": "https://www.va.gov/burials-memorials/veterans-burial-allowance/",
    "SourceIsEnglish": "TRUE",
    "agency": {
      "title": "Veterans Affairs Department (VA)",
      "summary": "<p>Provides a wide range of benefits in support of veterans, service members, and their families.</p>\r\n",
      "lede": ""
    },
    "tags": [
      "Death of a loved one"
    ],
    "lifeEvents": [
      "Death"
    ],
    "eligibility": [
      ...
      {
        "criteriaKey": "deceased_service_status",
        "label": "The service status of the deceased is: discharged for conditions other than dishonorable",
        "acceptableValues": [
          **"Discharged for conditions other than dishonorable"**
        ]
      },
     ...
    ]
  }
}
```
This is the option value that we see in some criteria

```JSON
[
  {
    "fieldsets": [
      {
        "fieldset": {
          "criteriaKey": "deceased_service_status",
          "legend": "What was the service status of the deceased?",
          "required": "FALSE",
          "hint": "",
          "inputs": [
            {
              "inputCriteria": {
                "id": "deceased_service_status",
                "type": "Select",
                "name": "deceased_service_status",
                "label": "What was the service status of the deceased?",
                "hasChild": "FALSE",
                "childDependencyOption": "",
                "values": [
                  {
                    "option": "Active-duty service member",
                    "value": "Active-duty service member"
                  },
                  {
                    "option": "Discharged under conditions other than dishonorable",
                    **"value": "Discharged under conditions other than dishonorable"**
                  },
                  {
                    "option": "Retired from the service",
                    "value": "Retired from the service"
                  },
                  {
                    "option": "Member of the National Guard/Reserves",
                    "value": "Member of the National Guard/Reserves"
                  }
                ]
              }
            }
          ],
          "children": []
        }
      }
    ]
  },
  ...
]
```

### How to replicate

<img width="1439" alt="Screenshot 2023-11-14 at 9 28 13 AM" src="https://github.com/GSA/px-benefit-finder/assets/37077057/6d7f547a-9282-4988-9255-6e79135c3358">

https://benefit-finder-waf-main.app.cloud.gov/benefit-finder/death?applicant_date_of_birth=%7B%22month%22%3A%220%22%2C%22day%22%3A%2222%22%2C%22year%22%3A%222022%22%7D&applicant_relationship_to_the_deceased=Spouse&applicant_marital_status=Married&deceased_date_of_death=%7B%22month%22%3A%220%22%2C%22day%22%3A%2222%22%2C%22year%22%3A%222022%22%7D&deceased_served_in_active_military=Yes&deceased_service_status=Discharged%20under%20conditions%20other%20than%20dishonorable&shared=true'

**Comment by diegocob** [comment]
Will update all the benefits with this criteria to "Discharged under conditions other than dishonorable"

**Comment by diegocob** [comment]
Reviewed all benefits on 3 life event forms and corrected the following:

1. [Survivors pension for child](https://benefit-finder-waf-main.app.cloud.gov/benefits/benefit/survivor_pension_child_VA)
2. [Survivors pension for child with disabilities](https://benefit-finder-waf-main.app.cloud.gov/benefits/benefit/survivor_pension_child_disabled_VA)
3. [Survivors pension for spouse](https://benefit-finder-waf-main.app.cloud.gov/benefits/benefit/survivor_pension_spouse_VA)
4. [Veterans burial allowance](https://benefit-finder-waf-main.app.cloud.gov/benefits/benefit/burial_allowance_VA)
