### ISSUE TITLE
generate content report for migration strategy

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#588]
benefit-finder-content-report

https://docs.google.com/spreadsheets/d/1o_RX510Cu3subRuzF--iDPAJYJCOrKV_MHlowvdVEWs/edit?usp=sharing

**Comment by scottqueen-bixal** [comment]
updated, new view in main here 

https://benefit-finder-waf-main.app.cloud.gov/admin/structure/views/view/benefit_finder_content
