### ISSUE TITLE
Content sync to USAGov Drupal 10

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#591]
Perform content sync from Benefit Finder Sandbox (Drupal 9) to Benefit Finder dev (Drupal 10).
Perform content sync from Benefit Finder Sandbox (Drupal 9) to Benefit Finder main (Drupal 10).
Make development environment from Benefit Finder Sandbox to Benefit Finder main.

**Comment by scottqueen-bixal** [comment]
closing as completed
