### ISSUE TITLE
configuration sync from Benefit Finder sandbox (Drupal 9) to Benefit Finder Dev and Main site (Drupal 10).

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#593]
Configuration sync from USAGov Drupal 9 local site to USAGov Drupal 10 in Benefit Finder Dev site.
Configuration sync from USAGov Drupal 9 local site to USAGov Drupal 10 in Benefit Finder Main site.

**Comment by scottqueen-bixal** [comment]
closing as completed
