### ISSUE TITLE
fix failing storybook components and add component tests

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/px-benefit-finder#594]
Cypress bundler doesn’t like importing “as” for the locale json. When we launch cypress with ‘npx cypress open’, webpack throws errors on the console when you save changes you are making on cypress tests.
This changes includes updates to de-structure the import and assign to a constant before passing into the args and thus fixes the webpack process completes without errors.
component tests for Benefit accordion group have will be added

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga can you please move this work to the current sprint and provide an update?

**Comment by scottqueen-bixal** [comment]
@scottqueen-bixal link to work in progress PRs were requested on NOV22, please update.
