### ISSUE TITLE
Review new Intro Page text

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#600]
### Description

Changed the text on the beginning of the [DOLO page.](https://benefit-finder-waf-main.app.cloud.gov/benefit-finder/death) It seemed like it needed to be more empathetic and clear in explaining the form's purpose. Also added the bolding.

@fongcindy and @erniedeeb, please have a look.

<img width="301" alt="image" src="https://github.com/GSA/px-benefit-finder/assets/125094772/0a338b1e-fe30-40ee-acc1-8e04b9306cf8">

**Comment by fongcindy** [comment]
Hi Diego, these changes look great. The first added sentence helps to make the intro page more empathetic and the second bolded section will hopefully clear up some confusion about our tool. 

Once Nick D completes the Spanish interviews, it would be interesting to see if this landing page could be tested.

**Comment by diegocob** [comment]
Yes! And see if there are any changes with the previous findings where people did not know what the purpose of the app was.

**Comment by diegocob** [comment]
Thanks, Cindy. Will wait to hear what @erniedeeb thinks before closing this.

**Comment by erniedeeb** [comment]
LGTM

**Comment by diegocob** [comment]
Closing this ticket. This was done a while ago. Working a new version after user testing sessions.
