### ISSUE TITLE
Watch Jacline’s prototype testing sessions with USWDS

### ISSUE THREAD

**Issue by amycole501** [GSA/px-benefit-finder#604]
they’re in Dovetail; ask Nick to watch them too

**Comment by angelina-smith** [comment]
@EnriqueOrt @amycole501 How do I change the status of the issue to "In Progress"? Not sure why I'm unable to edit anything in the issues

**Comment by amycole501** [comment]
I can't seem to edit it either
![image](https://github.com/GSA/px-benefit-finder/assets/117778073/b6c0989f-1cfe-4829-bd5a-81c4e4708032)

**Comment by Ndoyle118** [comment]
I met with Jacline yesterday and she shared some resources from USWDS testing with disabled users [here](https://bixal365-my.sharepoint.com/:w:/r/personal/jacline_contrino_bixal_com/Documents/USWDS/A11y%20Usability%20Testing%20Documentation%20to%20share%20with%20Bixal%20Colleagues.docx?d=wd238cd1788ad418b9ad48664c1e82ef1&csf=1&web=1&e=x9Nsh3)

I'm also planning to watch some of her sessions on Dovetail!
