### ISSUE TITLE
Test Module Code in USAGov Pipeline, Code Scanning

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#613]
Coordinate with USAGov to stage our code in the custom directory as a PR (Draft) to trigger any code scanning.

If there are issues, document here and flag.

**Comment by gchi25** [comment]
https://github.com/GSA/px-benefit-finder/issues/625
PHP Code Standard

**Comment by scottqueen-bixal** [comment]
closing as completed
