### ISSUE TITLE
Include PHP lint and code sniff in our pipeline

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#614]
USAGov has linting and code scanning for PHP set up in their pipeline, let's include this in ours so we can resolve issues before release integrations

**Comment by scottqueen-bixal** [comment]
review build here https://app.circleci.com/pipelines/github/usagov/usagov-2021/7215/workflows/9c6c3392-ce80-49f5-bb56-5e9b925aef8f/jobs/14903

**Comment by scottqueen-bixal** [comment]
coordinate with Gene to ensure our configuration aligns with USAGov

**Comment by FatmaBakir** [comment]
I am working on this one, trying to replicate USAGov code sniff and lint scanning.

**Comment by scottqueen-bixal** [comment]
closing as complete
