### ISSUE TITLE
autogenerated JSON hook when revision is reverted

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#62]
When a content editor reverts to another version the data needs to be regnerated

**Comment by scottqueen-bixal** [comment]
@gchi25 write out more details here, let's get a fix out

**Comment by scottqueen-bixal** [comment]
closing as completed

**Comment by scottqueen-bixal** [comment]
@gchi25 confirm and link code

**Comment by gchi25** [comment]
Test in Benefit Finder DEV site. The revert triggers the auto json files generation.
