### ISSUE TITLE
USAGov release local test

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#629]
https://docs.google.com/spreadsheets/d/1Lgk3HLpm6kIYUIdnkR9FitGA6Ft5Yjd67g6Dh6kg0MA/edit?usp=sharing

- run release process benefit finder
- share zip folder to usagov
- install locally
- enable module
- import partial configuration
- export config
- update code
- create PR in usagov

**Comment by scottqueen-bixal** [comment]
closing as completed
