### ISSUE TITLE
QA Current data issues

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#637]
disability
•	applicant_has_ss_number is of type “Select”. This has a “Yes” or “No” option. Shouldn’t the type be “Radio”?
•	applicant_has_ss_number is in disability but there is no equivalent is creteria key in es_disability
•	In applicant_served_in_active_military, “hasChild” is FALSE but children has values

es_disability
•	es_applicant_paid_into_SS is in es_ disability but there is no equivalent in disability

retirement
•	applicant_paid_into_SS is of type “Select”. This has a “Yes” or “No” option. Shouldn’t the type be “Radio”?
•	In applicant_served_in_active_military, “hasChild” is FALSE but children has values

**Comment by gchi25** [comment]
Disability

applicant_has_ss_number is of type “Select”. This has a “Yes” or “No” option. Shouldn’t the type be “Radio”?
https://benefit-finder-waf-main.app.cloud.gov/benefits/criteria/applicant_has_ss_number
Updated this to Radio.

applicant_has_ss_number is in disability but there is no equivalent is creteria key in es_disability
https://benefit-finder-waf-main.app.cloud.gov/benefits/criteria/applicant_has_ss_number
Need to create Spanish version.

In applicant_served_in_active_military, “hasChild” is FALSE but children has values
https://benefit-finder-waf-main.app.cloud.gov/benefits/criteria/deceased_served_in_active_military
Updated this with hasChild TRUE.

es_disability and disability
https://benefit-finder-waf-main.app.cloud.gov/benefit-finder/api/life-event/es_disability
It has "criteriaKey": "es_applicant_paid_into_SS".
https://benefit-finder-waf-main.app.cloud.gov/benefit-finder/api/life-event/disability
It has "criteriaKey": "applicant_has_ss_number".

Need to check MASTER data about this.

Retirement:

applicant_paid_into_SS is of type “Select”. This has a “Yes” or “No” option. Shouldn’t the type be “Radio”?
https://benefit-finder-waf-main.app.cloud.gov/benefits/criteria/applicant_paid_into_SS
Updated to Radio.
The Spanish version is Radio already.

In applicant_served_in_active_military, “hasChild” is FALSE but children has values
https://benefit-finder-waf-main.app.cloud.gov/benefits/criteria/deceased_served_in_active_military
Updated this with hasChild TRUE.

**Comment by diegocob** [comment]
I corrected the required questions on disability to match ES and EN.

Thanks for making the changes @gchi25 on the benefits, they look good. 

On the Has Social Security number, that criteria is not used in any form or question. I had created it in EN to keep it there. Added it in ES for consistency.

**Comment by gchi25** [comment]
>>For retirement applicant_date_of_birth should be mandatory
Updated life event form disability English and Spanish.
Made applicant_date_of_birth required.

**Comment by diegocob** [comment]
@nehemiah-abuga, this was resolved. Can I close this ticket?

**Comment by nehemiah-abuga** [comment]
> @nehemiah-abuga, this was resolved. Can I close this ticket?
@diegocob I am waiting for @gchi25 to share the pull request to test this.

@gchi25 - please share the PR so that I can validate the changes. We can then merge to main if everything looks good.

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga and @gchi25 please update this ticket and close if necessary

**Comment by diegocob** [comment]
I believe this was resolved a while ago. We could close this ticket.

**Comment by scottqueen-bixal** [comment]
agree, @diegocob closing as stale
