### ISSUE TITLE
DOB not reflecting exact input date

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#645]
### What's expected

Entered a DOB of 09/15/2007 but in the review section it said 09/14/2007. Missed by one date but not sure if it's doing it with other dates. Needs testing. 

On the disability finder ran the Minor w/disabilities scenario: https://benefit-finder-waf-main.app.cloud.gov/benefit-finder/disability?applicant_date_of_birth=%7B%22month%22%3A%228%22%2C%22day%22%3A%2215%22%2C%22year%22%3A%222007%22%7D&applicant_marital_status=Unmarried&applicant_citizen_status=Yes&applicant_paid_into_SS=Yes&applicant_income=Yes&applicant_american_indian=No&applicant_disability=Yes&applicant_ability_to_work=Yes&applicant_miner=No&applicant_child_spouse_SS=Yes&applicant_public_safety_officer=No&applicant_served_in_active_military=No&shared=true'

![image](https://github.com/GSA/px-benefit-finder/assets/125094772/b3feb243-01d0-4f9c-b93f-72e7469465eb)

![image](https://github.com/GSA/px-benefit-finder/assets/125094772/074c211b-2c51-4dd0-9bef-b2666390e1d0)

### What happened

Date not reflecting exact in the review section.

### How to replicate

Go to the scenario and check date entered with the reviewed date: https://benefit-finder-waf-main.app.cloud.gov/es/benefit-finder/disability?es_applicant_date_of_birth=%7B%22month%22%3A%228%22%2C%22day%22%3A%2215%22%2C%22year%22%3A%222007%22%7D&es_applicant_marital_status=No%20casada%2Fo&es_applicant_citizen_status=S%C3%AD&es_applicant_paid_into_SS=S%C3%AD&es_applicant_income=S%C3%AD&es_applicant_american_indian=No&es_applicant_disability=S%C3%AD&es_applicant_ability_to_work=S%C3%AD&es_applicant_miner=No&es_applicant_child_spouse_SS=S%C3%AD&es_applicant_public_safety_officer=No&es_applicant_served_in_active_military=No&shared=true'

**Comment by scottqueen-bixal** [comment]
looks like this is only a bug in translating object date to local long format ISO date, will need to resolve in next release.

**Comment by diegocob** [comment]
Sg, adding to the product backlog and setting a low priority status.

**Comment by scottqueen-bixal** [comment]
this is updated

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/ef1aa88b-c399-4ec0-81d1-318e51516ca9)
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/b6bd4731-8547-43e2-bdb4-3c7da15fc766)

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/8dfc996b-f5a9-48e7-98a5-fff473518a83)
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/481d9ba5-d989-4141-878e-c8ce6269f4a0)
