### ISSUE TITLE
Taking out "Critical info" from benefit summary

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#646]
### Description

Post MVP: Should we take out or edit the critical info that was put in SSA benefits "You only need one application to apply for all disability benefits offered by SSA." It seems like it doesn't add much to the summary as it is. Thoughts?

![image](https://github.com/GSA/px-benefit-finder/assets/125094772/3418085a-2362-4451-9bc3-7ee717e088c8)

**Comment by diegocob** [comment]
Seems like with some of the new user tests they might circle back and be edited somehow. Adding it to this sprint so we can decide how to edit it with the upcoming changes.

**Comment by fongcindy** [comment]
@diegocob I think we've addressed this? Can you confirm?

**Comment by diegocob** [comment]
Hi @fongcindy, I don't think it was addressed. We needed feedback from @erniedeeb to see if we could remove this. Some users complained that they didn't understand why it was being repeated across SSA benefits. Seemed more confusing than helpful.

**Comment by erniedeeb** [comment]
Sorry for the late reply. It doesn't add much, but it doesn't detract much either. Might be helpful to keep it there until we can figure out how else we might want to communicate that information, if at all.

**Comment by diegocob** [comment]
Thanks, @erniedeeb. Will keep it as it and close this ticket.
