### ISSUE TITLE
Revisit/Breakout QE Testing Plan

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#655]
https://docs.google.com/document/d/18GLSto3_CQigQ8RdNY-XuXjhO3Tmi3VsM4dy5g1_wpk/edit#heading=h.wfp81dh7rst

DOD:
Update to reflect BEARS removal
Provide update to TEAM on progress and accomplishments of testing plan to date in sprint checkpoint
Create individual tickets for e2e coverage ~80% component coverage in Component Library
Assign all individual tickets to sprint

**Comment by nehemiah-abuga** [comment]
Identified and component scenarios to be automated - 90 % complete
Working on documenting E2E features to automated - 20% complete
https://docs.google.com/document/d/1oy1QKz4zo6i5RA9aKuFtGU334ogmncGR/edit
