### ISSUE TITLE
Add a step to pipeline to create network policy

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/px-benefit-finder#665]
### Description

In the pipeline; after creating/deploying the app I can add another step to create the security group:
`cf add-network-policy benefit-finder-waf-dev benefit-finder-cms-dev -s benefit-finder-dev -o gsa-tts-usagov --protocol tcp --port 61443` The policy gets automatically deleted if the app gets deleted.

Here is a good resource from vote.gov project:
https://github.com/usagov/vote-gov-drupal/blob/dev/scripts/pipeline/cloud-gov-deploy.sh

**Comment by casey-rapnicki-bixal** [comment]
Added PR: https://github.com/GSA/px-benefit-finder/pull/903

**Comment by casey-rapnicki-bixal** [comment]
Deployment to dev was successful.
