### ISSUE TITLE
USAGov S3: do not export Draft JSON data file to static site

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#673]
### Description

The following is the code for Drupal to provide published and draft JSON data files for REACT to fetch data.
[page--benefit-finder-life-event.html.twig](https://github.com/usagov/usagov-2021/blob/2ace96beff261dc5e561868612368cf3e8da3316/web/modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_app/usagov_benefit_finder_page/templates/page--benefit-finder-life-event.html.twig#L121C1-L125C136
)

```
<div hidden><a href="{{ json_data_file_path }}" rel="noindex nofollow">"{{ json_data_file_path }}"</a></div>
  <div class="grid-container">
    {{ page.breadcrumb }}
  </div>
  <div id="benefit-finder" json-data-file-path="{{ json_data_file_path }}" draft-json-data-file-path="{{ draft_json_data_file_path }}">
```

The following is the corresponding HTML in a life event page.
https://www.usa.gov/benefit-finder/death
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/66989464-e68c-46d9-bac2-9e5959abf65e)

```
<div hidden="">
<a href="/s3/files/benefit-finder/api/life-event/death.json" rel="noindex nofollow">
"/s3/files/benefit-finder/api/life-event/death.json"</a>
</div>
<div id="benefit-finder" 
json-data-file-path="/s3/files/benefit-finder/api/life-event/death.json" 
draft-json-data-file-path="/s3/files/benefit-finder/api/draft/life-event/death.json">
```

We thought only published JSON data files exported to static site via HTML link.

But both published and draft JSON data files are exported to static site.
https://www.usa.gov/s3/files/benefit-finder/api/life-event/death.json
https://www.usa.gov/s3/files/benefit-finder/api/draft/life-event/death.json

The draft JSON data files are in following folder
`/s3/files/benefit-finder/api/draft/life-event/`

We would like draft JSON data files not exported to static site.

### User Story

As developer, we develop and generate draft JSON data files for content team to test their draft content in Benefit Finder tool running in draft mode. We would like these draft JSON data files not exported to static site.

### Acceptance Criteria
Benefit Finder Draft JSON data files not exported into static site

**Comment by scottqueen-bixal** [comment]
@gchi25 please work with USAGov to complete this work.

**Comment by scottqueen-bixal** [comment]
closing as completed

**Comment by akf** [comment]
@gchi25 I think there's a very simple fix for this.  usagov-2021's tome-sync.sh script includes a few lines to remove specific directories from the static files before copying them over: 
https://github.com/usagov/usagov-2021/blob/2ace96beff261dc5e561868612368cf3e8da3316/scripts/tome-sync.sh#L75

I'll make a Jira ticket for this one, given the part of the code it exists in.

**Comment by akf** [comment]
I put it on our current sprint as https://cm-jira.usa.gov/browse/USAGOV-1597 . You're welcome to pick up the ticket and make a PR if you like. Otherwise, I do expect someone will have time to make this change in the near future.

**Comment by gchi25** [comment]
I pick up the ticket and will make a PR.

**Comment by gchi25** [comment]
https://github.com/usagov/usagov-2021/pull/1617
Created PR to remove BF draft json files from static site export.

**Comment by gchi25** [comment]
Tested in USAGov DEV site. Worked as expected.
