### ISSUE TITLE
Do not export Benefit Finder content to static site except life event

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#674]
USAGov CMS only export life event to static site.
Do not export agency, criteria, benefit, life event form to static site.

**Comment by gchi25** [comment]
TOME static build does not export node without URL to static site.

**Comment by gchi25** [comment]
Confirmed TOME static build does not export node without URL to static site.
Will not add URL alias to Agency, Criteria, Benefit, Life Event Form in content migration.

**Comment by scottqueen-bixal** [comment]
closing as completed
