### ISSUE TITLE
URL Translation - Benefit Finder Integration

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#675]
Translated paths/URL - Due EOD 12/4/first thing 12/05
benefit-finder/death
benefit-finder/retirement
benefit-finder/disability

**Comment by EnriqueOrt** [comment]
Thanks @diegocob & @erniedeeb 

benefit-finder/es/muerte
benefit-finder/es/jubilacion
benefit-finder/es/discapacidad

Ernie will check with Maria to get final sign off. @scottqueen-bixal for vis

**Comment by erniedeeb** [comment]
/es/ will need to follow the domain for parity with usa.gov, which means /benefit-finder/ will likely need to be translated as well. We'd probably end up with URLS of:

usa.gov/es/buscador-de-beneficios/muerte
usa.gov/es/buscador-de-beneficios/jubilacion
usa.gov/es/buscador-de-beneficios/discapacidad

Will confirm with Maria and circle back.

**Comment by erniedeeb** [comment]
Confirmed the following paths with Maria and Shoshana:

http://usa.gov/es/buscador-beneficios
http://usa.gov/es/buscador-beneficios/muerte
http://usa.gov/es/buscador-beneficios/jubilacion
http://usa.gov/es/buscador-beneficios/discapacidad

Note the URL drops the `de` from the full Spanish translation of the tool name "buscador de beneficios"

**Comment by diegocob** [comment]
Love it.
