### ISSUE TITLE
Benefit Landing Page

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#676]
Benefit Finder Landing Page
https://docs.google.com/document/d/1tbpqNrMscDdIQXGIw5ek7TdAVYAz-uRfXvhgoCuRyMA/edit?usp=sharing

https://benefit-finder-waf-main.app.cloud.gov/benefit-finder
Benefit Landing Page - English

**Comment by diegocob** [comment]
This was done in the Google doc and I added it to the content data bank [Landing page tab](https://benefit-finder-waf-main.app.cloud.gov/benefit-finder).

@gchi25 is there anything else to do?
