### ISSUE TITLE
Add tag that denotes page as a translation of other language page

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#681]
it makes it a bit trickier to track the two versions of the page together in the data. But we don’t have many pages so it won’t be too tough to manually group them. I’ll think about other things we could do to associate them in the data as well.

perhaps we could make some kind of tag that denotes each page as a translation of [page path of other language page] and then I could use that tag to associate them. That would be good to have if we added additional translations

**Comment by nickpistone** [comment]
thanks for creating this Gene! I don't think it needs to be a priority right now, but it's good to capture for future refinements.

**Comment by scottqueen-bixal** [comment]
@nickpistone this description is a bit confusing, can you clarify a few things so @fongcindy and I can review.

1. What is the requirement in one sentence
2. What is the main value for the product

**Comment by nickpistone** [comment]
I didn't create this tag. But I believe Gene created it in response to the hreflang issue. #1032 I've followed up with David Kaufmann about this as well. It is not high urgency or high value. But it could potentially help our content be found more easily as it would help Google understand how our pages relate to each other.

**Comment by scottqueen-bixal** [comment]
needs better requirements and AC - my understanding from reading #1032 is that we don't control this. @gchi25 can you confirm this is an update we can make?

**Comment by nickpistone** [comment]
[GSA.gov Mail - Fwd_ \[JIRA\] Updates for USAGOV-1564_ Reinstitute self-reflexive link rel ahref meta tag in head.pdf](https://github.com/user-attachments/files/16364678/GSA.gov.Mail.-.Fwd_.JIRA.Updates.for.USAGOV-1564_.Reinstitute.self-reflexive.link.rel.ahref.meta.tag.in.head.pdf)

The hreflang issue was addressed on the USAGov side. So I don't think this ticket is needed anymore.
