### ISSUE TITLE
include temp link list to sub pages under /benefit-finder landing page

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#682]
While we wait for the fix to come up stream let's include a simple link list to the correct subpages for both en/es locales on /benefit-finder

**Comment by diegocob** [comment]
@erniedeeb is reaching out to Shoshana to check if she made any changes to the Spanish landing page list and links to life events in the main body of the page.

**Comment by erniedeeb** [comment]
We are clear to add that content to the Spanish page, let's just make sure that saving those changes doesn't cause that page to be made visible in menus and nav pages.

**Comment by gchi25** [comment]
Implemented temp solution with submenu links in Benefit Finder landing page of English and Spanish version.
#693

**Comment by diegocob** [comment]
This is complete.
