### ISSUE TITLE
Take Deque course on screen reader testing

### ISSUE THREAD

**Issue by amycole501** [GSA/px-benefit-finder#685]
JAWS has recently had a big update. Deque offers a course to stay abreast of the latest techniques in all screen readers and web browser combinations.

This ticket will be considered done once the course is completed and any adjustments to benefits finder testing protocols are updated as needed.
https://dequeuniversity.com/class/screenreaders/toc

**Comment by angelina-smith** [comment]
Completed course and added ideal QA testing protocol for Benefits tool in [Google document](https://docs.google.com/document/d/1YLwn3_N9XeeluZNerTojZTc71C1sDhNPDE2OrkU7GOE/edit). Did you want to review my additions under the A11y QA Testing section @amycole501 @fongcindy ?

**Comment by fongcindy** [comment]
Thanks for the updates Angelina, I took a look at the google doc and associated tickets. We can chat more about the A11y QA checks with Scott during the 508 Compliance Tracker sync on 1/4 :)
