### ISSUE TITLE
Benefit Finder life event title in browser tab

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#687]
Related ticket: https://github.com/GSA/usagov-benefits-eligibility/issues/1011

Update the Benefit Finder life event title in browser tab.

https://www.usa.gov/benefit-finder/death
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/f9863b69-3e8b-49a2-9a37-ceaa7e660a9c)

https://www.usa.gov/benefit-finder/retirement
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/34b197cd-d10c-4466-bb13-bcfd43514803)

https://www.usa.gov/benefit-finder/disability
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/3483f404-3790-4e79-a89c-a888bd9334ff)

https://www.usa.gov/es/buscador-beneficios/muerte
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/c35f6ab2-4ed0-472a-8bb7-cfd25cbca872)

https://www.usa.gov/es/buscador-beneficios/jubilacion
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/a45365e3-c8ee-44ee-a435-d561c4802783)

https://www.usa.gov/es/buscador-beneficios/discapacidad
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/93159b87-0290-4436-83d6-4c5c97f63513)

**Comment by nickpistone** [comment]
There are two issues here. One is changing the names to something more descriptive that can stand alone in search results and be read by a screen reader and easily understood. But the second issue is that the page title for DOLO is showing up sometimes as "Death" or "Muerte" in Google Analytics but showing up as DOLO and DOLO-ES in my browser tab. Is there a bug there causing two different page titles?

**Comment by gchi25** [comment]
Updated the page title of life events.

https://www.usa.gov/benefit-finder/death
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/a5cd1bc4-d754-40af-bd84-472917ce06d6)

https://www.usa.gov/benefit-finder/retirement
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/1d3455b7-5bb7-43c2-b012-b99265af4610)

https://www.usa.gov/benefit-finder/disability
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/7cde6841-b293-4086-a18b-7f4f7b1b4cbf)

https://www.usa.gov/es/buscador-beneficios/muerte
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/b0c8246f-f5e5-48be-8f4c-2a05ad96797b)

https://www.usa.gov/es/buscador-beneficios/jubilacion
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/1040a1ce-661f-400d-93e7-249246aa5d21)

https://www.usa.gov/es/buscador-beneficios/discapacidad
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/c8f37e9e-8edf-4a96-a5e6-8bba6c6e22f1)

**Comment by diegocob** [comment]
@nickpistone, are the two different names still coming up on GA on your end?

**Comment by nickpistone** [comment]
Looking at today, Dec. 8th, there is data for both versions of each page title ("DOLO" and "Benefit finder: death"). Since the data is tracked by day, I won't be able to verify until Monday that only one version is showing up. But it looks promising since most of the pageviews for today are going to the new versions that start with "Benefit finder:"

**Comment by diegocob** [comment]
@gchi25 have these changes been deployed or when are they expected to be seen live?

**Comment by nickpistone** [comment]
This looks good to me. I'm ready to move it to done. Not sure if anyone else needs to review first. @fongcindy @diegocob

**Comment by diegocob** [comment]
Lgtm2!

**Comment by fongcindy** [comment]
Just triple checked, also LGTM on my end, thanks for following up

**Comment by diegocob** [comment]
This was completed.
