### ISSUE TITLE
Adjust page titles to make them more descriptive and consistent

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#688]
### Description

[Benefit Finder page titles and URLs.xlsx](https://github.com/GSA/usagov-benefits-eligibility/files/13602025/Benefit.Finder.page.titles.and.URLs.xlsx)
See attached spreadsheet above for current page titles and URLs as of 12/7. Titles like "Death | USAGov" make it hard for users to understand what the page is about when they see it in search results. A more descriptive title like "Find federal benefits after losing a loved one" can help users understand the purpose of the page quickly when they see it out of the context of the rest of the site.

Page titles should be under 60 characters. Wide characters such as "W" take up more pixels and further limit the characters. Use this tool to preview title tags and see if they would be cut off. https://moz.com/learn/seo/title-tag
Technically the page title and the title tag/SEO title can be different. It's easier to keep them the same, though. But if the title tag gets cut off in search at the end, the page title will not get cut off in the browser window.

**Comment by amycole501** [comment]
Page titles are important to provide clarity for screen reader users. Currently DOLO is a page title which is an acronym unknown to almost everyone. Let me know if any a11y evaluation is needed.

**Comment by diegocob** [comment]
Spoke with @erniedeeb about making these changes to the page titles:

Death:
EN: Benefit finder: death
ES: Buscador beneficios: muerte

Disability: 
EN: Benefit finder: disability
ES: Buscador beneficios: discapacidad

Retirement:
EN: Benefit finder: retirement
ES: Buscador beneficios: jubilación

**Comment by nickpistone** [comment]
I'm still seeing a few events firing for ES - Death, ES - Disability, and ES - Retirement. It seems like the English page titles are good now. When I visit the Spanish pages, I see the new page titles in the browser tab. But in GA, I'm still seeing the old ones. I'll keep checking to see if that changes over time. But for now, I can't mark this as done yet.

**Comment by nickpistone** [comment]
In addition to the changes outlined above, I'd also like to propose taking it one step further with something like "Find federal benefits after losing a loved one" so that users have a clear sense of the purpose and scope of the page if they see it in search results outside of the context of the rest of the site. @diegocob

**Comment by diegocob** [comment]
@nickpistone, 
What do you think of these titles:
- Find federal benefits after the death of a loved one
- Find federal benefits for retirement
- Find federal benefits for disability

**Comment by diegocob** [comment]
Spanish titles:

- Encuentre beneficios tras la muerte de un ser querido 
- b) Encuentre beneficios del Gobierno por fallecimiento [to keep consistency with the wording on the other options writing "del Gobierno" but changing "muerte de un ser querido" for "fallecimiento" to keep it under 60 characters.
- Encuentre beneficios del Gobierno para su jubilación
- Encuentre beneficios del Gobierno por discapacidad

**Comment by diegocob** [comment]
@gchi25 and @nickpistone are these page titles only for Google analytics or will they also show up on the page tab like this:

![Image](https://github.com/GSA/px-benefit-finder/assets/125094772/0cf30b0b-371d-42ca-a5cf-8131b95e8f23)

**Comment by nickpistone** [comment]
@diegocob any page titles should be the same in Google Analytics and on the browser tab. I'm not sure why there's been inconsistency between what I've seen on my screen on the live page and the data in GA. But it could mean that not everyone is seeing the same page titles.

As of yesterday, I no longer see DOLO as a page title. The only one I still see is "Death | USAGov." Everything else is now "Benefit finder: ___" or "Buscador beneficios: ____"

**Comment by diegocob** [comment]
Thanks for the clarification, Nick. 

@gchi25, do you know if this was pushed to production?

**Comment by nickpistone** [comment]
Confirming now that as of Dec 15, I am no longer seeing DOLO or "Death" as a page title. @diegocob Diego I now pass this on to you for revising the title tags to make them more descriptive.

**Comment by diegocob** [comment]
Didn't we finalize these titles on this thread? @fongcindy, is there anything missing from my end?

**Comment by diegocob** [comment]
Closing this since it was completed.
