### ISSUE TITLE
block index of pages in salesforce

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#689]
Some of the pages were indexed in Salesforce which makes it available to contact center reps.
talk to Isabel about seeing how to exclude all our content from Salesforce

Sounds like http://usa.gov/benefits-finder and /buscador-beneficios are the only pages indexed in salesforce, fortunately

**Comment by gchi25** [comment]
There is no way to do that with our current salesforce installation

**Comment by scottqueen-bixal** [comment]
G. Scott Queen (USA.gov Contractor)
  [12:03 PM](https://gsa-tts.slack.com/archives/C066YUT55LH/p1702314215695179)
[@Isabel Laurenceau (she/her)](https://gsa-tts.slack.com/team/U03KTFL2SUW)
 - I am curious, once we switch to a navigation page type instead of the standard page type will the landing page still be indexed in Salesforce?

Isabel Laurenceau (she/her)
:aggretsuko-typing:  [12:04 PM](https://gsa-tts.slack.com/archives/C066YUT55LH/p1702314255554579)
No! We will make the switch over and request that salesforce remove the old data from that page

Isabel Laurenceau (she/her)
:aggretsuko-typing:  [12:04 PM](https://gsa-tts.slack.com/archives/C066YUT55LH/p1702314270365469)
And it won’t re-index since it’s a navigation page\\

@erniedeeb this looks like our assumption is correct, Isabel is going to work to get us off salesforce once the nav page is in place

**Comment by scottqueen-bixal** [comment]
closing as completed
