### ISSUE TITLE
Content Migration

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#701]
Content Inventory and Tracking Sheet
https://docs.google.com/spreadsheets/d/1o_RX510Cu3subRuzF--iDPAJYJCOrKV_MHlowvdVEWs/edit#gid=0

Content Migration  integration checklist https://docs.google.com/spreadsheets/d/1Lgk3HLpm6kIYUIdnkR9FitGA6Ft5Yjd67g6Dh6kg0MA/edit?usp=sharing

~12/6/23

> **Below are high level considerations, additional detailed process should be organized with Drupal Developer.

**Steps for Migrating Content** (Diego)

- Log into VDI
- Log into `https://benefit-finder-waf-main.app.cloud.gov/user/login`
- Find Node to transfer, `https://benefit-finder-waf-main.app.cloud.gov/<node id>`
- Log into `usagov prod admin cms`
- Create/Draft new Node from type in `usagov prod admin cms`
- Add new `<node id>` to inventory tracking document
- Mark as `Done` on content report

**Steps for QA Migrated Content** (Nehemiah)

- Log into VDI
- Find origin node, `https://benefit-finder-waf-main.app.cloud.gov/<node id>`
- Find destination node, `https://usa.gov/*/<node id>`
- Compare rendered content using `https://www.w3docs.com/tools/code-diff/`
- Ticket Errors and assign to appropriate person
   -  include screenshots
- If no Errors, mark as `QA`

**Comment by fongcindy** [comment]
Current blocker: Diego does not have access to the main site. Isabel and Russel have submitted and approved this request and we are waiting for an update and access

Related ticket: https://github.com/GSA/px-benefit-finder/issues/713

**Comment by fongcindy** [comment]
Isabel was able to resolve the blocker, Diego can now work on his steps of the content migration

**Comment by fongcindy** [comment]
Diego expected to complete the content migration by EOD 12/21 :)

**Comment by diegocob** [comment]
ES migration completed on 12/21.

**Comment by diegocob** [comment]
This has been completed. @nehemiah-abuga is QA complete? @scottqueen-bixal and @gchi25, do I need to publish the content or will you guys do that?

**Comment by fongcindy** [comment]
@nehemiah-abuga, any updates on the QA for the content?

**Comment by diegocob** [comment]
@nehemiah-abuga mentioned the QA was completed.

**Comment by diegocob** [comment]
98% complete
