### ISSUE TITLE
Create tickets to update static content in usagov to point to benefit-tool

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#704]
The static content that lives in usa.gov, that references the old v1 benefit finder tool, will need to be updated: 

The old v1 link is found [here](https://www.usa.gov/#all-topics-header) >[disability services](https://www.usa.gov/disability-services) > disability benefits locator block

Steps
1. Check to see where the old v1 link is referenced to in the content static, maybe check with Shosana to see if she is tracking this somewhere? 
2. Once all old v1 references are identified, update to new link [https://www.usa.gov/benefit-finder/](https://www.usa.gov/benefit-finder/)

This ticket is placed in backlog for now

**Comment by diegocob** [comment]
Hey Cindy, this is only for the disability services benefit card in the [disability services](https://www.usa.gov/disability-services), right?

**Comment by diegocob** [comment]
I was reached out to Ernie earlier about speaking with Shoshana, and he preferred to reach out to her himself. Should I do the same here and see how he would prefer to communicate with her?

**Comment by diegocob** [comment]
@fongcindy anything else that needs to be done here or has this been completed through other tickets?

**Comment by diegocob** [comment]
Pinging this up to see if we can close this, @fongcindy.

**Comment by diegocob** [comment]
Sg. Closing this ticket.
