### ISSUE TITLE
ICONS | Accordion Green Checkmarks

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#710]
Include application inline SVG icon

Green check marks before the criteria descriptions are missing.
Note: these initially were white but changed to Check Green #009831

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/a70e7e70-1239-43f7-8940-9c302dd357e9)

Related: https://github.com/GSA/px-benefit-finder/issues/48

**Comment by fongcindy** [comment]
Hi Scott,
Confirming USAgov was in favor of the green checkmarks in the result accordions. When you get the chance, can you please make this change? Thank you!!

**Comment by scottqueen-bixal** [comment]
note: HEX `#009831` (Check Green)

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal @fongcindy 

I am just confirming that the checkmarks in these Accordion cards are OK. 
Thank you!

**Comment by angelina-smith** [comment]
@scottqueen-bixal These green checkmarks announced as expected with NVDA and JAWS in Storybook.

**Comment by ErnestoFernandezAlvarez** [comment]
Fantastic!
