### ISSUE TITLE
USAGov prod permission

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#713]
Provide content editor and content administrator permissions for edit benefit finder content.

**Comment by fongcindy** [comment]
Gene has informed GSA and Isabel has submitted the permissions and they have been approved by Russell. They are working on this and will keep us posted

**Comment by fongcindy** [comment]
Isabel was able to resolve this, she granted access to both of Diego's content roles. Diego is now able to add to the benefit-finder content
