### ISSUE TITLE
Accordion |  button and legend adjustments

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#720]
3
CTA button Size and legend:

Note Button size change:
narrower with legend split in two lines

Related: https://github.com/GSA/px-benefit-finder/issues/48

**Comment by scottqueen-bixal** [comment]
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/cff0c994-cba5-4861-b284-3ec6582ecac7)

Ernesto, need some clarification to resolve these updates

1. Is there a max width set on the CTA button or do we just want it not to be full width?
2. What is the hex color of the green check?

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal 

i. we do not want it to be full width. We can set up a width that would accommodate the longest possible text.
ii. HEX # 009831 (Check Green)

**Comment by fongcindy** [comment]
Let's hold off on making these for the width and button sizes.

We have a sync scheduled with Diego and Amy on 1/2, after this call we will determine the content changes that will define the final standard button sizes.

**Comment by fongcindy** [comment]
@scottqueen-bixal As mentioned in  Ernesto's comment in this related ticket: https://github.com/GSA/px-benefit-finder/issues/48

The Desktop Accordion button for all benefits accordions and in both languages should be:
-2 line of text
-404x58 size

When you get the chance next week or next sprint, can you ensure these changes are made? Thank you!

**Comment by EnriqueOrt** [comment]
Waiting on design audit for USAgov feedback - will resume work once we get more information.

**Comment by ErnestoFernandezAlvarez** [comment]
We did agree on a button size as a team a couple of weeks ago. I expect to
be making further revisions upon the completion of the audit from Usa.gov.
Thanks guys!

**Comment by scottqueen-bixal** [comment]
Closing this as duplicate
