### ISSUE TITLE
ES Relevant event not showing up in draft mode

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#725]
### Description

The relevant events in ES Death are not showing up.
 
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/a47fcfa8-509e-4953-a8c6-8aff60ac9b3e)

### User Story

Need to find other relevant life events finder in the Spanish version.

### Architectural Decision Records (ADRs)

Need to check relevant events code and path link and why it's not working.

**Comment by scottqueen-bixal** [comment]
closing as completed
