### ISSUE TITLE
Unable to migrate Life event form bc criteria key does not appear.

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#727]
### What's expected

When Diego is entering a life event form I should be able to reference the criteria key for each section. I am unable to do so bc no criteria come up in the Criteria key search. This problem was not there with Gene.

### What happened

When Diego enters the criteria key, there is no reference or search results to any criteria. The same happens when entering a benefit and linking it to criteria key.
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/5f6e90d9-59c7-42af-b428-0f4ef534f1fb)

I get the following error:
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/de0a63ef-de53-49e4-ae40-e626f6b3ec65)

### How to replicate
- [ ] Go to Life event form in [ES Buscador de beneficios: muerte de un ser querido](https://cms.usa.gov/es/node/2134)
- [ ] Scroll down to the `Sections (Eligibility Criteria)` 
- [ ] Click on add criteria 
- [ ] Try entering any `Criteria Key` see if you can toggle and search for different criteria.
- [ ] Try saving the node and see if you don't get an error message.

**Comment by diegocob** [comment]
Tagging the Dev team since @gchi25 will be OOO. This is a blocker for migrating more content.

**Comment by fongcindy** [comment]
Diego was able to chat with Gene to work on resolving this. This is tied to a permission issue, Diego will coordinate with Isabel to unblock this.
