### ISSUE TITLE
Edit titles of sections in Retirement and Disability LE Forms

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#733]
### Description

When you are back, @gchi25, could you change the title of the life event pages of Retirement and Disability to read: 

- [ ] About the applicant (1 of 2) 
- [ ] About the applicant (2 of 2)

I couldn't change anything in EN bc the criteria in EN are not published and it was showing up as an error. Once you change it I can change it on Sandbox.

### User Story

Need to have consistency of page titles among LE and be able to understand how many pages there are in the form.

**Comment by scottqueen-bixal** [comment]
closing as completed
