### ISSUE TITLE
Design Zero Benefits Page

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#737]
Ernesto has started on the design for the zero benefits page for DOLO, [figma file](https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=2275-3360&mode=design&t=uARNGiZFB8cfuhC8-0)

**Currently:** 
When a user does not qualify for any benefits, the results page looks the same and shows 0 benefits

**Expected:**
When a user does not qualify for any benefits, a modal asking users "Are you sure your information is correct?" will pop up and options are:
1. Back to the usa.gov [site ](https://www.usa.gov/survivor-benefits)
2. Go back to the form

**Next steps:**
- [x] Brainstorm with UX team about what to place on the actual zero benefits page, i.e. links to other government sites, etc. 
- [x] Ernesto to design based on UX team discussion and recommendations
- [x] UX team review and approval
- [x] Review with Tech and Ernie 

Note:
We will need design in both English and Spanish

Related ticket: https://github.com/GSA/px-benefit-finder/issues/707

**Comment by ErnestoFernandezAlvarez** [comment]
Hi @fongcindy and team
I thought we could discuss this user flow sometime in January. I'd like to brain storm about what problem we would like to solve for the user at this stage.

Here are some of my thoughts:

Scenario 1: User has entered wrong information and has not reviewed it prior to seeing results. We can direct him via modal back to the form or somewhere previous to that.

Scenario 2:  a Zero result screen with a message that tells the user "You didn't qualify for any benefits, however below are some other services and agencies to help you find benefits", here the user can jump into other agencies (we have to decide which ones), or go back to a Life Even landing page, etc. We could also direct him to local or state agencies via Zip Code entry, etc.

This page should include links to further direct the user.

Scenario 3: The page could list all the benefit accordions (not eligible), with the option to see open them individually as in V1. 


I think we could try a few ideas and validate them via user testing.

**Comment by fongcindy** [comment]
Hi Ernesto,
Yes, I think this ticket was created after we chatted more about this, I moved this to product backlog for now. 

Thanks for including an overview of the 3 scenarios! Agreed with the approaches you outlined and scenario 2 including links and more resources. 

Sounds good, user testing will help define the scope of this work more clearly.

**Comment by ErnestoFernandezAlvarez** [comment]
thanks Cindy!

**Comment by fongcindy** [comment]
Assigned to Sprint 23, let's make sure to prioritize this ticket. 
We can brainstorm a "quick" temporary solution and brainstorm with UX team along with Scott to see what solution makes the most sense for long term

**Comment by ErnestoFernandezAlvarez** [comment]
Sounds good, thanks for the heads up!

**Comment by fongcindy** [comment]
This is a big ticket, breaking this into smaller tickets like [707](https://github.com/GSA/px-benefit-finder/issues/707).

**Comment by fongcindy** [comment]
Figma zero benefit flow [here](https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=2275-3360&mode=design&t=Suf49lu6QoophMSn-0)

**Comment by fongcindy** [comment]
Reviewed with the UX team, general thoughts: option 2 is preferred because it is easier for the user to understand. Has a CTA and is two pages, message on top "You are not eligible for an benefits" very clear.

**Comment by erniedeeb** [comment]
After internal review and approval, we should send it to USA.gov content for review before we start building.

**Comment by fongcindy** [comment]
Hi Ernie, the UX team has reviewed and confirmed that option 2 is the recommended option, Scott has also confirmed that it is feasible. 

Do you want to start this conversation with USA.gov?

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy Should I focus on continuing with Option 2 only? 
Message + 2 CTAs (Option to go back and fix entries + Option with full list of non-eligible benefits)

**Comment by erniedeeb** [comment]
I think there are some accepted style changes from the recent design review we can implement into the design/development of this new page. Do you think it makes sense to do that now rather than changing designs later? I would want to discuss the design with USAGov UX before handing off to dev.

**Comment by fongcindy** [comment]
I think it's a great time to include the design changes now instead of having to go back and redoing the design with the design feedback changes. I'll sync with Ernesto to have him start making the changes we agreed on. 

Yes totally, we'll wait for your review and approval with USAGov UX before the handoff to dev.

**Comment by ErnestoFernandezAlvarez** [comment]
I agree with you @erniedeeb . That is the reason we are going slow with this. Currently the plan is to review some of the content content for these page with Diego.
We started with these pages before we had the review sessions, so we could re prioritize things a bit. What do you think @fongcindy?

**Comment by fongcindy** [comment]
Latest content changes in zero benefit page, see here: 

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/bce3191b-44fd-4734-bb2e-fae9791a12d7)

Next step:
Ernesto to create a revised design of zero benefits design to incorporate USAGov design feedback

**Comment by diegocob** [comment]
@ErnestoFernandezAlvarez did we finish this? Lmk if we still need work on this.

**Comment by ErnestoFernandezAlvarez** [comment]
hey @diegocob I closed the ticket. 
The intention for this version of the Zero benefit page was to 'Close the loop' but not meant specifically to be permanent. @fongcindy am I right? 

Recently Ernie expressed interest in making the zero benefit richer in content and perhaps functionality (maybe linking to Benefits.gov, etc)

**Comment by fongcindy** [comment]
Related:

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @diegocob @erniedeeb 
Hello guys,

The zero benefit page in the style of the USA.gov redesign has been finished. Please refer to the Figma file and screenshots.
Thank you!
Ernesto
[
Zero Benefit Screen Design Exploration ONGOING
[#837](https://github.com/GSA/px-benefit-finder/issues/837)](https://www.figma.com/design/xij2PUZTouE6cco8f1F2Bn/USAgov-ReDesign-Benefit-Finder?node-id=1%3A17298&t=XvihX7fBR6fRjH5d-1)



![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/cea571d1-8708-4ec7-b9d0-38d08db826b9)



![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/449cac17-89bd-4ed2-847f-ca9a27bc79ba)



![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/42ef1e84-075e-4a24-8fa9-3dacf39f4db2)
