### ISSUE TITLE
QA Scenarios

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#74]
Scenario Document:

https://docs.google.com/spreadsheets/d/1tCNJzKcQQvspkw2j30kkkv_XVFzghMXYEEd_SKSExq8/edit#gid=0

Establish some e2e tests for the included scenarios

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga can you please provide an update?

**Comment by scottqueen-bixal** [comment]
@scottqueen-bixal  link to work in progress PRs were requested on NOV22, please update.

**Comment by scottqueen-bixal** [comment]
carrying over to Sprint 20

**Comment by nehemiah-abuga** [comment]
This was updated and split into individual tickets. 
1: https://github.com/orgs/GSA/projects/48/views/16?pane=issue&itemId=46068751
2: https://github.com/orgs/GSA/projects/48/views/16?pane=issue&itemId=46068759
3: https://github.com/orgs/GSA/projects/48/views/16?pane=issue&itemId=46068771
