### ISSUE TITLE
Include Background Icons in landing banner

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#747]
Include svg icons in headings depending on which life-event is being shown

**Comment by scottqueen-bixal** [comment]
@ErnestoFernandezAlvarez I've made a go at trying to get the SVG icons working for `/death` in the background of the headers.  Here is a quick preview.


![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/6143ee77-7c24-49f2-be51-a53fbdcbaa11)
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/45a21aaa-1834-4460-9de6-f9f69608dd7f)

Can you please provide me with the two additional icons that we are using with `/retirement` and `/disability`

**Comment by ErnestoFernandezAlvarez** [comment]
![Inclusive Icon](https://github.com/GSA/px-benefit-finder/assets/125310691/aee8bf6d-683b-4717-93ab-fcaeb649f0f2)

**Comment by ErnestoFernandezAlvarez** [comment]
Hey Scott<
That is the icon I used. I lowered the opacity to 6%, so it is barely visible, like a watermark.

**Comment by scottqueen-bixal** [comment]
@ErnestoFernandezAlvarez  I need the icons for all the life events please

**Comment by ErnestoFernandezAlvarez** [comment]
@Scott

These are exported at a 1:1 ratio. I can export them up to 4 times bigger for better quality.

![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/d739937c-079e-4da9-8d9d-6faf09e74508)



![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/955692d1-7c90-4d42-9408-c27022bbe19f)
![Image](https://github.com/GSA/px-benefit-finder/assets/125310691/06c6597b-d835-447f-b65b-ab79cdfd23c3)

**Comment by fongcindy** [comment]
@scottqueen-bixal We just had a sync with Ernie and based on the USAGov feedback, we have decided to **not** add the person icon in the landing page banner. 

For the last comment (Ernesto icons), we do plan to proceed with the results page icons, I will confirm in the other ticket. Thanks
