### ISSUE TITLE
QA current data

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#75]
Starting with the latest data, audit for the following,

DEATH:
EN: https://bears-waf.app.cloud.gov/benefit-finder/api/life-event/death/jsonfile
ES: https://bears-waf.app.cloud.gov/benefit-finder/api/life-event/es_death/jsonfile

- audit content for correct entry
  - audit keys
    - compare keys from criteria fieldset and ensure they correctly match those assigned to benefits
    - note ES locale keys start with `es_`
  - audit values and acceptable criteria
    - compare values from criteria fieldset and ensure they correctly match those assigned to benefits
  - audit types
    - ensure that the criteria fieldset has the correct type assigned to it
    - tip: yes, no will be `radio` type, >2 options will likely be a `select` type
  - audit child dependencies
    - if a fieldset `"hasChild": "TRUE"`, it should also have "childDependencyOptions"
 - audit dates
 -  all days should only follow these formats:

```
// Our comparison string (content) values for acceptable criteria should be limited to the following formats
// compared to a specific date
// "<operator><MM><hyphen><DD><hyphen><YYYY>"

// ie. // "<01-01-1978"

// or

// compared to a length of time
// "<operator><number><years>"

// ie. // "<18years"
```

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga can you please provide an update?

**Comment by scottqueen-bixal** [comment]
timebox 1hr per json ~6hrs
report anything that jumps out as an issue that is inconsistent with the above guidance
report ready by Monday morning

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga updates were agreed due on NOV25, please provide status and link to progress of work.

**Comment by nehemiah-abuga** [comment]
@scottqueen-bixal - I have gone through the json files and I see issues in disability and retirement. Here is the link to the issue noted https://github.com/orgs/GSA/projects/48/views/10?pane=issue&itemId=45812676
I also added a spreadsheet to document any issue, here is the link https://docs.google.com/spreadsheets/d/1yL1HfDW_r5QaDU_DrxzvGH0Th2ed0nHU/edit#gid=1013372028

**Comment by scottqueen-bixal** [comment]
This was completed in Sprint 19
