### ISSUE TITLE
ICONS | Results Suggestion Card

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#751]
**Currently:**
 "More Benefits" page looks like this: 

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/c0ea5b29-c3a1-4c2b-b904-f104e5ff7384)

**Expected:** 
Icons with titles and descriptions 

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/abf7b135-8ac0-4888-b9ef-a408586eb790)

Style guide for reference: https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=2335-11582&mode=design&t=PA4mB2yhZcayv2Ha-0

**Comment by scottqueen-bixal** [comment]
@fongcindy , we determined that these updates would be on hold until usagov design feedback had been reviewed, correct?

**Comment by fongcindy** [comment]
@scottqueen-bixal Hi Scott, after the sync with Ernie and Ernesto to discuss USAGov design feedback, we have decided to proceed with adding these icons into the suggestion cards in the results page.

@ErnestoFernandezAlvarez for viz

**Comment by ErnestoFernandezAlvarez** [comment]
thanks guys!

**Comment by scottqueen-bixal** [comment]
@fongcindy 

Here are the implementation options that we have with some recommendations along side.

**1. handle icons as content from cms (right way, biggest lift)**

This is the best way to handle it.  It allows content editor to add icons to life-event pages. When a relevant benefit is assigned the link to the image is returned in the JSON data object.  The JS application then just renders the `svg`.  

Pros: 

- No dev required when adding/updating new icons
- No dev required when assigning relevant benefits
- Managed by content team

Cons:

- requires changes on cms and application
- USAGov media has allowed file extensions: `.png, .gif, .jpg, .jpeg`
We can add svg, but need to get approval to allow for that config update, OR rely on `png` files.

**2. return the id and inline the` svg` with a switch component in JS (good way, lower lift)**


Pros: 

- no need for approval to use svg
- back end update only requires code change to include 'id' in our related benefits object

Cons:

- requires dev to include new images in code
- can break if id changes

 
 @gchi25 agrees

> It is better to use media to manage image files.
Media management is same like content management

**Comment by fongcindy** [comment]
In the interest of time, let's proceed with **option 2 return the id and inline the svg with a switch component in JS (good way, lower lift)**
For similar future issues, we can discuss the possibility of implementing option 1.
Thank you!

**Comment by scottqueen-bixal** [comment]
@fongcindy and @ErnestoFernandezAlvarez can you point me to the icon used for `death of a loved one`?

**Comment by ErnestoFernandezAlvarez** [comment]
Hello @scottqueen-bixal, Is this the one you are looking for?:

![Inclusive Icon](https://github.com/GSA/px-benefit-finder/assets/125310691/e16070b8-ef06-40b8-b0ad-a16b4e7ec3b9)

**Comment by ErnestoFernandezAlvarez** [comment]
@fongcindy @scottqueen-bixal 

As per our conversation with Cindy yesterday (3/6) we are only commenting on the Icons. They look OK to me except that they look a bit pixelated when Zoomed In (on VDI)

Please see the screenshot below, here are some design call outs (even though we are not focusing on them)

- In general the layout in the MVP looks a bit more elongated and narrower.
- The Icon and the Arrow are closer to the edges in the MVP. On Figma there is a bit more margin. 
- The border around the card is thinner: 0.5 in Figma
- The color for the border is #005EA2 (Pop Blue)
- There is a light shadow added to the card to create depth 

<img width="747" alt="Screenshot 2024-03-06 at 4 40 44 PM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/6bb0b88b-1cc1-4d53-a0cc-05bff782bc97">

**Comment by angelina-smith** [comment]
@scottqueen-bixal These icons are sounding as expected with NVDA on Storybook
