### ISSUE TITLE
Keyboard Tab Order | 1st Tab Order

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#757]
On the initial start, "Complete Questions - About the applicant" section, the "Skip to main" (content) would normally be 1st in the tab order, then the top of nav.

**Currently:** 
The 1st tab order was the Progress step indicator 

**To replicate:**
Navigate to the page and hit "tab" on keyboard

**Notes from 508 sync:**
On the backend, the tool and form is built as one page, but visually, for user experience is multiple pages. When a user is navigating the site with their keyboard, we have to mimic the multiple pages through the keyboard tabbing functionality. 

For the second step/page, to give an equivalent visual experience, we can skip the items in the header. Start the focus at the step indicator.

[508 Compliance Audit Tracker](https://docs.google.com/spreadsheets/d/1iJSaqpiTv-MBkAGe9QXVX3ixrEZzIE1IQtv1tr5zsqM/edit#gid=0)
Related Ticket: https://github.com/GSA/px-benefit-finder/issues/731

**Comment by fongcindy** [comment]
Scott is planning to address this today 1/8, expected QA review for Angelina tomorrow 1/9.
Final approvals for work by 1/9 EOD to prepare for stage deployment for USA.gov

**Comment by fongcindy** [comment]
Update: Scott and team will be working on this for sprint 23, will have Angelina QA when it is ready.

**Comment by scottqueen-bixal** [comment]
@angelina-smith and @fongcindy this has been updated on https://benefit-finder-waf-main.app.cloud.gov/benefit-finder/death. Please ignore the focus styles, we know it is a new regression that is being tracked here -> https://github.com/GSA/px-benefit-finder/issues/795

**Comment by fongcindy** [comment]
Thanks Scott! 

@angelina-smith please start your QA/testing, thank you!

**Comment by scottqueen-bixal** [comment]
Awesome, we will get some unit testing around this to try and catch any regressions in future release(s)
