### ISSUE TITLE
Keyboard Tab Order | DOB Error

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#758]
On the initial start, "Complete Questions - About the applicant" section, when a user hits the tab button for the first time after making an error, they would be brought to the first field where the error should be fixed.

Currently:
The 1st tab order was the "main-content region, then the 2nd tab takes you to the bottom footer nav to "All topics and services" link

To replicate:

Leave the Day field in DOB empty, completed the rest of the form fields and clicked continue button at the bottom. Hit 'tab' key for the 1st tab order element.

[508 Compliance Audit Tracker](https://docs.google.com/spreadsheets/d/1iJSaqpiTv-MBkAGe9QXVX3ixrEZzIE1IQtv1tr5zsqM/edit#gid=0)
Related Ticket: https://github.com/GSA/px-benefit-finder/issues/731
Similar Ticket: https://github.com/GSA/px-benefit-finder/issues/757

**Comment by scottqueen-bixal** [comment]
This has been updated https://github.com/GSA/px-benefit-finder/pull/760#pullrequestreview-1811094672

**Comment by fongcindy** [comment]
Angelina has completed her QA and confirmed that this looks good on her end. 
We are ready to proceed
