### ISSUE TITLE
Move all the scripts in bin/ folder

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/px-benefit-finder#763]
### Description

Move the below scripts in the `bin/` folder in the repo and re-configure the pipelines to consume the new paths to the scripts:

- [mv-benefit-finder-app.sh](https://github.com/GSA/px-benefit-finder/blob/main/mv-benefit-finder-app.sh)
- [mv-usagov_benefit_finder.sh](https://github.com/GSA/px-benefit-finder/blob/main/mv-usagov_benefit_finder.sh)
- [mv-uswds-usagov-theme.sh](https://github.com/GSA/px-benefit-finder/blob/main/mv-uswds-usagov-theme.sh)

**Comment by casey-rapnicki-bixal** [comment]
Moved scripts in bin folder to scripts folder.
