### ISSUE TITLE
BF Report Tool

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#768]
### Description

Develop BF report tool.

Currently our reporting tool looks like:
![Image](https://github.com/user-attachments/assets/8d60dd89-31f0-4929-b374-265010419f59)

### Acceptance Criteria
Set up an initial BF reporting tool.

**Comment by scottqueen-bixal** [comment]
need more information on what type of reporting will be created

**Comment by scottqueen-bixal** [comment]
HOLD as do not work on, will discuss with Cindy
