### ISSUE TITLE
review content changes on stage for conflict with dev work

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#779]
Some changes on usagov stage are being made and we need to sniff out any potential conflicts with dev work.

From PO:
> Shoshana and I went through [usa.gov](http://usa.gov/) stage environment to make some IA and content changes. Will any future moving of data from our environment to theirs cause any of that stuff to be overwritten?

For visibility, here are the changes we made to [stage](https://cms-stage.usa.gov/):

- Removed [benefits.gov](http://benefits.gov/) link card from [Government benefits page](https://cms-stage.usa.gov/benefits)
- Removed [benefits.gov](http://benefits.gov/) content page, link points to [benefits.gov](http://benefits.gov/) website directly
- Adjusted benefit finder card position on [Government benefits page](https://cms-stage.usa.gov/benefits)
- Reformatted [benefit finder landing page](https://cms-stage.usa.gov/benefit-finder) for brevity
- Added [benefits.gov](http://benefits.gov/) to [benefit finder landing page](https://cms-stage.usa.gov/benefit-finder)

**Comment by gchi25** [comment]
Any refreshing of database from upstreaming will override these.
The dev work will not override these for now.

**Comment by scottqueen-bixal** [comment]
closing as completed
