### ISSUE TITLE
Changing Focus Color for Screen Readers

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#782]
Currently the accessibility focus color is a orange/brown color, GSA is changing this to aqua/blue.

**Currently:**
![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/06011136-6884-4eb3-8517-0254bc3de255)

**Expected:** 
![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/9dacc0b3-6d28-4113-895a-70acb0f2d89a)

**Comment by erniedeeb** [comment]
I think there is another ticket for this issue floating around somewhere, but I couldn't find it. Here's the most recent update from USA.gov

> I did get a chance to view the benefits finder and noticed one of the elements on the page still had an orange focus. I will add the style to our css that should fix that issue.

That came from Bryant Jones, so we should be able to follow up with him or Isabel for more information. But hopefully it will be included in the next release.

**Comment by erniedeeb** [comment]
Looks like the issue has been addressed in dev and will make it into the next prod push. https://beta-dev.usa.gov/benefit-finder/retirement
