### ISSUE TITLE
finalize release and review schedule/cycle

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#790]
With the new integration staged in production at usa.gov/benefit-finder we need to organize our coordinated release schedule.

Working document:
https://docs.google.com/spreadsheets/d/1-Go0_iodk0WEDSQ-jCgsy8EOLuuLHOOo0iQDpzX_0ZA/edit#gid=135828904

**Comment by fongcindy** [comment]
Enrique and I have completed our review looks good to us! 
Next: Ernie and GSA to review

**Comment by erniedeeb** [comment]
Has USAGov webops been looped in to validate this or should I get their attention on it? I believe they work in 3 week sprints; will that conflict with this plan or are we only really concerned about aligning with their deployment schedule?

**Comment by fongcindy** [comment]
USAGov webops has not validated this draft release schedule, yes could you share this with them to get their thoughts? 

We're mainly concerned about aligning with their deployment schedule

**Comment by erniedeeb** [comment]
I think we should have a call with Isabel and Amy where this document can be presented and discussed in real time. I will schedule.

**Comment by scottqueen-bixal** [comment]
updated the release cycle to use a hybrid approach that supports semantic release practices https://docs.google.com/spreadsheets/d/1-Go0_iodk0WEDSQ-jCgsy8EOLuuLHOOo0iQDpzX_0ZA/edit#gid=1070460332

 
1. Major/Minor Release work together in a 6 week release cycle.  This allows for two (2) sprints of development work and one (1) sprint of QA and fixes
4. Security and Bug Patches go up within a sprint. These are likely lower in priority but need to get up more quickly.
5. Anything critical needs to be identified and pushed up stream ASAP. This requires more coordination with the USAgov team.

**Comment by fongcindy** [comment]
@EnriqueOrt @erniedeeb 
We plan to start this hybrid approach tomorrow 2/6, any objections on your end?

**Comment by erniedeeb** [comment]
LGTM

**Comment by scottqueen-bixal** [comment]
closing as complete
