### ISSUE TITLE
Pre-launch content updates

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#791]
Validate body copy, description, meta description for benefit finder [landing page](https://beta-stage.usa.gov/benefit-finder).

- Body copy: page text
- Description: nav card text (as seen on usa.gov [government benefits page](https://cms-stage.usa.gov/benefits))
- Meta description: shown in search results

**Comment by diegocob** [comment]
Is there a time line for this?
For the body:copy how much do we want to get into changing or editing? Quick QA or also including important changes.

**Comment by erniedeeb** [comment]
By end of week if possible, to track with launch. Quick QA of body copy is
good enough, just to make sure it's saying everything we need it to say for
launch. The two description fields can re-use some text as well if that
makes completing this task any easier. And Shoshana has asked to review our
changes before they go live.

**Comment by diegocob** [comment]
Updating the progress here: completed content review and suggested changes to the meta data description in [this doc](https://docs.google.com/document/d/1UJzHip-EoR4crwIKU8vGZG8PVtNodmBjo3DRi1HDGMk/edit?usp=sharing).

Ernie is checking with Shoshana about the changes.

**Comment by diegocob** [comment]
I think these are completed, @erniedeeb?
Wanting to close the tix.

**Comment by erniedeeb** [comment]
Good to close
