### ISSUE TITLE
Add virtual page attribute to distinguish between the "pages" of the app and results pages

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#794]
We need an attribute that says which "page" users are on. We've used usa-step-indicator__segment to create a virtual page variable within the form, but it doesn't apply to the results pages or the start page. This will be particularly helpful for distinguishing between clicks on eligible benefits on the results page and clicks on ineligible benefits on the "Benefits you didn't qualify for" page. Currently we have no way to distinguish between those events.

**Comment by nickpistone** [comment]
Moved this to the product backlog since I'll be on vacation for most of this sprint. Planning to pick it back up when I get back.

**Comment by scottqueen-bixal** [comment]
These are the values I am updating to provide on the results view
 
```jsx
      data-analytics="bf-result-view"
      data-analytics-content={
        notEligibleView === true ? 'bf-not-eligible-view' : 'bf-eligible-view'
      }
      data-analytics-content-criteria-values={criteriaValues}
      data-analytics-content-benefits={benefitsLength}
      data-analytics-content-eligible={eligibilityCount.eligible}
      data-analytics-content-not-eligible={eligibilityCount.notEligible}
      data-analytics-content-more-info={eligibilityCount.moreInfo}
    >
```

so when a user lands on the results view you will know, 
- if they are viewing eligible or not eligible lists
- how many questions they provided answers for
- what are the total available benefits
- how many they were eligible for
- not eligible for
- or benefits that required more information to make a determination

for example, if I only fill out the required fields on death of a loved one the bf-results-view element will contain the following attributes and values
 
```HTML
<div class="bf-result-view" data-testid="bf-result-view" data-analytics="bf-result-view" data-analytics-content="bf-eligible-view" data-analytics-content-benefits="30" data-analytics-content-eligible="0" data-analytics-content-not-eligible="14" data-analytics-content-more-info="16" data-analytics-content-criteria-values="4">
```
 
if they go back and provide values for all criteria questions it would look more like, 
 
```HTML
<div class="bf-result-view" data-testid="bf-result-view" data-analytics="bf-result-view" data-analytics-content="bf-eligible-view" data-analytics-content-criteria-values="17" data-analytics-content-benefits="30" data-analytics-content-eligible="16" data-analytics-content-not-eligible="14" data-analytics-content-more-info="0"
```

This should give us the data we need to track to make better informed decisions around results, zero benefits, etc. on this view.  

@nickpistone Let me know if you think we need to make any adjustments here?

CC: @fongcindy

**Comment by nickpistone** [comment]
Looks good to me! Thanks Scott! I will need to test everything out in GTM to make sure it all works out. But this seems like it would provide me with a lot of really insightful data through all these attributes. The criteria values attribute is the number of questions they answered right? @scottqueen-bixal

**Comment by nickpistone** [comment]
These attributes all look good in the dev environment. I will have to create some custom javascript variables to put them to use in GTM, which I'm not sure how to do yet. But I can figure it out. The attributes themselves appear to be providing the correct values. The issue now is how to get to them since they are at the page level and not associated with specific click events like the majority of variables I track. Bottom line: they're good to go. It's just going to require some custom GTM work to get these attributes into tags.
