### ISSUE TITLE
USA.gov CSS Updates Interference

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#795]
USA.gov has pushed up some new styles for focus value and this is breaking styles on our form. 
They're not using native USWDS code, they're using custom CSS to overwrite our style instead. 

Flagging because this is an accessibility issue.
Risk - when USA.gov changes style/custom CSS, we have to potentially go back in and fix each time. They also didn't fully update everything

When tabbing through, the focus/highlight is not showing for the DOB month selection drop down:
![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/e7930c85-19b9-426d-b1fa-b4f9c903a346)

Tabbing to options are not working, it forces the user to only select one option:
![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/0c993e7f-6202-4d32-8f60-68eeb46027a7)

Following items are OK

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/d6736ba1-b352-4227-9d3b-6f14fea1de4c)

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/1adb6da5-5faa-4dcf-9bcc-4fbd79a287e9)

Related: https://github.com/GSA/px-benefit-finder/issues/789

**Comment by angelina-smith** [comment]
I'm seeing a visual focus indicator around the DOB-Month field (using Chrome) so this field looks okay to me?  ![image](https://github.com/GSA/px-benefit-finder/assets/142342010/1a3b4de1-aa47-4018-81a7-b7d5a529547a)

Places where I do see visible focus indicator issues (not present, way too subtle, or wonky):
- Agree with the Yes/No radio buttons
- 'Back' button (on all instances in which it appears)
![image](https://github.com/GSA/px-benefit-finder/assets/142342010/12e1b6e3-210b-4d44-bc7a-ed37f693cf7f)
- Accordions on the eligible results page (drop shadow changes to white on focus, way too subtle)
![image](https://github.com/GSA/px-benefit-finder/assets/142342010/e4540bf2-50e0-44ce-af55-4b6f0c8b95f0)
- 'Share link' and 'Email results' buttons
![image](https://github.com/GSA/px-benefit-finder/assets/142342010/7329b810-dfc3-4b14-a5a7-24240f14acea)

**Comment by scottqueen-bixal** [comment]
Given direction by @erniedeeb to hold off on fixes this until we organize an approach for avoiding style pollution for usagov implementation at the global level.

My recommendation is to proceed with our own fix until a collaborative decision is made.

CC: @fongcindy

**Comment by erniedeeb** [comment]
Checking in with USA.gov on this issue, as it is something they have in their ongoing work but hasn't been released yet. 

Focus styles weren't dinged in the audit though, so these changes should be safe to make _if_ they aren't resolved as part of USA.gov's ongoing work

**Comment by angelina-smith** [comment]
@scottqueen-bixal @fongcindy Confirmed that focus indicators look great on all pages!
