### ISSUE TITLE
Spanish content creation for "Other death benefits" on benefit finder landing page

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#801]
With some IA updates, the benefits.gov now lives in an "Other death benefits" link on the benefit finder landing page. The English version is updated with copy, but we need to have that copy trans-created in Spanish to make the appropriate link changes.

[English version](https://www.usa.gov/benefit-finder):
[Spanish version](https://www.usa.gov/es/buscador-beneficios)

[Working document](https://docs.google.com/document/d/1UJzHip-EoR4crwIKU8vGZG8PVtNodmBjo3DRi1HDGMk/edit#heading=h.2o48mav8aowj)

**Comment by diegocob** [comment]
This has been created. Lmk when we are good to make the changes on the CMS.

**Comment by diegocob** [comment]
Hey @erniedeeb, pinging this up to see if it's ok to mark this ticket as completed.

**Comment by erniedeeb** [comment]
All clear! Thanks Diego.
