### ISSUE TITLE
Remove json files from being indexed in Search

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#802]
See attached screenshot, search result #4. In USA.gov search the json files are showing up as results. This search is powered by Bing, so they are appearing in Bing search as well, but not Google search for the time being. Can we omit these files from being indexed? 

![Image](https://github.com/GSA/px-benefit-finder/assets/7094493/1608ce5c-becc-4362-ac8e-aa36c6ee0ad2)

**Comment by erniedeeb** [comment]
Work with USAGov to see if there is anything on their end they need to do to address this issue.

**Comment by scottqueen-bixal** [comment]
Spiking this in sprint 25. We need to see who on the USAgov side can get these files off the search index.

**Comment by scottqueen-bixal** [comment]
@erniedeeb and I confirmed that this issue is resolved, 

no longer appearing in search, ie. https://search.usa.gov/search?affiliate=usagov_all_gov&page=1&query=Benefit+finder%3A+retirement+Retirement+should+be+celebrated
