### ISSUE TITLE
Add benefit finder pages to sitemap after DNS updates

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#803]
When David K. attempted to add the benefit finder pages to the usa.gov sitemap, he received an error in that a bunch of /node/ urls were added instead. I'm guessing this issue is related to our current redirect solution. Leaving this ticket here as a reminder to update the sitemap again once we move off the middleware redirects.

**Comment by erniedeeb** [comment]
This issue was due to the entity type not being "Life Event". "Benefit" or "Life Event Form" entity types will cause this issue.

I believe USAGov made the change to the entity type to cause the pages to appear in the sitemap, we will have to validate that those changes didn't break anything and revert if necessary.

https://cms.usa.gov/sitemap.xml

**Comment by scottqueen-bixal** [comment]
closing as completed
