### ISSUE TITLE
USAGov menu update

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#804]
USAGov menu changed., bread crumb and mobile menu not showing up.

Bread crumb not showing up.
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/99bf2182-1e89-4640-9ef8-88c25eedf2d4)

Mobile menu is not at Benefit Finder level.
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/0a7be697-95df-4f1a-b54b-6818592cea73)

**Comment by gchi25** [comment]
Updated USAGov Prod menu.
The breadcrumb and mobile menu work in the following pages.
https://www.usa.gov/benefit-finder
https://www.usa.gov/benefit-finder/death
https://www.usa.gov/benefit-finder/retirement
https://www.usa.gov/benefit-finder/disability
https://www.usa.gov/es/buscador-beneficios/muerte
https://www.usa.gov/es/buscador-beneficios/jubilacion
https://www.usa.gov/es/buscador-beneficios/discapacidad

![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/1f59e63e-27ae-42be-aa4a-65553be52910)

![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/903eff29-e2be-4f44-ae2d-95d899b9b498)

**Comment by scottqueen-bixal** [comment]
closing as completed
