### ISSUE TITLE
Implement Head USAgov Drupal Field in Benefit Finder Page Templates

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#808]
## Background

> This is working on the landing pages but the snippet still needs to be added to the head of the application pages in both EN/ES. The content team cannot make this change because these pages don't have a head field in the CMS ([Set up CrazyEgg recordings to track user visits on v2 Benefit Finder #692](https://github.com/GSA/px-benefit-finder/issues/692)).

There is a field in USAGov twig system that allows content editors to add elements to the HEAD of the document

## Task
- [ ] review to see if we can implement in Benefit Finder
- [ ] update Benefit Finder

**Comment by gchi25** [comment]
https://github.com/usagov/usagov-2021/pull/1422

**Comment by scottqueen-bixal** [comment]
![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/b97c8949-87e8-491b-8b89-cd72304dd91c)

confirming the field is on prod

example: 

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/5bab23ab-07c9-44a8-ad45-77456b4b7466)

**Comment by scottqueen-bixal** [comment]
confirming that field works on dev


![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/30f6c455-4fb2-48b2-a64b-8f1c3e4b4df0)
