### ISSUE TITLE
Screen Reader Announcing "Invalid"

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#810]
Screen reader announces "invalid" entry on all required form fields, as a user this is confusing to hear "invalid entry" on a form field I have not yet filled out or completed. 

Location:
About the applicant and about the deceased pages

What Happened?
The first time a user encounters a required form field, the screen reader announces "invalid" entry.

How to replicate? 
NVDA x Firefox, using 'Tab' key to navigate to the required form field 

View what happened:
https://app.screencast.com/2ma4y52LPLQMp?conversation=BoreoopP1dJLaMG836n21b

**Comment by angelina-smith** [comment]
@scottqueen-bixal Listened to this on Storybook and it sounds good to me!
