### ISSUE TITLE
'Year' Field Hint

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#815]
Currently in the 'Year' field there is no indication or hint of how many digits are expected to be inputted, it only shows after a user makes an error and is alerted after they entered the year incorrectly. 

What's expected:
In the 'Year' field it should show a hint of YYYY
If a form field requires a certain format (in this case YYYY) — letting the users know this ahead of time can help prevent errors

**Comment by fongcindy** [comment]
Moving @scottqueen-bixal 's comment here: 
@fongcindy there is no hint for the DOB field since there is no content provided.



![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/f3a8c328-7fee-41b9-afb7-fd5fe9ca03ec)


Should be addressable by including the proper hint content in the CMS.

**Comment by diegocob** [comment]
Do we only do this for the YYYY and not for the month `MM` and day `DD`?

**Comment by diegocob** [comment]
Some of the options are:

1. YYYY/DD/MM
2. YYYY DD MM
3. YYYY | DD | MM
4. YYYY.DD.MM
5. YYYY-DD-MM

With different separators and with/out an example of a date like: 
YYYY/DD/MM Example: "1950-10-20"

**Comment by scottqueen-bixal** [comment]
> Moving @scottqueen-bixal 's comment here: @fongcindy there is no hint for the DOB field since there is no content provided.
> 
> ![Image](https://private-user-images.githubusercontent.com/128498116/299469664-f3a8c328-7fee-41b9-afb7-fd5fe9ca03ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTIzNTcsIm5iZiI6MTcwNjE5MjA1NywicGF0aCI6Ii8xMjg0OTgxMTYvMjk5NDY5NjY0LWYzYThjMzI4LTdmZWUtNDFiOS1hZmI3LWZkNWZlOWNhMDNlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNDE0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2M2NDk0OTIzNjU4OTcxODhhNDIxMTFkNWYzN2FiMDA2YTU0MzE1YjBmMTA2MGI3MGNhYTk4YzY0ZmYwNGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZSaW15R5ePYGDIzo240IJgCRfgsXyBNPLzEmZ0_LZCA)
> 
> Should be addressable by including the proper hint content in the CMS.

glad you caught my odd comment over on the other ticket! thanks @fongcindy

**Comment by fongcindy** [comment]
All we need is the highlighted: 
Needs in the about the applicant and about the deceased sections :) 

![Image](https://github.com/GSA/px-benefit-finder/assets/128498116/c859b1e0-30b8-4df7-8a34-9dd34e0b0d77)

**Comment by diegocob** [comment]
Hi Cindy, 
Is this USWDS guidance? I would suggest taking out the "For" and abbreviating the month for readability, just reading "Example: Jan 19 2000"

**Comment by fongcindy** [comment]
@angelina-smith Any thoughts on abbreviating the months? 

Diego - The way it's shown in the screen shot is taken from the USWDS [website](https://designsystem.digital.gov/components/memorable-date/) :)

**Comment by diegocob** [comment]
I can follow the USWDS to the "t".

**Comment by diegocob** [comment]
@gchi25 Just made these changes.
 
**DOLO** 
- [x] EN DOB
- [x] EN DOD
- [x] ES DOB
- [x] ES DOD

**Retirement**
- [x] EN DOB
- [x] ES DOB

**Disability**
- [x] EN DOB
- [x] ES DOB
