### ISSUE TITLE
Screen Reader Announces "Continue Link"

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#818]
The screen reader announces the continue button as "Continue link", this is confusing for users because its expected to say "Continue button". This is located in the Final Questions - About the deceased section. 

Please fix "continue link" to "continue text", this will help users understand that they are proceeding in the form and not going to a different link. 

The other pages, the 'Continue button' is announced correctly via the screen reader (NVDA x Firefox).

**Comment by angelina-smith** [comment]
@scottqueen-bixal Just listened to this on storybook. On the "About the deceased" page, the screen reader is announcing the Continue button as "Continue button button". 

Hopefully this link works of my screen recording. If it's not, let me know and we can hop on a quick call where I can share my audio.
https://app.screencastify.com/v3/watch/1MCI0Jp93CRhJSbgpBYS
