### ISSUE TITLE
Changing "deceased person" to "the deceased"

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#846]
Making changes to refer to the deceased as “the deceased” and not the “deceased person” for consistency” 

*Nancy's* comments

**Comment by fongcindy** [comment]
@diegocob Is this something we plan to change soon? This looks like a brief/easy fix. Enrique and I are trying to reduce clutter on Github, thanks!

**Comment by diegocob** [comment]
This is also part of the broader content changes with the you v applicant research findings.
