### ISSUE TITLE
Update Benefit Finder Entity

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#847]
Update Benefit Finder entity.

It creates view "Benefit Finder".
Add entity reference agency.
Add entity reference criteria.
Add entity reference life event form.
The entity reference views list content of published and unpublished in current page language in ascending title order.

For example, Entity reference Agency
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/6093eb77-f8d5-4cd2-8f86-5d5b2cd553a8)

Changes to use the entity reference view as reference method in entity reference field of agency, criteria and life event form.
In content type "Benefit" field "Agency".
In content type "Benefit" field "Life Event Forms".
In paragraph "Benefit eligibility" field "Criteria Key".
In paragraph "Criteria" field "Criteria Key".
In paragraph "Relevant Benefits" field "Life Event Forms".

For example, in content type "Benefit" field "Agency".
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/56a5ed54-d1f7-457d-917c-6c987f7cd8e7)

Changes the agency, criteria and life event form widget from autocomplete to select list or check boxes/radio buttons.
In content type "Benefit" field "Agency" widget
In content type "Benefit" field "Life Event Forms"
In paragraph "Benefit Eligibility" field "Criteria Key"
In paragraph "Criteria" field "Criteria Key"
In paragraph "Relevant Benefits" field "Life Event Forms"

When using entity reference view as reference method, the select box lists content of both published and unpublished in current page language in title ascending order.

For example, Agency select box
<img width="800" alt="image" src="https://github.com/GSA/px-benefit-finder/assets/88853916/986546ba-fc85-46c8-b8f7-4df7278b8e98">

**Comment by scottqueen-bixal** [comment]
closing as completed
