### ISSUE TITLE
More benefits list doesn't show card description on tablet/mobile viewports

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-benefit-finder#850]
On the results page, the more benefits list shows a description of each life event in the card (screenshot 1). In mobile and tablet viewports, the description is replaced by "Call to action([life event name])" (screenshot 2)

![Image](https://github.com/GSA/px-benefit-finder/assets/7094493/31b5ede3-13fa-45c1-b8ce-99158a941b74)

![Image](https://github.com/GSA/px-benefit-finder/assets/7094493/d62fa532-0d13-4b94-b7a3-d1cdacc20e5e)

**Comment by erniedeeb** [comment]
@fongcindy Can you review, prioritize, and assign?

**Comment by fongcindy** [comment]
@erniedeeb Sure thing, I've assigned this for sprint 25, hopefully we can resolve this sooner. 

@diegocob Is this something you can fix on your end? Or will we need to involve Gene? The content is incomplete on mobile and tablet view.

**Comment by diegocob** [comment]
We fixed this last week and @gchi25 confirmed it went live.

I checked it. @erniedeeb feel free to check and close this comment if it looks good.

**Comment by diegocob** [comment]
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/4316f389-9c4a-453d-85d4-d03d38d8f498)
Current screenshot from usa.gov/benefit-finder/death

**Comment by erniedeeb** [comment]
Confirmed fixed, thanks for the update!
