### ISSUE TITLE
Change (required) field to sentence case

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#854]
### Description

Lower case "required" fields.

### User Story

Need to have all required fields in EN be in lower case.

### Architectural Decision Records (ADRs)

1. DOLO EN
Page 1
- [ ] DOB 
- [ ] Applicant's relationship to the deceased
- [ ] Marital status
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/e765efd5-4006-4c66-afd8-79ae31d57103)
Page 2
- [ ] DOD
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/ceff09e6-cb7d-4106-82a0-f99dcfe96b28)

2. Retirement EN
- [ ] DOB
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/042f3ce5-b181-47eb-af5f-c93adeb07b09)

3. Disability
- [ ] DOB
- [ ] Marital Status
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/d1589bbb-d02e-4964-90f3-6d5be2166524)

**Comment by scottqueen-bixal** [comment]
is this still applicable @diegocob ?
