### ISSUE TITLE
USAGov upgrading from CKEditor4 to CKEditor5

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#872]
Review and feedback on USAGov upgrading from CKEditor4 to CKEditor5
http://cms-dev.usa.gov/
Try CKEditor5 in USAGov Dev site.
Check whether this would have any effect on the benefits-finder tool.
It does introduce a change in UI for people editing content.

What's changed: 

- The buttons for Accordion, Bootstrap grid, and Templates. Our team has exclusively used the "USWDS Paragraphs" integration to add USWDS-formatted elements, and we'd learned that the Accordion button (provided by the integration that also gives us USWDS table formatting) doesn't work properly. If I recall correctly, the Bootstrap grid and Templates buttons are no longer supported (and we weren't using them). 
- The editor button bar looks pretty different, and the Paragraphs button no longer has the USWDS logo, in spite of our efforts to change that. 
- CKEditor5 no longer uses an iFrame for the rich text editor. 
- ... probably lots of little stuff

What has not changed: 

- No content needed to be upgraded or modified.
- The USWDS Paragraphs are implemented in exactly the same way; only the controls for invoking them were modified.

**Comment by gchi25** [comment]
Built locally from this branch:  https://github.com/usagov/usagov-2021/tree/USAGOV-1226-ckeditor5-paragraphs-integration
bin/build
bin/drush cim
Tested to add and edit a content page of all Benefit Finder content types.
Verified that I can edit, add USWDS components, and edit USWDS components.
These upgrades do not affect Benefit Finder content management.

**Comment by scottqueen-bixal** [comment]
closing as completed
