### ISSUE TITLE
Life event page breadcrumb and mobile menu issue

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#877]
Benefit Finder life event page menu was changed.

For all Benefit Finder life event pages,

- Breadcrumb changed
- Mobile menu not working

https://www.usa.gov/benefit-finder/death
https://www.usa.gov/benefit-finder/retirement
https://www.usa.gov/benefit-finder/disability
https://www.usa.gov/es/buscador-beneficios/muerte
https://www.usa.gov/es/buscador-beneficios/jubilacion
https://www.usa.gov/es/buscador-beneficios/discapacidad

For example, 
https://www.usa.gov/benefit-finder/death
https://cms.usa.gov/benefit-finder/death

Breadcrumb changed to Home > Life events > Dealing with the death of a loved one >  Benefit finder: death of a loved one
Mobile menu not working.

![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/646e8c90-1120-42e7-8438-19c7e1e7aab4)

![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/f6dd5238-bcba-4ee9-a90e-b18e7f2754a6)

**Comment by gchi25** [comment]
Updated the menu.

For example, 
How to get survivor benefits from the government](http://localhost/survivor-benefits
changed to 
Benefit finder: death of a loved one

This is the previous menu.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/d28e537c-1daa-484e-8b84-b7fe5d81dc9f)

This is the new menu.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/2c0a0e2f-4543-4054-adc3-54290a8fba9f)

**Comment by gchi25** [comment]
In mobile navigation menu, 
in content type, somehow the life event is gone.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/adf75d38-3bad-4d8a-aeee-87ec72d8d8aa)
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/ec14f8ae-0787-4b3a-abde-eee46c08c104)

**Comment by gchi25** [comment]
I implemented a solution and tested in our DEV site as following:

- update life event page menu back to under Benefit Finder
- add life event in content type of mobile navigation menu

**Comment by erniedeeb** [comment]
We were able to figure out what caused this issue in the first place. Per Amy:

> We did have to make code changes to get Drupal to pick the menu item we wanted. I think that by default, it used the depth of the item in the menu structure and alphabetical order, and we were often finding that "false children" entries were chosen to build the nav and breadcrumbs. The fix involved using the date that the menu item was created to determine its "rank." This often "just works" because people create the primary menu item along with the content, so the menu items for the false children are automatically older. (Keeping in mind that "primary" is just a value judgment and not a thing we can specify in Drupal!)
> 
> The menu entry placing https://www.usa.gov/benefit-finder/death under https://www.usa.gov/death-loved-one might actually be older than the one placing it under benefit-finder. If that's what's happening, I think the fix is to update (or recreate) the menu items so that the one that should be "primary" is oldest. 

So I believe the issue occurred because the benefit finder menu items on the DOLO and Retirement life event pages are the older BEARS menu items with updated names and links. Since those are older than the menu item on the benefit finder landing page, they are what is shown in the breadcrumbs. I think the fix should be fore usa.gov to delete the old menu items and recreate them, which will then make the menu item on the benefit-finder page the oldest, and bring it into the breadcrumbs.

**Comment by gchi25** [comment]
Benefit Finder life event page breadcrumb is working.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/c6b56e26-31dd-44b1-ad76-b7dabfd243a4)

**Comment by gchi25** [comment]
Manually add "life event" in content type in Mobile Navigation - English and Spanish block configuration.
The life event page mobile menu is working.
![image](https://github.com/GSA/px-benefit-finder/assets/88853916/557aa550-aac6-4c88-a377-9b240e570ea1)

**Comment by EnriqueOrt** [comment]
@gchi25 could you provide an update or close out the ticket? Thanks!

**Comment by scottqueen-bixal** [comment]
closing as stale
