### ISSUE TITLE
cypress test automation setup for e2e and component testing

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/px-benefit-finder#89]
As QE engineer I would like to configure  test automation framework to lay the structure for component and e2e automated tests. This includes:-
-  adding automate test for accordion component
- adding an e2e test that select options/criteria for Survivor Benefits for child eligibility benefits in DOLO page 
- Adding a test that validates errors triggered when a user tries to navigate to the next page and does not enter date which a required field
- Add methods for commonly used functions for entering various dates when navigating a page
- Adding page objects to allow reusability
- Adding a utility class that has method for calculating dates
- Add command line scripts for e2e and component tests

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga this test is still in QA, can you provide an update so we know what the status is or what needs to be done to close this work out?
