### ISSUE TITLE
Include acceptable values in error message

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#898]
### Description

when an error in content input is found include the acceptable values from the criteria.

### User Story

As a content editor, I would like to see a list of values from the associated criteria that I can select from

### Acceptance Criteria

- [ ] content editor can find acceptable criteria listed in the error messaging console as, 

"Acceptable values from `<criteria>` includes: `<value-1>`, `<value-2>`, `<value-3>`"

**Comment by diegocob** [comment]
When QA this I could not see the acceptable values in the dropdown of each criteria.
These are my steps:
1. Went to: https://bf-cms-dev.bxdev.net/user/login
2. Went to [SSI benefit](https://bf-cms-dev.bxdev.net/user/login) checked the criteria values
3. Not seeing any acceptable values
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/d619c4bf-4877-459e-b2e8-f8ef844607fa)

4. Getting a lot of warning/error messages at the top:
Error message
Warning: Undefined array key 3 in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
Warning: Trying to access array offset on value of type null in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
Warning: Trying to access array offset on value of type null in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
Warning: Trying to access array offset on value of type null in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
Warning: Undefined array key "field_page_type" in usa_twig_vars_after_build() (line 279 of modules/custom/usa_twig_vars/usa_twig_vars.module).
Warning: Undefined array key "field_page_type" in usa_twig_vars_after_build() (line 283 of modules/custom/usa_twig_vars/usa_twig_vars.module).
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/d619c4bf-4877-459e-b2e8-f8ef844607fa)

**Comment by scottqueen-bixal** [comment]
> When QA this I could not see the acceptable values in the dropdown of each criteria. These are my steps:
> 
> 1. Went to: https://bf-cms-dev.bxdev.net/user/login
> 2. Went to [SSI benefit](https://bf-cms-dev.bxdev.net/user/login) checked the criteria values
> 3. Not seeing any acceptable values
>    ![image](https://private-user-images.githubusercontent.com/125094772/312192992-d619c4bf-4877-459e-b2e8-f8ef844607fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjc5NjQsIm5iZiI6MTcxMDI2NzY2NCwicGF0aCI6Ii8xMjUwOTQ3NzIvMzEyMTkyOTkyLWQ2MTljNGJmLTQ4NzctNDU5ZS1iMmU4LWY4ZWY4NDQ2MDdmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxODIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTJmYTA4YTcyYzJkNjVlNGM2ZWQ2OGY2N2Q1ZDZkYzM5MDk3ZTljOGRjZjY4OTg5MTQ4ZDFmMDlhMWI3YTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LfKgwshxBeybDA3I0vFAVODq8XHka-268uCyfmJdHug)
> 4. Getting a lot of warning/error messages at the top:
>    Error message
>    Warning: Undefined array key 3 in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
>    Warning: Trying to access array offset on value of type null in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
>    Warning: Trying to access array offset on value of type null in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
>    Warning: Trying to access array offset on value of type null in usagov_benefit_finder_content_form_alter() (line 18 of modules/custom/usagov_benefit_finder/modules/usagov_benefit_finder_content/usagov_benefit_finder_content.module).
>    Warning: Undefined array key "field_page_type" in usa_twig_vars_after_build() (line 279 of modules/custom/usa_twig_vars/usa_twig_vars.module).
>    Warning: Undefined array key "field_page_type" in usa_twig_vars_after_build() (line 283 of modules/custom/usa_twig_vars/usa_twig_vars.module).
>    ![image](https://private-user-images.githubusercontent.com/125094772/312192992-d619c4bf-4877-459e-b2e8-f8ef844607fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjc5NjQsIm5iZiI6MTcxMDI2NzY2NCwicGF0aCI6Ii8xMjUwOTQ3NzIvMzEyMTkyOTkyLWQ2MTljNGJmLTQ4NzctNDU5ZS1iMmU4LWY4ZWY4NDQ2MDdmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxODIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTJmYTA4YTcyYzJkNjVlNGM2ZWQ2OGY2N2Q1ZDZkYzM5MDk3ZTljOGRjZjY4OTg5MTQ4ZDFmMDlhMWI3YTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LfKgwshxBeybDA3I0vFAVODq8XHka-268uCyfmJdHug)

we are testing other functionality, those are not related - please connect with @gchi25 on proper testing steps for this functionality.
