### ISSUE TITLE
Add Header HTML field in life event

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#901]
Add Header HTML field in life event.
This will enable content editor to add header html on life event page.
For example, add CrazyEgg script.
![Image](https://github.com/GSA/px-benefit-finder/assets/88853916/c8426d13-35ae-4de5-9970-a4cd7c3cfbf3)

**Comment by gchi25** [comment]
https://github.com/usagov/usagov-2021/pull/1422
Created PR to add header html field in life event.

**Comment by gchi25** [comment]
Merged to USAGov dev 2024-02-20.
Expected to USAGov Prod 2024-02-27.
Test after prod deployment.

**Comment by scottqueen-bixal** [comment]
closing as completed
