### ISSUE TITLE
Benefit form acceptable value date validation

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#910]
In Benefit form eligibility criteria acceptable value validation, 
add date validation.

**Comment by diegocob** [comment]
Unable to access the CMS in dev mode. 
 
Went to: https://bf-static-dev.bxdev.net/ and https://bf-cms-dev.bxdev.net/ I get the same page and cannot see the CMS in development and got USAGov site. Can't access the CMS in dev envi.
 
![image](https://github.com/GSA/px-benefit-finder/assets/125094772/bcd78903-7f60-46ba-a7b7-bb41fb716d67)

![image](https://github.com/GSA/px-benefit-finder/assets/125094772/52d88993-d1c9-4f2f-882d-ef0798556062)

**Comment by fongcindy** [comment]
Notes from Gene: 

(https://bf-cms-dev.bxdev.net/user/login)
Go to this login page.
Login via SecureAuth.
This is CMS site.
Once login, you can test benefit form.
