### ISSUE TITLE
D10 - Drupal 10 development

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#92]
### Description

Install Drupal 10 for test/making Benefit Finder working in Drupal 10.
- Benefit Finder content entity
- Benefit Finder content entity configuration sync process
- Benefit Finder content sync process
- Benefit Finder custom module

link to usagov upgrade https://github.com/usagov/usagov-2021/pull/1122/files
[Discovery Drupal 10 update GSA/px-benefit-finder#184](https://github.com/GSA/px-benefit-finder/issues/184)

**Comment by scottqueen-bixal** [comment]
closing as completed
