### ISSUE TITLE
Check broken hypertext links inside BF content

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#931]
### Description

Develop a method to detect broken hypertext links inside BF content.

### User Story

As a content editor,  I would like a way to detect the broker hypertext links inside BF content.

### Acceptance Criteria
A method to detect and report broken hypertext links inside BF content.

**Comment by scottqueen-bixal** [comment]
We cover link checks on benefits here with e2e https://github.com/GSA/px-benefit-finder/actions/runs/9278083535/job/25528491025#step:4:116
