### ISSUE TITLE
CrazyEgg tracking script not installed on Benefit Finder pages

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#985]
The CrazyEgg script was supposed to go live this week but it doesn't seem to be working. We might need to troubleshoot a bit to figure out what's causing this. Let me know what you need from me -Nick P

**Comment by nickpistone** [comment]
![Image](https://github.com/GSA/px-benefit-finder/assets/121254111/8ae90c3c-0e6a-464d-b696-4e325030042a)

**Comment by nickpistone** [comment]
Created a bug report following the template, so I'm closing this one.

**Comment by erniedeeb** [comment]
Completed and validated.
