### ISSUE TITLE
CrazyEgg tracking script not installed on Benefit Finder pages

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#987]
### What's expected

I created a snapshot in CrazyEgg but it is not collecting any data. So I am able to check the installation within the tool and after doing that, it says that the tracking script is not installed. CrazyEgg does work on the /benefit-finder landing page, however. But it doesn't work on the life experience pages.

### What happened

I created snapshots, they got no data, so I tested the installation and it said it was not installed.

### How to replicate

You need CrazyEgg access, so Nick has to test it to confirm in the future. But it can be replicated by creating a snapshot for one of the life experience pages and seeing if it collects data as well as clicking the prompt to check the installation.

**Comment by nickpistone** [comment]
<img width="738" alt="Screenshot 2024-02-05 at 1 54 28 PM" src="https://github.com/GSA/px-benefit-finder/assets/121254111/801ab166-5f12-48ac-b09c-a0e01422644b">

**Comment by scottqueen-bixal** [comment]
confirmed it is up on cms - we are likely just waiting for the static build to complete
<img width="1437" alt="Screenshot 2024-03-01 at 2 26 29 PM" src="https://github.com/GSA/px-benefit-finder/assets/37077057/2a7e670a-1abf-4fb7-a4ab-13aac1232dce">

@gchi25 can you keep an eye out for prod when the build completes and confirm our crazyegg scripts are loading through on static pages, looks like a few get called over the network

<img width="1430" alt="Screenshot 2024-03-01 at 2 38 04 PM" src="https://github.com/GSA/px-benefit-finder/assets/37077057/f571d473-46f4-4f9b-ac5b-a0b4cff665e9">

**Comment by scottqueen-bixal** [comment]
confirming that I see packages from scripts imported over network, hope everyone else confirms the same
<img width="1433" alt="Screenshot 2024-03-01 at 3 01 57 PM" src="https://github.com/GSA/px-benefit-finder/assets/37077057/428ea8a3-aef2-43d2-9265-701377cc319b">
