### ISSUE TITLE
QA | a11y v0.2.0.beta.1 release

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#992]
### Domain

a11y

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml) 

Due:
03/13/23

Issues: 
#944 , #933, #908, #751, #710, #50

### Description

#944 and #933 are specific to a11y errors
#751 #908 #710 are new design elements that need a11y validation for sr
#50 is new content that needs a11y validation for sr

**Comment by angelina-smith** [comment]
@scottqueen-bixal This sounds good in Storybook!

**Comment by scottqueen-bixal** [comment]
> * Looks like [Implement Axe runner in dev envrionment #944](https://github.com/GSA/px-benefit-finder/issues/944) is completed and was included in this QA ticket because it pertains to a11y. Do you need anything from me for this [@scottqueen-bixal](https://github.com/scottqueen-bixal)?

There are a sweep of changes that resulted from implementing errors that were found from the axe runner.  These are the items we would want to have you confirm are properly implemented.

**Comment by angelina-smith** [comment]
@scottqueen-bixal, Completed my review of #945 and noticed the below issue. Please let me know if you want me to copy the below finding into #945 itself, or if this needs to be logged as a new bug. Everything else sounded fantastic on Storybook!

Within ticket #945 , item 8 regarding the Results being changed from H3 to H2. I noticed that we still have a skipped heading level from H2 to H4 (see screenshot below).
<img width="674" alt="Capture" src="https://github.com/GSA/px-benefit-finder/assets/142342010/87cbd32f-42be-4b4f-9f24-e2a93a7fdac6">

My recommendation for fixing this would be make the "You may be eligible for these benefits:" text into an H3. This would make sure our heading levels are not skipped AND having it be an H3 makes sense (content-wise) when comparing it to the other H3's on the page.

**Comment by scottqueen-bixal** [comment]
I agree, @fongcindy we can get this update made in the last lap of this sprint to have it ready for release.  If this is something we want to work on we can create a _new_ ticket that outlines the requirements @angelina-smith has commented above.

**Comment by fongcindy** [comment]
@angelina-smith Thank you for clearly outlining the issue, and what your recommendation is. Agree with your recommendation, that makes the most sense to not skip H3.

@scottqueen-bixal Please proceed with Angelina's recommendation of making the "You may be eligible for these benefits:" text into a H3

**Comment by scottqueen-bixal** [comment]
> Please let me know if you want me to copy the below finding into [#945](https://github.com/GSA/px-benefit-finder/pull/945) itself, or if this needs to be logged as a new bug.

@angelina-smith,  any issues found during QA will typically be new bug/or task tickets. Feel free to create that new bug ticket with the info below, assign to myself, and close this ticket out. 👍
