### ISSUE TITLE
QA | Design v0.2.0.beta.1 release

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#993]
### Domain

design

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

Due:
03/13/23

Issues:
#908, #751, #710,

### Description

Icons have been implemented for the related issues, please review for any design discrepancies.

**Comment by ErnestoFernandezAlvarez** [comment]
Hello guys @scottqueen-bixal @fongcindy 
Where could I see the implemented version? On the live site I do not see them.
Are we supposed to look somewhere else?
Thank you

**Comment by fongcindy** [comment]
Hi Ernesto, 
Please view the site via [VDI](https://www.google.com/url?q=https://github.com/GSA/px-bears-drupal%23vdi-login-guide-for-the-bears-team-members&sa=D&source=calendar&ust=1710175437784991&usg=AOvVaw2-AO2J1EmLJYMrcyPhx1FV) with this link: [https://bf-cms-dev.bxdev.net/](https://www.google.com/url?q=https://bf-cms-main.bxdev.net/&sa=D&source=calendar&ust=1710175437784991&usg=AOvVaw0EwF210rDhoqUos2Qa8h1_)

**Comment by ErnestoFernandezAlvarez** [comment]
@scottqueen-bixal @fongcindy 

Hi guys, I added my comments to close this ticket into the following 3 tickets, please let me know if this is clear.THANK YOU!

https://github.com/GSA/px-benefit-finder/issues/908, https://github.com/GSA/px-benefit-finder/issues/751, https://github.com/GSA/px-benefit-finder/issues/710,
