### ISSUE TITLE
QA | Content v0.2.0.beta.1 release

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#994]
### Domain

other

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

**Due:
03/13/24**

Issues:

- [x] #50, 
- [x] #898, 
- [x] #910, 
- [x] #849, 
- [x] #819

### Description

#898 , #910 , and #849 are related to content entry validation for error prevention
#50 are ui content updates

**Comment by fongcindy** [comment]
@scottqueen-bixal 
Hi Scott,
Diego has started his QA, he started with the "is in English" [#50](https://github.com/GSA/px-benefit-finder/issues/50)
and content capitalization [#819](https://github.com/GSA/px-benefit-finder/issues/819) and since those weren't there he didn't proceed with the others. He is using the correct link: https://bf-cms-main.bxdev.net/ via VDI.

**Comment by EnriqueOrt** [comment]
@diegocob - could you please provide some additional information on what items have been completed and what is still pending as of today? Thank you in advance

**Comment by diegocob** [comment]
Working on it. Will finish by tmr.
- [ ] Completed https://github.com/GSA/px-benefit-finder/issues/50,  
- [ ] Unable to do the three middle tickets, will reach out to @gchi25 :
- [ ] https://github.com/GSA/px-benefit-finder/issues/898
- [ ] https://github.com/GSA/px-benefit-finder/issues/910
- [ ] https://github.com/GSA/px-benefit-finder/issues/849
- [ ] 80% done with the content capitalization: https://github.com/GSA/px-benefit-finder/issues/819

**Comment by diegocob** [comment]
QA 100% done.

- Created a ticket to make some content changes on [ticket #1052](https://github.com/GSA/px-benefit-finder/issues/1052)
- Create a way to download CMS content to a spreadsheet [#1053](https://github.com/GSA/px-benefit-finder/issues/1053)
